### ISSUE TITLE
You have error in image_classification/infer.py

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/models#1089]
### error message
```
Traceback (most recent call last):
  File "infer.py", line 94, in <module>
    main()
  File "infer.py", line 90, in main
    infer(args)
  File "infer.py", line 68, in infer
    test_reader = paddle.batch(reader.test(), batch_size=test_batch_size)
TypeError: test() takes exactly 1 argument (0 given)
```
### cause
The test function takes 1 argument
https://github.com/PaddlePaddle/models/blob/53937db0f1a29c90cd4e23c1198d34c81bfed1b2/fluid/image_classification/reader.py#L163
### command
```
python infer.py --use_gpu 0  --batch_size 1
```

**Comment by luotao1** [comment]
How about change to 
```
def test(file_list=TEST_LIST):
```
