### ISSUE TITLE
face_detection 多卡下多个pass后,拿不到数据

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1245]
paddle_version: 0.15.0
相同配置下，跑两次，第一次挂在第61个pass，第二次挂在第10个pass
```bash
Pass 61, batch 530, face loss 2.25895452499, head loss 2.0783700943, time 2.00991797447
Pass 61, batch 540, face loss 1.47570765018, head loss 1.28614866734, time 2.35021495819
Pass 61, batch 550, face loss 1.9905424118, head loss 1.82294678688, time 2.87708592415
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    train(args, config, train_file_list, optimizer_method="momentum")
  File "train.py", line 132, in train
    im, face_box, head_box, labels, lod = next(train_reader)
TypeError: 'NoneType' object is not iterable
```

**Comment by fangzong12** [comment]
问一下，你的parallel关掉了么，多卡

**Comment by ccmeteorljh** [comment]
> 问一下，你的parallel关掉了么，多卡
没关，用的默认配置

**Comment by fangzong12** [comment]
> > 问一下，你的parallel关掉了么，多卡
> > 没关，用的默认配置

好吧，都不知道怎么回事

**Comment by qingqing01** [comment]
@ccmeteorljh  请问现在是否还有问题？ 最新的develop代码有相应的修改。

**Comment by ccmeteorljh** [comment]
> @ccmeteorljh 请问现在是否还有问题？ 最新的develop代码有相应的修改。

用了最新develop的代码和9月20号paddle编译的包，该问题依然存在

**Comment by ccmeteorljh** [comment]
关闭多进程读数据，问题依然存在
