### ISSUE TITLE
测试数据“Cannot open file output/159/conv2d_15.w_0”

### ISSUE THREAD

**Issue by neverland0621** [PaddlePaddle/models#1259]
我先用单张卡测试，遇见错误如下，我看到要求下载的预训练模型里只有conv2d_0.w_0到conv2d_14.w_0。所以conv2d_15.w_0是在哪里呢？
报错具体如下：
Traceback (most recent call last):
  File "widerface_eval.py", line 312, in <module>
    exe, args.model_dir, main_program=main_program)
  File "/home/jw/.conda/envs/Paddle/lib/python2.7/site-packages/paddle/fluid/io.py", line 496, in load_persistables
    filename=filename)
  File "/home/jw/.conda/envs/Paddle/lib/python2.7/site-packages/paddle/fluid/io.py", line 376, in load_vars
    filename=filename)
  File "/home/jw/.conda/envs/Paddle/lib/python2.7/site-packages/paddle/fluid/io.py", line 407, in load_vars
    executor.run(load_prog)
  File "/home/jw/.conda/envs/Paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot open file output/159/conv2d_15.w_0 for load op at [/paddle/paddle/fluid/operators/load_op.cc:39]

**Comment by qingqing01** [comment]
@neverland0621 预训练模型是初始化backbone部分的，不是完整的PyramidBox模型。 如果你只做eval，可以下载已经训练好的PyramidBox模型：https://github.com/PaddlePaddle/models/tree/develop/fluid/face_detection#%E6%A8%A1%E5%9E%8B%E5%8F%91%E5%B8%83

**Comment by YueXiNPU** [comment]
@qingqing01 非常感谢您的回复。按照您连接，我们下载了已经训练好的PyramidBox模型。我们用单张GPU 1080Ti，11G显存，进行eval，报内存不足的错误。请问仅仅eval，对显卡显存要求高吗？

**Comment by neverland0621** [comment]
好的，已解决。谢谢。

**Comment by qingqing01** [comment]
@YueXiNPU 
PyramidBox模型评估时图片是变长的，可能会遇到非常大的图片，显存不足是可能的。可以 参考 https://github.com/PaddlePaddle/models/issues/1262#issuecomment-422724707 评估是加显存优化吧，后续我们也验证下，加上。

该issue关闭了，在#1262里继续讨论吧。
