### ISSUE TITLE
ocr_recognition API changed

### ISSUE THREAD

**Issue by chuanqi129** [PaddlePaddle/models#1287]
When I use command ` python train.py --use_gpu False --parallel=False --total_step 5 --save_model_period 5 --save_model_dir ./models`, I got below information. Could you have a look into it?

`[chuanqiw@mlt-skx089 ocr_recognition]$ python train.py --use_gpu False --parallel=False --total_step 5 --save_model_period 5 --save_model_dir ./models
-----------  Configuration Arguments -----------
average_window: 0.15
batch_size: 32
eval_period: 15000
init_model: None
log_period: 1000
max_average_window: 12500
min_average_window: 10000
model: crnn_ctc
parallel: 0
profile: False
save_model_dir: ./models
save_model_period: 5
skip_batch_num: 0
skip_test: False
total_step: 5
use_gpu: 0
------------------------------------------------
/home/chuanqiw/.local/lib/python2.7/site-packages/paddle/fluid/evaluator.py:71: Warning: The EditDistance is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.EditDistance instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    main()
  File "train.py", line 214, in main
    train(args)
  File "train.py", line 60, in train
    args, data_shape, num_classes)
  File "/home/chuanqiw/workspace/aipg_paddle/models/fluid/ocr_recognition/crnn_ctc_model.py", line 212, in ctc_train_net
    max_average_window=args.max_average_window)
  File "/home/chuanqiw/.local/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 1275, in __init__
    self._add_average_apply_op(block, param_grad)
  File "/home/chuanqiw/.local/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 1304, in _add_average_apply_op
    layers.elementwise_div(x=sum, y=tmp, out=param)
TypeError: elementwise_div() got an unexpected keyword argument 'out'
`

**Comment by kolinwei** [comment]
这个问题新的代码已经修了
