### ISSUE TITLE
DeepASR 运行 AISHELL例子 training报错

### ISSUE THREAD

**Issue by IrishCoffee** [PaddlePaddle/models#1370]
各位好，我在编译运行deepasr aishell这个例子的时候，先是运行sh profile.sh，会报一个memory不够的问题。

------------------------------------------------
.........Traceback (most recent call last):
  File "../../tools/profile.py", line 210, in <module>
    profile(args)
  File "../../tools/profile.py", line 193, in profile
    return_numpy=False)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: ptr_ should not be null
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/framework/tensor.h:180]
PaddlePaddle Call Stacks:
0       0x7fe12816db36p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486

如果我直接运行sh train.sh, 会报如下错误。
```
xjia@nvidia:~/work/PaddlePaddle/models/fluid/DeepASR/examples/aishell$ sh train.sh
-----------  Configuration Arguments -----------
batch_size: 64
checkpoints: checkpoints
class_num: 3040
device: GPU
frame_dim: 80
hidden_dim: 1024
infer_models:
init_model_path: None
learning_rate: 6.4e-05
mean_var: data/global_mean_var
minimum_batch_size: 1
parallel: True
pass_num: 100
print_per_batches: 100
proj_dim: 512
stacked_num: 5
train_feature_lst: data/train_feature.lst
train_label_lst: data/train_label.lst
val_feature_lst: data/val_feature.lst
val_label_lst: data/val_label.lst
------------------------------------------------
API get_places is deprecated since 0.15.0. Please use ParallelExecutor instead.
Traceback (most recent call last):
  File "../../train.py", line 292, in <module>
    train(args)
  File "../../train.py", line 156, in train
    parallel=args.parallel)
  File "/home/xjia/work/PaddlePaddle/models/fluid/DeepASR/model_utils/model.py", line 91, in stacked_lstmp_model
    pd = fluid.layers.ParallelDo(places)
AttributeError: 'module' object has no attribute 'ParallelDo'
```
我是在一个单机1080ti的GPU上运行的，已经确认paddle成功安装。

**Comment by chengduoZH** [comment]
@IrishCoffee  您安装的是什么版本的Paddle?

**Comment by IrishCoffee** [comment]
xjia@nvidia:~/work/PaddlePaddle/models/fluid/DeepASR/examples/aishell$ paddle version
PaddlePaddle 1.0.1.post97, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

我直接pip安装的。

**Comment by chengduoZH** [comment]
现在ParallelDo从layers.中去掉了   你可以通过这种方式调用
```
from paddle.fluid.layers.control_flow import ParallelDo
```

把layers.ParallelDo 改成ParallelDo

**Comment by IrishCoffee** [comment]
替换掉ParallelDo的调用后， 依然会报一些错误。请问这个example对于运行环境有什么要求吗？我机器上有一块1080Ti，怎么还报找不到device这种错误。


xjia@nvidia:~/work/PaddlePaddle/models/fluid/DeepASR/examples/aishell$ sh train.sh
-----------  Configuration Arguments -----------
batch_size: 64
checkpoints: checkpoints
class_num: 3040
device: GPU
frame_dim: 80
hidden_dim: 1024
infer_models:
init_model_path: None
learning_rate: 6.4e-05
mean_var: data/global_mean_var
minimum_batch_size: 1
parallel: True
pass_num: 100
print_per_batches: 100
proj_dim: 512
stacked_num: 5
train_feature_lst: data/train_feature.lst
train_label_lst: data/train_label.lst
val_feature_lst: data/val_feature.lst
val_label_lst: data/val_label.lst
------------------------------------------------
API get_places is deprecated since 0.15.0. Please use ParallelExecutor instead.
/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/control_flow.py:286: Warning: API ParallelDo is deprecated since 0.15.0. Please use ParallelExecutor instead.
  Warning)
Traceback (most recent call last):
  File "../../train.py", line 292, in <module>
    train(args)
  File "../../train.py", line 172, in train
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: no CUDA-capable device is detected at [/paddle/paddle/fluid/platform/gpu_info.cc:33]
PaddlePaddle Call Stacks:
0       0x7f437fa1eb36p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f4380d05c66p paddle::platform::GetCUDADeviceCount() + 246
2       0x7f4380d072afp paddle::platform::SetDeviceId(int) + 31
3       0x7f4380baad0cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 492
4       0x7f437fae9c61p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 353
5       0x7f437faea660p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7f437fa0474dp
7       0x7f437fa2f8b4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8             0x4cad00p PyEval_EvalFrameEx + 28048
9             0x4c2705p PyEval_EvalCodeEx + 597
10            0x4ca088p PyEval_EvalFrameEx + 24856
11            0x4c2705p PyEval_EvalCodeEx + 597
12            0x4ca7dfp PyEval_EvalFrameEx + 26735
13            0x4c2705p PyEval_EvalCodeEx + 597
14            0x4c24a9p PyEval_EvalCode + 25
15            0x4f19efp
16            0x4ec372p PyRun_FileExFlags + 130
17            0x4eaaf1p PyRun_SimpleFileExFlags + 401
18            0x49e208p Py_Main + 1736
19      0x7f43b9fc8830p __libc_start_main + 240
20            0x49da59p _start + 41

**Comment by jiayifang1** [comment]
你好，请问你这个找不到 设备"no CUDA-capable device is detected “，这个问题解决了吗
