### ISSUE TITLE
run policy_gradient failed

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/models#1373]
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1022 16:02:46.179663 104725 init.cc:47] Init commandline: dummy run.py --tryfromenv=use_pinned_memory,check_nan_inf,benchmark,warpctc_dir,eager_delete_scope,use_mkldnn,initial_cpu_memory_in_mb,init_allocated_mem,free_idle_memory,paddle_num_threads,dist_threadpool_size,cpu_deterministic
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    brain.build_net()
  File "/home/wangsijiang01/work/models/fluid/policy_gradient/brain.py", line 38, in build_net
    self.inferece_program = fluid.defaul_main_program().clone()
AttributeError: 'module' object has no attribute 'defaul_main_program'

**Comment by wanghaoshuang** [comment]
`self.inferece_program = fluid.defaul_main_program().clone()`
->
`self.inferece_program = fluid.default_main_program().clone()`
