### ISSUE TITLE
How to save MobileNet-SSD model? with detection mAP evaluator?

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/models#1459]
When training a MobileNet-SSD model, the `train.py` script allows for saving persistables using
```
fluid.io.save_persistables(exe, model_path, main_program=main_prog)
```
But how can we save the whole model?
In order to save the whole model for inference using:
```
fluid.io.save_inference_model("abc", feed_dict, [target], exe)
```
we need to provide `feed_dict` and `target`.
1. What should the `feed_dict` be?
Usually, the `feed` argument of `exe.run()` method suggest the answer, but in MobileNet-SSD, the `feed` is not defined. The `py_reader` is used there.
2. What should the `target` be?
Several attempts to put anything into target failed with message
```
Traceback (most recent call last):
...
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/io.py", line 654, in save_inference_model
    main_program = main_program._prune(targets=target_vars)
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/framework.py", line 1739, in _prune
    "The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.
```
3. Is it possible to save the model with the `DetectionMAP` evaluator?

**Comment by qingqing01** [comment]
@wojtuss Please see

 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py#L117

and 

https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py#L165

You can change line 165:

```
test_py_reader, map_eval, output, input = build_program(
        main_prog=test_prog,
        startup_prog=startup_prog,
        train_params=train_params,
is_train=False)
test_prog = test_prog.clone(for_test=True)
```

Then:

```
 fluid.io.save_inference_model(model_save_dir, [input.name],  [output], exe, test_prog)
```

If you want to do inference, the target is the output of `fluid.layers.detection_output`.
You can save the model with the DetectionMAP evaluator by using `test_prog`

**Comment by wojtuss** [comment]
@qingqing01 ,
Thank you! To save the model with the DetectionMAP I need also to add the `map_eval` to targets, right?
However, calling
```
fluid.io.save_inference_model(model_save_dir, [input.name],  [output, map_eval], exe, test_prog)
```
gives
```
Traceback (most recent call last):
  File "train.py", line 332, in <module>
    val_file_list=val_file_list)
  File "train.py", line 181, in train
    [output, map_eval], exe, test_prog)
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/io.py", line 616, in save_inference_model                                                                                               
    raise ValueError("'target_vars' should be a list of Variable.")
ValueError: 'target_vars' should be a list of Variable.
```
I have tried also
```
cur_map, accum_map = map_eval.get_map_var()
fluid.io.save_inference_model(model_save_dir, [input.name],  [output, accum_map], exe, test_prog)
```
Then I got
```
Traceback (most recent call last):                                                                                                                                                                                 
  File "train.py", line 332, in <module>                                                                                                                                                                           
    val_file_list=val_file_list)                                                                                                                                                                                   
  File "train.py", line 181, in train                                                                                                                                                                              
    [output, accum_map], exe, test_prog)                                                                                                                                                                           
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/io.py", line 671, in save_inference_model                                                                                                
    save_persistables(executor, dirname, main_program, params_filename)                                                                                                                                            
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/io.py", line 292, in save_persistables                                                                                                   
    filename=filename)                                                                                                                                                                                             
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/io.py", line 170, in save_vars                                                                                                           
    filename=filename)                                                                                                                                                                                             
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/io.py", line 201, in save_vars                                                                                                           
    executor.run(save_program)                                                                                                                                                                                     
  File "/home/wojtuss/repos/PaddlePaddle/Paddle/build/python/paddle/fluid/executor.py", line 470, in run                                                                                                           
    self.executor.run(program.desc, scope, 0, True, True)                                                                                                                                                          
paddle.fluid.core.EnforceNotMet: holder_ should not be null                                                                                                                                                        
Tensor not initialized yet when Tensor::type() is called. at [/home/wojtuss/repos/PaddlePaddle/Paddle/paddle/fluid/framework/tensor.h:141]                                                                         
PaddlePaddle Call Stacks:                                                                                                                                                                                          
0       0x7fc4499ebcf4p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 466                                                                                
1       0x7fc4499ed464p paddle::framework::Tensor::type() const + 194                                                                                                                                              
2       0x7fc44a8a7dc6p paddle::operators::SaveOp::SaveLodTensor(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::d
etail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, bo
ost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::voi
d_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*) const + 872                                                                                                
3       0x7fc44a8a7887p paddle::operators::SaveOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detai
l::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost:
:detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, 
boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 217                                                                                                   
4       0x7fc44ad6ecdfp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::det
ail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 817                                                                                                      
5       0x7fc449b9d877p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 713                                            
6       0x7fc449b9a1f0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 182                                                                 
7       0x7fc4499ba44fp
8       0x7fc4499e6d26p
9       0x7fc4499e3bfbp
10      0x7fc4499daf45p
11      0x7fc4499daff3p
12      0x7fc4499f9bf2p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2581
13            0x4c37edp PyEval_EvalFrameEx + 31165
14            0x4b9ab6p PyEval_EvalCodeEx + 774
15            0x4c16e7p PyEval_EvalFrameEx + 22711
16            0x4b9ab6p PyEval_EvalCodeEx + 774
17            0x4c16e7p PyEval_EvalFrameEx + 22711
18            0x4b9ab6p PyEval_EvalCodeEx + 774
19            0x4c16e7p PyEval_EvalFrameEx + 22711
20            0x4b9ab6p PyEval_EvalCodeEx + 774
21            0x4c16e7p PyEval_EvalFrameEx + 22711
22            0x4b9ab6p PyEval_EvalCodeEx + 774
23            0x4c16e7p PyEval_EvalFrameEx + 22711
24            0x4b9ab6p PyEval_EvalCodeEx + 774
25            0x4c1e6fp PyEval_EvalFrameEx + 24639
26            0x4b9ab6p PyEval_EvalCodeEx + 774
27            0x4eb30fp
28            0x4e5422p PyRun_FileExFlags + 130
29            0x4e3cd6p PyRun_SimpleFileExFlags + 390
30            0x493ae2p Py_Main + 1554
31      0x7fc482092830p __libc_start_main + 240
32            0x4933e9p _start + 41
```
What target should it be?

**Comment by qingqing01** [comment]
@wojtuss 

I tested in `evaly.py`,  after running one time,  then, mode saving is ok:

```
test_map, = exe.run(test_prog, fetch_list=[accum_map])
fluid.io.save_inference_model('test-model', [image.name, gt_label.name, gt_box.name, difficult.name], [nmsed_out, cur_map, accum_map], exe, test_prog)
```

Since the mAP depends on `gt_label`, `gt_box`, `difficult` variables, so these also need to save.

**Comment by wojtuss** [comment]
@qingqing01 , thank you very much for your help! It helped a lot!
