### ISSUE TITLE
gru4rec

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1487]
多机下reader读数据时候应该根据trainer_id 切分

**Comment by frankwhzhang** [comment]
根据trainer的文件路径来划分，paddlecloud上是按照文件自动切分

**Comment by jackyhawk** [comment]
在单机自己的服务器上，会报这个错误，不知道遇到过没有？ @ccmeteorljh 

E1210 10:11:24.682713 1501 grpc_client.cc:338] SendRPC name:[fc_1.w_0@GRAD.block0.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683696 1501 grpc_client.cc:338] SendRPC name:[embedding_0.w_0@GRAD.block0.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683753 1501 grpc_client.cc:338] SendRPC name:[fc_0.w_0@GRAD.block1.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683784 1501 grpc_client.cc:338] SendRPC name:[fc_0.b_0@GRAD.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683814 1501 grpc_client.cc:338] SendRPC name:[gru_0.w_0@GRAD.block1.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
E1210 10:11:24.683840 1501 grpc_client.cc:338] SendRPC name:[gru_0.b_0@GRAD.trainer_1], ep:[127.0.0.1:6000], status:[-1] meets grpc error, error_code:4 error_message:Deadline Exceeded error_details:
('use_cuda:', False)
start constuct word dict
run distribute training
run trainer
epoch_1 start
Traceback (most recent call last):
File "cluster_train.py", line 140, in 
train()
File "cluster_train.py", line 137, in train
train_loop(t.get_trainer_program())
File "cluster_train.py", line 102, in train_loop
fetch_list=fetch_list)
File "/data0/home/jy7/python_installed/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: internal error in RPCClient at [/paddle/paddle/fluid/operators/send_barrier_op.cc:47]
PaddlePaddle Call Stacks:
0 0x7fde36e8fab6p paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr::exception_ptr, char const*, int) + 486
1 0x7fde37890794p paddle::operators::SendBarrierOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 788
2 0x7fde37b04b58p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 232
3 0x7fde36f530fbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
4 0x7fde36f53ee0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
5 0x7fde36e748bdp
6 0x7fde36ec4cb4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7 0x7fde6c34a45ap PyEval_EvalFrameEx + 34762
8 0x7fde6c34b868p PyEval_EvalCodeEx + 1976
9 0x7fde6c3481d1p PyEval_EvalFrameEx + 25921
10 0x7fde6c34b868p PyEval_EvalCodeEx + 1976
11 0x7fde6c3481d1p PyEval_EvalFrameEx + 25921
12 0x7fde6c34b868p PyEval_EvalCodeEx + 1976
13 0x7fde6c3481d1p PyEval_EvalFrameEx + 25921
14 0x7fde6c34b868p PyEval_EvalCodeEx + 1976
15 0x7fde6c34ba79p PyEval_EvalCode + 25
16 0x7fde6c36e02ap PyRun_FileExFlags + 138
17 0x7fde6c36fe23p PyRun_SimpleFileExFlags + 211
18 0x7fde6c388c4ep Py_Main + 2830
19 0x7fde6b577b35p __libc_start_main + 245
20 0x40071ep
