### ISSUE TITLE
deeplabv3+如何自定义类别？

### ISSUE THREAD

**Issue by 408550969** [PaddlePaddle/models#1497]
我换了一个数据集，将train.py的num_classes改成10并把models.py里的label_number改成10。但是运行就报错：
  File "./train.py", line 148, in <module>
    'label': labels})
  File "/home/cll/.local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 277, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-11235850 != -in_size:-11235859.
Invalid shape is given. at [/paddle/paddle/fluid/operators/reshape_op.cc:98]
PaddlePaddle Call Stacks:
而且我发现只有调整为默认的19它才不报错，请问应该如何修改？
还有train.py里的loss
label_nignore = (label < num_classes).astype('float32')
这个是什么意思？

**Comment by xieqingxing** [comment]
你好,请问解决了吗?

**Comment by 408550969** [comment]
没有

**Comment by cjld** [comment]
你好，除开train.py里面需要改类别数，models.py里面也有类别数需要改

**Comment by xieqingxing** [comment]
model.py和train.py都改了，还是跟提问者报一样的错，请问是为什么？

**Comment by cjld** [comment]
pr #1562
add num_classes config to deeplabv3+

Now you can train any number of classes you want:

python3 ./train.py \
    --batch_size=1 \
    --train_crop_size=769 \
    --total_step=50 \
    --num_classes=$NUMBER_YOU_WANT \
    --init_weights_path=$INIT_WEIGHTS_PATH \
    --save_weights_path=$SAVE_WEIGHTS_PATH \
    --dataset_path=$DATASET_PATH

**Comment by busyboxs** [comment]
@cjld 你好，我将num_classes改为9之后出现了以下错误，但是不知道是哪个conv的问题

```
Traceback (most recent call last):
  File "/media/yangshun/0008EB70000B0B9F/PycharmProjects/deeplabv3+/train.py", line 168, in <module>
    fetch_list=[pred, loss_mean])
  File "/home/yangshun/anaconda2/envs/paddle1.2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected in_dims.size() == filter_dims.size(), but received in_dims.size():4 != filter_dims.size():1.
Conv input dimension and filter dimension should be the same. at [/paddle/paddle/fluid/operators/conv_op.cc:50]
PaddlePaddle Call Stacks: 
0       0x7fcd02f97e36p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fcd0416ee42p paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const + 7730
2       0x7fcd046163cdp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 77
3       0x7fcd04612dafp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
4       0x7fcd03065afbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
5       0x7fcd03066750p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7fcd02f7b11dp
7       0x7fcd02fae544p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7fcd398351a7p PyEval_EvalFrameEx + 28695
9       0x7fcd398376c9p PyEval_EvalCodeEx + 2025
10      0x7fcd39834b98p PyEval_EvalFrameEx + 27144
11      0x7fcd398376c9p PyEval_EvalCodeEx + 2025
12      0x7fcd398378eap PyEval_EvalCode + 26
13      0x7fcd39850badp
14      0x7fcd39851d28p PyRun_FileExFlags + 120
15      0x7fcd39852f48p PyRun_SimpleFileExFlags + 232
16      0x7fcd3986516cp Py_Main + 2988
17      0x7fcd38a0e830p __libc_start_main + 240
18      0x55af33e8507fp
```
