### ISSUE TITLE
deeplabv3+运行exe.run()时报paddle.fluid.core.EnforceNotMet: Enforce failed. Insufficient GPU memory to allocation.错误

### ISSUE THREAD

**Issue by silverfly1992** [PaddlePaddle/models#1543]
Traceback (most recent call last):
  File "/home/***/models/fluid/PaddleCV/deeplabv3+/train.py", line 129, in <module>
    exe.run(sp)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected allocating <= available, but received allocating:10906743472 > available:10723983104.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:170]
PaddlePaddle Call Stacks: 
0       0x7f33f352cea6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f33f4dce9fep paddle::platform::GpuMaxChunkSize() + 782
2       0x7f33f4dc621ap
3       0x7f3431cd5a99p
4       0x7f33f4dc568dp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 93
5       0x7f33f4dc5975p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 37
6       0x7f33f4dc6025p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long, paddle::memory::allocation::Allocator::Attr) + 389
7       0x7f33f4dc7f6bp paddle::memory::allocation::Allocator::Allocate(unsigned long, paddle::memory::allocation::Allocator::Attr) + 27
8       0x7f33f4db9d43p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 435
9       0x7f33f4db9e61p paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 33
10      0x7f33f4bc6570p paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long, paddle::memory::allocation::Allocator::Attr) + 48
11      0x7f33f4d727c7p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index, paddle::memory::allocation::Allocator::Attr, unsigned long) + 151
12      0x7f33f3ab13cep paddle::operators::FillConstantOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 958
13      0x7f33f4d2dc7fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
14      0x7f33f3601ba3p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
15      0x7f33f36025d0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
16      0x7f33f3518c4bp
17      0x7f33f355482ep
18      0x564da23b1b94p _PyCFunction_FastCallDict + 340
19      0x564da24417cep
20      0x564da2463cbap _PyEval_EvalFrameDefault + 762
21      0x564da243aa94p
22      0x564da243b941p
23      0x564da2441755p
24      0x564da2463cbap _PyEval_EvalFrameDefault + 762
25      0x564da243c459p PyEval_EvalCodeEx + 809
26      0x564da243d1ecp PyEval_EvalCode + 28
27      0x564da24b79a4p
28      0x564da24b7da1p PyRun_FileExFlags + 161
29      0x564da24b7fa4p PyRun_SimpleFileExFlags + 452
30      0x564da24bba9ep Py_Main + 1598
31      0x564da23834bep main + 238
32      0x7f343191d830p __libc_start_main + 240
33      0x564da246a773p

paddle gpu版已成功安装cuda9.0cudnn7

**Comment by silverfly1992** [comment]
用cpu没问题，在终端执行export FLAGS_fraction_of_gpu_memory_to_use=0 后，还是有问题

**Comment by silverfly1992** [comment]
我的显卡是单卡1080ti

**Comment by Hukongtao** [comment]
看报错都是关于CUDA得，是不是你的CUDA或者cudnn装得不对啊？最新版本得paddle对CUDA和cudnn版本有要求得？

**Comment by silverfly1992** [comment]
我装的cuda9.0cudnn7，就是paddle所需的版本，而且我跑keras pytorch这些框架都没问题啊

**Comment by geng007** [comment]
> 我装的cuda9.0cudnn7，就是paddle所需的版本，而且我跑keras pytorch这些框架都没问题啊

请问你解决了吗.我也遇到这个问题

**Comment by cjld** [comment]
如果显存不足，请使用group norm并且改小batch size

**Comment by cjld** [comment]
1080ti推荐配置是使用gn，batch size=4， total_step=180000
