### ISSUE TITLE
fork的models-1/ctr branch:ctr2 infer时有异常

### ISSUE THREAD

**Issue by awper361** [PaddlePaddle/models#155]
```text
Traceback (most recent call last):
  File "infer.py", line 80, in <module>
    ctr_inferer = CTRInferer(args.model_gz_path)
  File "infer.py", line 54, in __init__
    is_infer=True)
  File "/home/zhangjunmin/mycore/model/paddle/models-1-ctr2/ctr/network_conf.py", line 44, in __init__
    if self.model_type.is_classification():
AttributeError: 'int' object has no attribute 'is_classification'

修改self.model_type = ModelType.create_classification()后，另有如下出错

Traceback (most recent call last):
  File "infer.py", line 80, in <module>
    ctr_inferer = CTRInferer(args.model_gz_path)
  File "infer.py", line 54, in __init__
    is_infer=True)
  File "/home/zhangjunmin/mycore/model/paddle/models-1-ctr2/ctr/network_conf.py", line 45, in __init__
    self.model = self._build_classification_model(self.dnn, self.lr)
  File "/home/zhangjunmin/mycore/model/paddle/models-1-ctr2/ctr/network_conf.py", line 99, in _build_classification_model
    input=self.output, label=self.click)
AttributeError: 'CTRmodel' object has no attribute 'click'
```

**Comment by awper361** [comment]
@Superjom

**Comment by Superjomn** [comment]
fixed in https://github.com/Superjom/models-1/commit/a4815f33aa55dff6eebd98dcceadb6528226c931
