### ISSUE TITLE
DeepLabv3+ xception65_initialize weight, not compatible with paddlepaddle v1.1 or v1.2

### ISSUE THREAD

**Issue by tycallen** [PaddlePaddle/models#1551]
env:
`CUDA Capability: 61, Driver Version: 9.1, Runtime Version: 9.0
device: 0, cuDNN Version: 7.0.`

when load this weight: http://paddlemodels.cdn.bcebos.com/deeplab/deeplabv3plus_xception65_initialize.tar.gz

code:
`fluid.io.load_params(
            exe, dirname="", filename=args.init_weights_path, main_program=tp)`

got error:
`load from: init_weight
Traceback (most recent call last):
  File "./train.py", line 135, in <module>
    load_model()
  File "./train.py", line 44, in load_model
    exe, dirname="", filename=args.init_weights_path, main_program=tp)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 487, in load_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 395, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 436, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: tensor version 91 is not supported. at [/paddle/paddle/fluid/framework/lod_tensor.cc:284]
PaddlePaddle Call Stacks:
0       0x7f777148be86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f7772ae5c16p paddle::framework::DeserializeFromStream(std::istream&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 646
2       0x7f7771e9b6e2p paddle::operators::LoadCombineOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 722
3       0x7f7772c8ec2fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
4       0x7f7771562b53p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
5       0x7f7771563580p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
6       0x7f7771477d3bp
7       0x7f77714b3deep
8             0x4c5326p PyEval_EvalFrameEx + 37958
9             0x4b9b66p PyEval_EvalCodeEx + 774
10            0x4c17c6p PyEval_EvalFrameEx + 22758
11            0x4b9b66p PyEval_EvalCodeEx + 774
12            0x4c17c6p PyEval_EvalFrameEx + 22758
13            0x4b9b66p PyEval_EvalCodeEx + 774
14            0x4c17c6p PyEval_EvalFrameEx + 22758
15            0x4b9b66p PyEval_EvalCodeEx + 774
16            0x4c17c6p PyEval_EvalFrameEx + 22758
17            0x4b9b66p PyEval_EvalCodeEx + 774
18            0x4c1f56p PyEval_EvalFrameEx + 24694
19            0x4b9b66p PyEval_EvalCodeEx + 774
20            0x4eb69fp
21            0x4e58f2p PyRun_FileExFlags + 130
22            0x4e41a6p PyRun_SimpleFileExFlags + 390
23            0x4938cep Py_Main + 1358
24      0x7f7815688830p __libc_start_main + 240
25            0x493299p _start + 41`

in v1.2: error is `tensor version 91 is not supported`
in v1.1: error is `tensor version 8 is not supported`

Which version these weight belongs to? Or where I can get weight compatible with v1.2

**Comment by luotao1** [comment]
@cjld 能帮忙看一下么？

**Comment by tycallen** [comment]
> @cjld 能帮忙看一下么？

抱歉我又检查了下代码，问题出在
`fluid.io.load_params( exe, dirname="", filename=args.init_weights_path, main_program=tp)`里，权重文件路径不对。但路径不对报的这个错是真的看不懂啊。

另外，加载过了，开始训练后有另一个问题：
在执行`retv = exe.run(tp,
                       feed={'img': imgs,
                             'label': labels},
                       fetch_list=[pred, loss_mean])`时，出现了：

```
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-11235852 != -in_size:-11235859.
Invalid shape is given. at [/paddle/paddle/fluid/operators/reshape_op.cc:98]
PaddlePaddle Call Stacks:
0       0x7f38820aae86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f3882b84976p paddle::operators::ReshapeOp::ValidateShape(std::vector<int, std::allocator<int> >, paddle::framework::DDim const&) + 2854
2       0x7f3882b84f38p paddle::operators::ReshapeOp::InferShape(paddle::framework::InferShapeContext*) const + 664
3       0x7f3882b857f0p paddle::operators::Reshape2Op::InferShape(paddle::framework::InferShapeContext*) const + 576
4       0x7f38838b194dp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 77
5       0x7f38838adc2fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
6       0x7f3882181b53p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
7       0x7f3882182580p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
8       0x7f3882096d3bp
9       0x7f38820d2deep
10            0x4c5326p PyEval_EvalFrameEx + 37958
11            0x4b9b66p PyEval_EvalCodeEx + 774
12            0x4c17c6p PyEval_EvalFrameEx + 22758
13            0x4b9b66p PyEval_EvalCodeEx + 774
14            0x4eb69fp
15            0x4e58f2p PyRun_FileExFlags + 130
16            0x4e41a6p PyRun_SimpleFileExFlags + 390
17            0x4938cep Py_Main + 1358
18      0x7f39bc02c830p __libc_start_main + 240
19            0x493299p _start + 41
```


打印了img的shape，是(1, 3, 769, 769)。
网络只改了class_num

**Comment by qingqing01** [comment]
@tycallen 

您好，调试了下，发现是因为预训练模型 `deeplabv3plus_xception65_initialize.params` 里包含了 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/deeplabv3%2B/models.py#L310 该层的初始化参数，导致即使改了边 train.py里的class number， 以及models.py里的label_number，加载初始化模型之后 该conv的输出 channel容然是19，导致后面的reshape出错。

解决办法需要去掉初始化模型里该层参数，为了验证你可以不加载初始化模型。

**Comment by cjld** [comment]
pr #1562 
add num_classes config to deeplabv3+

Now you can train any number of classes you want:
```
python3 ./train.py \
    --batch_size=1 \
    --train_crop_size=769 \
    --total_step=50 \
    --num_classes=$NUMBER_YOU_WANT \
    --init_weights_path=$INIT_WEIGHTS_PATH \
    --save_weights_path=$SAVE_WEIGHTS_PATH \
    --dataset_path=$DATASET_PATH
```

**Comment by busyboxs** [comment]
@tycallen 你好，请问下训练deeplabv3+大概需要多少显存啊

**Comment by xieqingxing** [comment]
> @tycallen
> 
> 您好，调试了下，发现是因为预训练模型 `deeplabv3plus_xception65_initialize.params` 里包含了 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/deeplabv3%2B/models.py#L310 该层的初始化参数，导致即使改了边 train.py里的class number， 以及models.py里的label_number，加载初始化模型之后 该conv的输出 channel容然是19，导致后面的reshape出错。
> 
> 解决办法需要去掉初始化模型里该层参数，为了验证你可以不加载初始化模型。

请问下带有num_class参数的具体是xception哪一层呢？模型从头开始训练的效果不是很好，我使用官方训练好的模型，筛除xception的参数就可以进行训练了

**Comment by xieqingxing** [comment]
> > @tycallen
> > 您好，调试了下，发现是因为预训练模型 `deeplabv3plus_xception65_initialize.params` 里包含了 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/deeplabv3%2B/models.py#L310 该层的初始化参数，导致即使改了边 train.py里的class number， 以及models.py里的label_number，加载初始化模型之后 该conv的输出 channel容然是19，导致后面的reshape出错。
> > 解决办法需要去掉初始化模型里该层参数，为了验证你可以不加载初始化模型。
> 
> 请问下带有num_class参数的具体是xception哪一层呢？模型从头开始训练的效果不是很好，我使用官方训练好的模型，筛除xception的参数就可以进行训练了

您上方给的链接里头看不到标记的层，310行现在已经是空行的呢

**Comment by cjld** [comment]
您好，该问题已修复，请尝试最新版本的代码
