### ISSUE TITLE
PaddleRec/word2vec 使用建议

### ISSUE THREAD

**Issue by ZeyuChen** [PaddlePaddle/models#1555]
1. word2vec模型放在PaddleNLP是不是更合理？
2. 现在基于Fluid 1.2发布的模型是否能支持python2和python3，这个repo下的脚本只能支持python2。如果只能支持python2是否在Markdown上新增下说明。
3. Preprocess脚本运行时，默认认为用户不是在local模式下使用的，会导致调用出错。对local模式和distribute模式的使用区别再文档中没有体现。
4. 预处理的脚本可否考虑新增处理进度？

**Comment by ZeyuChen** [comment]
预处理脚本跑不通

Bug1 word_count[native_to_unicode('<UNK>')] = 0 没有初始化，后面直接+1，导致出错

Bug2，out of range
Traceback (most recent call last):
  File "preprocess.py", line 259, in <module>
    preprocess(parse_args())
  File "preprocess.py", line 239, in preprocess
    path_table, path_code, word_code_len = build_Huffman(word_count, 40)
  File "preprocess.py", line 171, in build_Huffman
    code[i] = binary[b]
IndexError: list assignment index out of range
