### ISSUE TITLE
icnet训练时没有问题，推断和评估时报维度错误

### ISSUE THREAD

**Issue by freekoy** [PaddlePaddle/models#1557]
```
root@63a11f01a6d1:/work/paddlepaddle/icnet# python train.py --batch_size=4 --use_gpu=True --checkpoint_path="./chkpnt/"
-----------  Configuration Arguments -----------
batch_size: 4
checkpoint_path: ./chkpnt/
init_model: None
random_mirror: True
random_scaling: True
use_gpu: 1
------------------------------------------------
W1225 04:23:18.551097    90 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 9.0
W1225 04:23:18.551133    90 device_context.cc:210] device: 0, cuDNN Version: 7.0.
Iter[100]; train loss: 0.655; sub4_loss: 0.835; sub24_loss: 0.529; sub124_loss: 0.310
kpis	train_cost	0.654622
Saved checkpoint: ./chkpnt//100
kpis	train_duration	189.435656
root@63a11f01a6d1:/work/paddlepaddle/icnet# python eval.py --model_path="./chkpnt/100/" --use_gpu=True
-----------  Configuration Arguments -----------
model_path: ./chkpnt/100/
use_gpu: 1
------------------------------------------------
W1225 04:27:08.380987   130 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 9.0
W1225 04:27:08.381017   130 device_context.cc:210] device: 0, cuDNN Version: 7.0.
loaded model from: ./chkpnt/100/
Traceback (most recent call last):
  File "eval.py", line 96, in <module>
    main()
  File "eval.py", line 92, in main
    eval(args)
  File "eval.py", line 80, in eval
    fetch_list=fetch_vars)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:128 != y_dims[i]:213.
Broadcast dimension mismatch. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:63]
PaddlePaddle Call Stacks: 
0       0x7f48636d7e96p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f48639b0334p paddle::operators::get_mid_dims(paddle::framework::DDim const&, paddle::framework::DDim const&, int, int*, int*, int*) + 916
2       0x7f4864a52d23p void paddle::operators::ElementwiseComputeEx<paddle::operators::AddFunctor<float>, paddle::platform::CUDADeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::AddFunctor<float>, paddle::framework::Tensor*) + 499
3       0x7f4864a534a3p void paddle::operators::default_elementwise_add<paddle::platform::CUDADeviceContext, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*) + 115
4       0x7f4864a53638p paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 344
5       0x7f4864a536b3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7f4864edcafcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
7       0x7f4864ed8c3fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
8       0x7f48637acb63p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
9       0x7f48637ad590p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
10      0x7f48636c3c3bp
11      0x7f48636ff81ep
12            0x4e9ba7p PyCFunction_Call + 119
13            0x53c6d5p PyEval_EvalFrameEx + 23029
14            0x540199p
15            0x53bd92p PyEval_EvalFrameEx + 20658
16            0x53b7e4p PyEval_EvalFrameEx + 19204
17            0x53b7e4p PyEval_EvalFrameEx + 19204
18            0x540199p
19            0x540e4fp PyEval_EvalCode + 31
20            0x60c272p
21            0x60e71ap PyRun_FileExFlags + 154
22            0x60ef0cp PyRun_SimpleFileExFlags + 444
23            0x63fb26p Py_Main + 1110
24            0x4cfeb1p main + 225
25      0x7f48b2fde830p __libc_start_main + 240
26            0x5d6049p _start + 41

```

**Comment by wanghaoshuang** [comment]
当前icnet的实现对输入图片大小的奇偶比较敏感，建议保持预测图片的大小和训练时用的图片大小一致。

**Comment by freekoy** [comment]
预测图片的大小和训练时用的图片大小一致,依然出现同样的问题
这不是用citysapce，用的是别的数据，只修改了NUM_CLASSES这个参数，其它并没有修改
照理说同样的大小，训练模型时可以跑，预测模型时也应该能跑，但报错了
```
root@63a11f01a6d1:/work/paddlepaddle/icnet# python eval.py --model_path="./chkpnt/100/" --use_gpu=True
-----------  Configuration Arguments -----------
model_path: ./chkpnt/100/
use_gpu: 1
------------------------------------------------
W1225 09:18:04.954792    64 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 9.0
W1225 09:18:04.954825    64 device_context.cc:210] device: 0, cuDNN Version: 7.0.
loaded model from: ./chkpnt/100/
Traceback (most recent call last):
  File "eval.py", line 96, in <module>
    main()
  File "eval.py", line 92, in main
    eval(args)
  File "eval.py", line 80, in eval
    fetch_list=fetch_vars)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:90 != y_dims[i]:213.
Broadcast dimension mismatch. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:63]
PaddlePaddle Call Stacks: 
0       0x7fd51bb31e96p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fd51be0a334p paddle::operators::get_mid_dims(paddle::framework::DDim const&, paddle::framework::DDim const&, int, int*, int*, int*) + 916
2       0x7fd51ceacd23p void paddle::operators::ElementwiseComputeEx<paddle::operators::AddFunctor<float>, paddle::platform::CUDADeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::AddFunctor<float>, paddle::framework::Tensor*) + 499
3       0x7fd51cead4a3p void paddle::operators::default_elementwise_add<paddle::platform::CUDADeviceContext, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*) + 115
4       0x7fd51cead638p paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 344
5       0x7fd51cead6b3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, long>, paddle::operators::ElementwiseAddKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
6       0x7fd51d336afcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
7       0x7fd51d332c3fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
8       0x7fd51bc06b63p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
9       0x7fd51bc07590p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
10      0x7fd51bb1dc3bp
11      0x7fd51bb5981ep
12            0x4e9ba7p PyCFunction_Call + 119
13            0x53c6d5p PyEval_EvalFrameEx + 23029
14            0x540199p
15            0x53bd92p PyEval_EvalFrameEx + 20658
16            0x53b7e4p PyEval_EvalFrameEx + 19204
17            0x53b7e4p PyEval_EvalFrameEx + 19204
18            0x540199p
19            0x540e4fp PyEval_EvalCode + 31
20            0x60c272p
21            0x60e71ap PyRun_FileExFlags + 154
22            0x60ef0cp PyRun_SimpleFileExFlags + 444
23            0x63fb26p Py_Main + 1110
24            0x4cfeb1p main + 225
25      0x7fd56bc3a830p __libc_start_main + 240
26            0x5d6049p _start + 41
```

**Comment by geng007** [comment]
你好,请问你解决了吗,我也遇到一样的问题

![default](https://user-images.githubusercontent.com/38428867/50837480-b093a900-1396-11e9-9e8f-e5625dde8ced.png)

**Comment by wanghaoshuang** [comment]
@freekoy @geng007
如果使用的不是cityscape的数据，这一行的shape改成和测试数据一致的大小试试？ 
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/icnet/cityscape.py#L17

**Comment by geng007** [comment]
@wanghaoshuang      
![default](https://user-images.githubusercontent.com/38428867/50872432-b4591700-13fa-11e9-8aef-bb8d67ef1d73.png)
![default](https://user-images.githubusercontent.com/38428867/50873457-2df10500-13fb-11e9-8373-07c3c5a3da61.png)
这里shape改成TRAIN_DATA_SHAPE = (3, 1024, 2048)不能训练,改回TRAIN_DATA_SHAPE = (3, 720, 720)就可以训练

**Comment by geng007** [comment]
@wanghaoshuang     我将cityscape.py中的TEST_DATA_SHAPE 改为(3, 720, 720) , TEST_DATA_SHAPE传入了infer.py的infer(args),但依然报那个bug
![default](https://user-images.githubusercontent.com/38428867/50874202-21ba7700-13fe-11e9-976b-06bf96ffadd9.png)
在读取test的时候,对 ` img = paddle.dataset.image.to_chw(image)[np.newaxis, :]`reshape改如何尝试呢
![default](https://user-images.githubusercontent.com/38428867/50874235-4878ad80-13fe-11e9-8ba9-de68eb6276fd.png)

**Comment by wanghaoshuang** [comment]
https://github.com/PaddlePaddle/models/issues/1614#issuecomment-452941566
