### ISSUE TITLE
gpu版的paddle一直运行不成功，确定cuda安装正确，运行paddle官网安装页面测试程序报paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]

### ISSUE THREAD

**Issue by silverfly1992** [PaddlePaddle/models#1564]
只是将官网安装页面测试程序place = fluid.CPUPlace()改成了place = fluid.CUDAPlace(0)
完整错误代码如下：
Traceback (most recent call last):
  File "/home/silverfly/models/fluid/PaddleCV/deeplabv3+/paddle_test.py", line 73, in <module>
    train(save_dirname)
  File "/home/silverfly/models/fluid/PaddleCV/deeplabv3+/paddle_test.py", line 46, in train
    train_loop(fluid.default_main_program())
  File "/home/silverfly/models/fluid/PaddleCV/deeplabv3+/paddle_test.py", line 30, in train_loop
    exe.run(fluid.default_startup_program())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]
PaddlePaddle Call Stacks: 
0       0x7fd23c8baaf6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fd23d6cd892p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 658
2       0x7fd23c9860f0p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 224
3       0x7fd23c9867f0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
4       0x7fd23c8a895bp
5       0x7fd23c8d8b80p
6       0x55637a13cb94p _PyCFunction_FastCallDict + 340
7       0x55637a1cc7cep
8       0x55637a1eecbap _PyEval_EvalFrameDefault + 762
9       0x55637a1c5a94p
10      0x55637a1c6941p
11      0x55637a1cc755p
12      0x55637a1eecbap _PyEval_EvalFrameDefault + 762
13      0x55637a1c5daep
14      0x55637a1c6941p
15      0x55637a1cc755p
16      0x55637a1eecbap _PyEval_EvalFrameDefault + 762
17      0x55637a1c5daep
18      0x55637a1c6941p
19      0x55637a1cc755p
20      0x55637a1eecbap _PyEval_EvalFrameDefault + 762
21      0x55637a1c7459p PyEval_EvalCodeEx + 809
22      0x55637a1c81ecp PyEval_EvalCode + 28
23      0x55637a2429a4p
24      0x55637a242da1p PyRun_FileExFlags + 161
25      0x55637a242fa4p PyRun_SimpleFileExFlags + 452
26      0x55637a246a9ep Py_Main + 1598
27      0x55637a10e4bep main + 238
28      0x7fd26b493830p __libc_start_main + 240
29      0x55637a1f5773p

**Comment by zzdgit** [comment]
我也是报这个错，我gpu版本和cpu版本都是试过，报一样的错，没看懂是什么引起这个错的
```
Traceback (most recent call last):
  File "train_mixup.py", line 248, in <module>
    main()
  File "train_mixup.py", line 117, in main
    train(model, args, image_shape, steps_one_epoch)
  File "train_mixup.py", line 164, in train
    exe.run(train_startup_prog)
  File "/home/zhouzhengdong/paddle-cpu-1.2/lib/python3.5/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:145]
PaddlePaddle Call Stacks: 
0       0x7fa2cf6eeb16p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fa2d05018e2p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 658
2       0x7fa2cf7ba140p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 224
3       0x7fa2cf7ba840p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
4       0x7fa2cf6dc97bp
5       0x7fa2cf70cba0p
6       0x7fa38a642621p PyCFunction_Call + 305
7       0x7fa38a6c9c37p PyEval_EvalFrameEx + 36887
8       0x7fa38a6cab49p
9       0x7fa38a6c9df5p PyEval_EvalFrameEx + 37333
10      0x7fa38a6cab49p
11      0x7fa38a6c9df5p PyEval_EvalFrameEx + 37333
12      0x7fa38a6ca166p PyEval_EvalFrameEx + 38214
13      0x7fa38a6cab49p
14      0x7fa38a6cacd8p PyEval_EvalCodeEx + 72
15      0x7fa38a6cad1bp PyEval_EvalCode + 59
16      0x7fa38a6f0020p PyRun_FileExFlags + 304
17      0x7fa38a6f1623p PyRun_SimpleFileExFlags + 371
18      0x7fa38a70c8c7p Py_Main + 3239
19            0x400addp main + 349
20      0x7fa3896ae445p __libc_start_main + 245
21            0x4008b9p

```

**Comment by EvanLiu1** [comment]
请问找到原因了吗？ @zzdgit @silverfly1992
