### ISSUE TITLE
CUDA Version 9.0.176 CUDNN7.0.4 paddlepaddle0.15.0  运行train_hinas.py报错

### ISSUE THREAD

**Issue by upwindflys** [PaddlePaddle/models#1565]
learning rate: 0.100000 -> 0.000100, cosine annealing
epoch: 200
batch size: 128
L2 decay: 0.000400
Token is 7,5,8,1,2,10,9,2,2,2,8,8,8,2,9,4,9,11,7,4,3
sep_3x3 	-> shape (-1L, 64L, 32L, 32L)
conv_1x3_3x1 	-> shape (-1L, 64L, 32L, 32L)
maxpool_2x2 	-> shape (-1L, 128L, 16L, 16L)
============
conv_2x2 	-> shape (-1L, 128L, 16L, 16L)
conv_3x3 	-> shape (-1L, 128L, 16L, 16L)
avgpool_2x2 	-> shape (-1L, 128L, 16L, 16L)
maxpool_3x3 	-> shape (-1L, 256L, 8L, 8L)
============
conv_3x3 	-> shape (-1L, 256L, 8L, 8L)
conv_3x3 	-> shape (-1L, 256L, 8L, 8L)
conv_3x3 	-> shape (-1L, 256L, 8L, 8L)
maxpool_2x2 	-> shape (-1L, 256L, 8L, 8L)
maxpool_2x2 	-> shape (-1L, 512L, 4L, 4L)
============
maxpool_2x2 	-> shape (-1L, 512L, 4L, 4L)
conv_3x3 	-> shape (-1L, 512L, 4L, 4L)
maxpool_3x3 	-> shape (-1L, 512L, 4L, 4L)
conv_1x2_2x1 	-> shape (-1L, 512L, 4L, 4L)
maxpool_3x3 	-> shape (-1L, 1024L, 2L, 2L)
============
avgpool_3x3 	-> shape (-1L, 1024L, 2L, 2L)
sep_3x3 	-> shape (-1L, 1024L, 2L, 2L)
conv_1x2_2x1 	-> shape (-1L, 1024L, 2L, 2L)
dilated_2x2 	-> shape (-1L, 1024L, 2L, 2L)
Reading file cifar-10-batches-py/data_batch_1
Reading file cifar-10-batches-py/data_batch_2
Reading file cifar-10-batches-py/data_batch_3
Reading file cifar-10-batches-py/data_batch_4
Reading file cifar-10-batches-py/data_batch_5
Traceback (most recent call last):
  File "train_hinas.py", line 44, in <module>
    app.run(main)
  File "/root/shangyw/.virtualenv/paddle0.15.0/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/root/shangyw/.virtualenv/paddle0.15.0/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train_hinas.py", line 40, in main
    model.run()
  File "/home/shangyw/git_rep/models/fluid/PaddleCV/HiNAS_models/nn_paddle.py", line 139, in run
    feed_order=['pixel', 'label'])
  File "/root/shangyw/.virtualenv/paddle0.15.0/lib/python2.7/site-packages/paddle/fluid/trainer.py", line 405, in train
    feed_order)
  File "/root/shangyw/.virtualenv/paddle0.15.0/lib/python2.7/site-packages/paddle/fluid/trainer.py", line 461, in _train_by_executor
    self._train_by_any_executor(event_handler, exe, num_epochs, reader)
  File "/root/shangyw/.virtualenv/paddle0.15.0/lib/python2.7/site-packages/paddle/fluid/trainer.py", line 490, in _train_by_any_executor
    for var in self.train_func_outputs
  File "/root/shangyw/.virtualenv/paddle0.15.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected dilations[i] == 1, but received dilations[i]:2 != 1:1.
Dilations conv is not supported in this cuDNN version(5.1.10). at [/paddle/paddle/fluid/platform/cudnn_helper.h:293]
PaddlePaddle Call Stacks: 
0       0x7f93a445cd06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f93a507469fp paddle::platform::ScopedConvolutionDescriptor::descriptor(cudnnDataType_t, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&) + 1279
2       0x7f93a50c2f5bp paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 859
3       0x7f93a50c3e03p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7f93a5456b2ep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 526
5       0x7f93a5453bbcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 252
6       0x7f93a4524d19p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
7       0x7f93a4525af0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
8       0x7f93a444294dp

**Comment by chengduoZH** [comment]
这是因为程序在运行时在环境找到的cudnn是5.1.10，而不是7.0。
