### ISSUE TITLE
在使用官方代码训练SSD时，出现AttributeError: module 'paddle.fluid' has no attribute 'program'

### ISSUE THREAD

**Issue by newdimitri** [PaddlePaddle/models#1575]
您好，研发老师，我在macos、Python3.7、paddlepaddle 1.2下运行https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection
中的代码时，出现错误：
```shell
Traceback (most recent call last):
  File "train.py", line 317, in <module>
    val_file_list=val_file_list)
  File "train.py", line 164, in train
    is_train=True)
  File "train.py", line 86, in build_program
    with fluid.program.devices_num_guard(main_prog, startup_prog):
AttributeError: module 'paddle.fluid' has no attribute 'program'
```
运行指令为：
```bash
python3 -u train.py --batch_size=64 --dataset='coco2017' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/' --use_gpu=false
```
出错代码的前后文为：
```Python
def build_program(main_prog, startup_prog, train_params, is_train):
    image_shape = train_params['image_shape']
    class_num = train_params['class_num']
    ap_version = train_params['ap_version']
    outs = []
    with fluid.program.devices_num_guard(main_prog, startup_prog):
        py_reader = fluid.layers.py_reader(
            capacity=64,
            shapes=[[-1] + image_shape, [-1, 4], [-1, 1], [-1, 1]],
            lod_levels=[0, 1, 1, 1],
            dtypes=["float32", "float32", "int32", "int32"],
            use_double_buffer=True)
        with fluid.unique_name.guard():
            image, gt_box, gt_label, difficult = fluid.layers.read_file(py_reader)
            locs, confs, box, box_var = mobile_net(class_num, image, image_shape)
            if is_train:
                with fluid.unique_name.guard("train"):
                    loss = fluid.layers.ssd_loss(locs, confs, gt_box, gt_label, box,
                        box_var)
                    loss = fluid.layers.reduce_sum(loss)
                    optimizer = optimizer_setting(train_params)
                    optimizer.minimize(loss)
                outs = [py_reader, loss]
            else:
                with fluid.unique_name.guard("inference"):
                    nmsed_out = fluid.layers.detection_output(
                        locs, confs, box, box_var, nms_threshold=0.45)
                    map_eval = fluid.evaluator.DetectionMAP(
                        nmsed_out,
                        gt_label,
                        gt_box,
                        difficult,
                        class_num,
                        overlap_threshold=0.5,
                        evaluate_difficult=False,
                        ap_version=ap_version)
                # nmsed_out and image is used to save mode for inference
                outs = [py_reader, map_eval, nmsed_out, image]
    return outs
```

**Comment by jacquesqiao** [comment]
fluid.program.devices_num_guard 改成 fluid.program_guard()

**Comment by newdimitri** [comment]
> fluid.program.devices_num_guard 改成 fluid.program_guard()

可依旧有问题，为何coco的程序要加载pascalvoc数据集？
```python
/usr/local/lib/python3.7/site-packages/paddle/fluid/evaluator.py:71: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
loading annotations into memory...
Traceback (most recent call last):
  File "train.py", line 317, in <module>
    val_file_list=val_file_list)
  File "train.py", line 192, in train
    enable_ce=enable_ce)
  File "/Volumes/macOS专区/models-develop/fluid/PaddleCV/object_detection/reader.py", line 300, in train
    generator = coco(settings, file_list, "train", batch_size, shuffle)
  File "/Volumes/macOS专区/models-develop/fluid/PaddleCV/object_detection/reader.py", line 170, in coco
    coco = COCO(file_list)
  File "/usr/local/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/pascalvoc/annotations/instances_train2017.json'
```

**Comment by jacquesqiao** [comment]
看着是 pycocotools 内部的问题

**Comment by newdimitri** [comment]
> 看着是 pycocotools 内部的问题

那这个问题我们能解决吗？

**Comment by qingqing01** [comment]
请入运行命令是啥？ 有下载COCO数据吗？ 有指定data_dir到COCO路径吗？

注意这个： https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py#L30

请 `python train.py --help` 仔细看下参数。

**Comment by newdimitri** [comment]
> 请入运行命令是啥？ 有下载COCO数据吗？ 有指定data_dir到COCO路径吗？
> 
> 注意这个： https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py#L30
> 
> 请 `python train.py --help` 仔细看下参数。

我按照readme给的代码跑的，确实少了data_dir参数。
这个问题解决了，但现在又有新问题：
```python
➜  object_detection python3 -u train.py --batch_size=64 --dataset='coco2017' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/' --use_gpu=false --data_dir=data/coco
-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 64
data_dir: data/coco
dataset: coco2017
enable_ce: False
epoc_num: 120
image_shape: 3,300,300
learning_rate: 0.001
mean_BGR: 127.5,127.5,127.5
model_save_dir: model
parallel: True
pretrained_model: pretrained/ssd_mobilenet_v1_coco/
use_gpu: 0
------------------------------------------------
/usr/local/lib/python3.7/site-packages/paddle/fluid/evaluator.py:71: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
loading annotations into memory...
Done (t=45.50s)
creating index...
index created!
train on coco2017 with 118287 images
loading annotations into memory...
Done (t=1.30s)
creating index...
index created!
test on coco2017 with 5000 images
*** Aborted at 1545990178 (unix time) try "date -d @1545990178" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x1045761d2) received by PID 3753 (TID 0x70000a371000) stack trace: ***
    @     0x7fff613dff5a _sigtramp
    @        0x1045761d3 _PyType_Lookup
    @        0x1045686a7 _PyObject_GetMethod
    @        0x1045c98a9 _PyEval_EvalFrameDefault
    @        0x10453b88e function_code_fastcall
    @        0x1046102d0 run_at_forkers
    @        0x10461416b os_fork
    @        0x10453bfa3 _PyMethodDef_RawFastCallKeywords
    @        0x10453b4af _PyCFunction_FastCallKeywords
    @        0x1045d210e call_function
    @        0x1045c9305 _PyEval_EvalFrameDefault
    @        0x10453b88e function_code_fastcall
    @        0x1045d217a call_function
    @        0x1045c92ec _PyEval_EvalFrameDefault
    @        0x10453b88e function_code_fastcall
    @        0x10453c241 _PyObject_Call_Prepend
    @        0x104579aaa slot_tp_init
    @        0x104576758 type_call
    @        0x10453b315 _PyObject_FastCallKeywords
    @        0x1045d2173 call_function
    @        0x1045c99a6 _PyEval_EvalFrameDefault
    @        0x10453b88e function_code_fastcall
    @        0x1045d217a call_function
    @        0x1045c9305 _PyEval_EvalFrameDefault
    @        0x10453b88e function_code_fastcall
    @        0x1045d217a call_function
    @        0x1045c9305 _PyEval_EvalFrameDefault
    @        0x10453b88e function_code_fastcall
    @        0x1045d217a call_function
    @        0x1045c92ec _PyEval_EvalFrameDefault
    @        0x1045d2ad1 _PyEval_EvalCodeWithName
    @        0x10453b474 _PyFunction_FastCallKeywords
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 563, in __provider_thread__
    for tensors in func():
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 610, in __tensor_provider__
    for slots in paddle_reader():
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 280, in __reader_creator__
    yield self.feed(item)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 188, in feed
    for each_sample in iterable:
TypeError: 'NoneType' object is not iterable
```

**Comment by qingqing01** [comment]
> 我按照readme给的代码跑的，确实少了data_dir参数。

README默认给的是PascalVOC的训练。

>  TypeError: 'NoneType' object is not iterable

这个问题很大原因是输入数据的路径不对，可以参考 

https://github.com/PaddlePaddle/Paddle/issues/14476#issuecomment-439750551

https://github.com/PaddlePaddle/Paddle/issues/14601#issuecomment-442825495

**Comment by newdimitri** [comment]
> > 我按照readme给的代码跑的，确实少了data_dir参数。
> 
> README默认给的是PascalVOC的训练。
> 
> > TypeError: 'NoneType' object is not iterable
> 
> 这个问题很大原因是输入数据的路径不对，可以参考
> 
> [PaddlePaddle/Paddle#14476 (comment)](https://github.com/PaddlePaddle/Paddle/issues/14476#issuecomment-439750551)
> 
> [PaddlePaddle/Paddle#14601 (comment)](https://github.com/PaddlePaddle/Paddle/issues/14601#issuecomment-442825495)

我写的这个看起来没问题啊：
```
python3 -u train.py --batch_size=64 --dataset='coco2017' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/' --use_gpu=false --data_dir='data/coco/'
```
数据集目录结构是：
```
➜  object_detection tree -L 2 data/
data/
├── coco
│   ├── annotations
│   ├── annotations_trainval2014.zip
│   ├── annotations_trainval2017.zip
│   ├── download.sh
│   ├── train2014.zip
│   ├── train2017.zip
│   ├── val2014
│   ├── val2014.zip
│   ├── val2017
│   └── val2017.zip
└── pascalvoc
    ├── create_list.py
    ├── download.sh
    └── label_list
```
而且，train.py里写的是：
```
add_arg('data_dir',         str,   'data/pascalvoc', "Data directory.")
```
我也和它格式对齐了啊

**Comment by dzhwinter** [comment]
--data_dir='data/coco/' 写成 --data_dir='data/coco'试试。看着像路径问题

**Comment by newdimitri** [comment]
> --data_dir='data/coco/' 写成 --data_dir='data/coco'试试。看着像路径问题

我是先试的data/coco，发现不行才换成data/coco/

**Comment by newdimitri** [comment]
> --data_dir='data/coco/' 写成 --data_dir='data/coco'试试。看着像路径问题
 我是先试的data/coco，发现不行才换成data/coco/

**Comment by qingqing01** [comment]
Fix bug for coco dataset #1582
