### ISSUE TITLE
face_detection 评估报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1761]
paddle 1.3 版本
在训练完后执行评估脚本出现如下错误：
```bash
python -u widerface_eval.py --model_dir=output/159 --pred_dir=pred
```
```bash
-----------  Configuration Arguments -----------
 16000 confs_threshold: 0.15
 16001 data_dir: data/WIDER_val/images/
 16002 file_list: data/wider_face_split/wider_face_val_bbx_gt.txt
 16003 image_path:
 16004 infer: False
 16005 model_dir: output/159
 16006 pred_dir: pred
 16007 use_gpu: True
 16008 use_pyramidbox: True
 16009 ------------------------------------------------
 16010 W0216 09:08:20.877653 38705 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runti
       me API Version: 8.0
 16011 W0216 09:08:20.877743 38705 device_context.cc:271] device: 0, cuDNN Version: 7.0.
 16012 W0216 09:08:20.877751 38705 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.1, but CU
       DNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compat
       ible CUDNN version.
 16013 Traceback (most recent call last):
 16014   File "widerface_eval.py", line 316, in <module>
 16015     infer(args, config)
 16016   File "widerface_eval.py", line 64, in infer
 16017     det4 = multi_scale_test_pyramid(image, max_shrink)
 16018   File "widerface_eval.py", line 230, in multi_scale_test_pyramid
 16019     det_b = detect_face(image, 0.25)
 16020   File "widerface_eval.py", line 127, in detect_face
 16021     det_conf = detection[:, 1]
 16022 IndexError: index 1 is out of bounds for axis 1 with size 1
```

**Comment by qingqing01** [comment]
由于1.3版本`multiclass_nms_op`输出shape改变，`widerface_eval.py` 124行判断需要改下，我会提PR修复下。
