### ISSUE TITLE
deep_attention_matching_net 预测错误

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1773]
[DAM 代码路径](https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleNLP/deep_attention_matching_net)
** 错误日志如下 **
```bash
W0220 12:10:09.423650  3927 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 8.0
W0220 12:10:09.423739  3927 device_context.cc:271] device: 0, cuDNN Version: 7.0.
W0220 12:10:09.423753  3927 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.1, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
start loading data ...
finish loading data ...
test batch num: 2500
begin inference ...
2019-02-20 12:16:49
Traceback (most recent call last):
  File "../test_and_evaluate.py", line 226, in <module>
    test(args)
  File "../test_and_evaluate.py", line 199, in test
    predicts = test_exe.run(feed=feed_list, fetch_list=[logits.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 300, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Cannot find fetched variable.(Perhaps the main_program is not set to ParallelExecutor) at [/paddle/paddle/fluid/framework/details/threaded_ssa_graph_executor.cc:166]
PaddlePaddle Call Stacks: 
0       0x7ff213393455p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7ff2133937d9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7ff214ca81f0p paddle::framework::details::ThreadedSSAGraphExecutor::InsertFetchOps(std::vector<std::string, std::allocator<std::string> > const&, std::vector<paddle::framework::details::FetchOpHandle*, std::allocator<paddle::framework::details::FetchOpHandle*> >*, std::unordered_set<paddle::framework::details::VarHandleBase*, std::hash<paddle::framework::details::VarHandleBase*>, std::equal_to<paddle::framework::details::VarHandleBase*>, std::allocator<paddle::framework::details::VarHandleBase*> >*, std::unordered_map<paddle::framework::details::OpHandleBase*, unsigned long, std::hash<paddle::framework::details::OpHandleBase*>, std::equal_to<paddle::framework::details::OpHandleBase*>, std::allocator<std::pair<paddle::framework::details::OpHandleBase* const, unsigned long> > >*, std::unordered_set<paddle::framework::details::VarHandleBase*, std::hash<paddle::framework::details::VarHandleBase*>, std::equal_to<paddle::framework::details::VarHandleBase*>, std::allocator<paddle::framework::details::VarHandleBase*> >*, paddle::framework::BlockingQueue<paddle::framework::details::VarHandleBase*>*, std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*) + 3104
3       0x7ff214ca8938p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 1768
4       0x7ff214c9fbeap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
5       0x7ff2134d1862p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
6       0x7ff21338408ep
7       0x7ff2133bea0ep
8             0x4c37edp PyEval_EvalFrameEx + 31165
9             0x4b9ab6p PyEval_EvalCodeEx + 774
10            0x4c16e7p PyEval_EvalFrameEx + 22711
11            0x4c136fp PyEval_EvalFrameEx + 21823
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4eb30fp
14            0x4e5422p PyRun_FileExFlags + 130
15            0x4e3cd6p PyRun_SimpleFileExFlags + 390
16            0x493ae2p Py_Main + 1554
17      0x7ff27200d830p __libc_start_main + 240
18            0x4933e9p _start + 41
```

**Comment by ccmeteorljh** [comment]
https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleNLP/deep_attention_matching_net/train_and_evaluate.py#L310
在train的时候fetch_list 加入logits即可解决上述问题
```bash
cost, _ = train_exe.run(feed=feed_list, fetch_list=[loss.name, logits.name])
```
