### ISSUE TITLE
tagspace 模型 样例数据多卡训练一个epoch后报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#1800]
tagspace 模型 直接跑样例数据单机多卡训练一个epoch后报错
paddle1.3 
CUDA9 cudnn7
gpu ：4卡

以下是报错日志：
TRAIN --> pass: 0 batch_num: 950 avg_cost: 0.0400084555149, acc: 1.0
TRAIN --> pass: 0 batch_num: 1000 avg_cost: 0.112019307911, acc: 0.4
epoch:1 num_steps:199 time_cost(s):1.300218
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    train()
  File "train.py", line 123, in train
    train_exe)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 1008, in save_inference_model
    save_persistables(executor, dirname, main_program, params_filename)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 487, in save_persistables
    filename=filename)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 174, in save_vars
    filename=filename)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/io.py", line 210, in save_vars
    executor.run(save_program)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 301, in run
    self.executor.run(fetch_list, fetch_var_name)
TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core.ParallelExecutor, arg0: List[unicode], arg1: unicode) -> None

Invoked with: <paddle.fluid.core.ParallelExecutor object at 0x7f78001ca688>, blocks {
  idx: 0
  parent_idx: -1
  vars {
    name: "cnn"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 50
          dims: 1000

**Comment by guoshengCS** [comment]
可以试下这里 https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleRec/tagspace/train.py#L123 把 `train_exe` 改成 `exe`

**Comment by zhengya01** [comment]
好的，这样改后运行成功了。
