### ISSUE TITLE
neural_machine_translation/rnn_search预测出错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#1853]
neural_machine_translation/rnn_search预测有时会报错(非必现)，报错如下：
Traceback (most recent call last):
  File "infer.py", line 137, in <module>
    infer()
  File "infer.py", line 113, in infer
    return_numpy=False)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks:
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/tensor.py", line 386, in fill_constant
    stop_gradient=True)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/contrib/decoder/beam_search_decoder.py", line 651, in early_stop
    shape=[1], value=0, dtype='bool', force_cpu=True, out=self._cond)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/contrib/decoder/beam_search_decoder.py", line 722, in decode
    self.early_stop()
  File "/ssd1/xiege/model_3.6/models-develop/fluid/PaddleNLP/neural_machine_translation/rnn_search/attention_model.py", line 215, in seq_to_seq_net
    decoder.decode()
  File "infer.py", line 60, in infer
    max_length=args.max_length)
  File "infer.py", line 137, in <module>
    infer()
C++ Callstacks:
op fill_constant does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN] at [/paddle/paddle/fluid/framework/operator.cc:943]

**Comment by tashengjinsheng** [comment]
该问题如何解决

**Comment by liuyf1994** [comment]
我发现这个是版本的问题，代码在paddle1.0版本下运行无错，不过可能产生insufficient memory，调小batch_size即可

**Comment by JiaXiao243** [comment]
<img width="1065" alt="705b13ce14cb7071fa9fe8051d775fb4" src="https://user-images.githubusercontent.com/37854899/54353958-582ba100-4690-11e9-82c8-646aeedc8d98.png">

**Comment by xiegegege** [comment]
在paddle 1.4分支下面最新报错：
Traceback (most recent call last):
  File "infer.py", line 137, in <module>
    infer()
  File "infer.py", line 113, in infer
    return_numpy=False)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/executor.py", line 534, in run
    use_program_cache=use_program_cache)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/executor.py", line 606, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator lstm error.
Python Callstacks:
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1667, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 523, in dynamic_lstm
    'candidate_activation': candidate_activation
  File "/ssd1/xiege/model_1.4/models-release-1.4/PaddleNLP/neural_machine_translation/rnn_search/attention_model.py", line 58, in bi_lstm_encoder
    input=input_forward_proj, size=gate_size * 4, use_peepholes=False)
  File "/ssd1/xiege/model_1.4/models-release-1.4/PaddleNLP/neural_machine_translation/rnn_search/attention_model.py", line 80, in seq_to_seq_net
    input_seq=src_embedding, gate_size=encoder_size)
  File "infer.py", line 60, in infer
    max_length=args.max_length)
  File "infer.py", line 137, in <module>
    infer()
C++ Callstacks:
Enforce failed. Expected b_dims[1] == 4 * frame_size, but received b_dims[1]:3584 != 4 * frame_size:2048.
The second dimension of Input(Bias) should be 4 * 512 if disable peepholes connection at [/ssd1/xiege/paddle_wheel/Paddle/paddle/fluid/operators/lstm_op.cc:84]
