### ISSUE TITLE
图像分类infer 没有batchsize参数

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1872]
```bash
usage: infer.py [-h] [--use_gpu USE_GPU] [--class_dim CLASS_DIM]
                [--image_shape IMAGE_SHAPE] [--with_mem_opt WITH_MEM_OPT]
                [--pretrained_model PRETRAINED_MODEL] [--model MODEL]
                [--model_category MODEL_CATEGORY]
infer.py: error: unrecognized arguments: --batch_size=32
```

**Comment by ccmeteorljh** [comment]
infer的reader数据路径处理不对；
```bash
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/reader/decorator.py", line 281, in handle_worker
    r = mapper(sample)
  File "/ssd1/ljh/models-develop/fluid/PaddleCV/image_classification/reader.py", line 102, in process_image
    img = Image.open(img_path)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/ILSVRC2012/val/ILSVRC2012_val_00000005.jpeg 516'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/reader/decorator.py", line 281, in handle_worker
    r = mapper(sample)
  File "/ssd1/ljh/models-develop/fluid/PaddleCV/image_classification/reader.py", line 102, in process_image
    img = Image.open(img_path)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/ILSVRC2012/val/ILSVRC2012_val_00000007.jpeg 334'
```

**Comment by ccmeteorljh** [comment]
和 #1834  一样
