### ISSUE TITLE
使用cycle_gan训练出来的模型执行预测命令报错

### ISSUE THREAD

**Issue by yuzhengfei** [PaddlePaddle/models#1881]
参考官方链接：http://www.paddlepaddle.org/paddle/ModelBase#%E8%AE%A1%E7%AE%97%E6%9C%BA%E8%A7%86%E8%A7%89%0A%E5%9B%BE%E5%83%8F%E7%94%9F%E6%88%90-CycleGAN
训练平台：ubontu18.04，GPU，paddle1.3.0， 预测平台：win10，cpu，paddle1.3.0
报错信息如下：
PS C:\Users\yuzhengfei\Desktop\models\models\fluid\PaddleCV\gan\cycle_gan> python infer.py --init_model="./output_0/chec
kpoints/1" --input="./data/horse2zebra\inputA\*" --input_style A --output="./output"
-----------  Configuration Arguments -----------
init_model: ./output_0/checkpoints/1
input: ./data/horse2zebra\inputA\*
input_style: A
output: ./output
use_gpu: False
------------------------------------------------
Traceback (most recent call last):
  File "infer.py", line 67, in <module>
    infer(args)
  File "infer.py", line 40, in infer
    fluid.io.load_persistables(exe, args.init_model)
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 701, in load_persistables
    filename=filename)
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 572, in load_vars
    filename=filename)
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 607, in load_vars
    executor.run(load_prog)
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator load error.
Python Callstacks:
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 593, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 572, in load_vars
    filename=filename)
  File "C:\Users\yuzhengfei\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 701, in load_persistables
    filename=filename)
  File "infer.py", line 40, in infer
    fluid.io.load_persistables(exe, args.init_model)
  File "infer.py", line 67, in <module>
    infer(args)
C++ Callstacks:
Cannot open file ./output_0/checkpoints/1\g_A_c1_w for load op at [D:\1.3\paddle\paddle\fluid\operators\load_op.cc:39]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.

![image](https://user-images.githubusercontent.com/31945737/54250449-caac5c00-457e-11e9-98fc-b159be87d632.png)

**Comment by wzzju** [comment]
请问，您在ubuntu上训练是正常的吗？如果是，请使用[save_inference_model](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/io_cn.html#save-inference-model)保存预测模型，然后在windows上使用[load_inference_model](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/io_cn.html#load-inference-model)做inference。

**Comment by kolinwei** [comment]
windows 下 --init_model="./output_0/checkpoints/1" 不对吧，应该是output_0\checkpoints\1

**Comment by yuzhengfei** [comment]
@wzzju 您好，训练是正常的，您的意思是需要将train.py文件下checkpoints(epoch)方法里的save_persistables改成save_inference_model，然后重新训练么？

**Comment by wzzju** [comment]
@yuzhengfei 请问您保存后是为了增量训练还是为了做预测呢？
