### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by dubhex** [PaddlePaddle/models#1897]
能正常训练，但是有时候会报：

> Exception in thread Thread-2 (most likely raised during interpreter shutdown):Exception in thread Thread-5 (most likely raised during interpreter shutdown):Exception in thread Thread-9 (most likely raised during interpreter shutdown):Exception in thread Thread-6 (most likely raised during interpreter shutdown):Exception in thread Thread-10 (most likely raised during interpreter shutdown):Exception in thread Thread-7 (most likely raised during interpreter shutdown):Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
Traceback (most recent call last):
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/opt/python/cp27-cp27mu/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/python/cp27-cp27mu/lib/python2.7/threading.py", line 754, in run
  File "/opt/python/cp27-cp27mu/lib/python2.7/threading.py", line 801, in __bootstrap_innerTraceback (most recent call last):Traceback (most recent call last):Traceback (most recent call last):

请问这是怎么回事，如何解决？

**Comment by frankwhzhang** [comment]
请问运行的是哪个模型，能贴一下具体的代码信息和命令吗
