### ISSUE TITLE
GNN 模型问题汇总

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/models#1935]
1. 数据处理部分
- 执行` python preprocess.py` 问题：
  ```bash
   Namespace(dataset='sample')
   -- Starting @ 2019-03-28 05:49:51.411397s
   Traceback (most recent call last):
   File "preprocess.py", line 32, in <module>
       with open(dataset, "r") as f:
   IOError: [Errno 2] No such file or directory: 'sample_train-item-views.csv'
  ```
2. 模型训练部分
- python3 下报错：
  ```bash
  Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train()
  File "train.py", line 111, in train
    for data in data_reader.reader(batch_size, batch_size * 20, True):
  File "/home/crim/models/fluid/PaddleRec/gnn/reader.py", line 93, in reader
    random.shuffle(self.input)
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/random.py", line 269, in shuffle
    for i in reversed(range(1, len(x))):
  TypeError: object of type 'zip' has no len()
  ```
3. infer部分
- infer模型文件夹建议用try.. except包起来：
  ```bash
  Traceback (most recent call last):
  File "infer.py", line 75, in <module>
    infer(index)
  File "infer.py", line 54, in infer
    model_path, exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1078, in 
   load_inference_model
    raise ValueError("There is no directory named '%s'", dirname)
    ValueError: ("There is no directory named '%s'", './saved_model/epoch_5')
  ```

**Comment by hutuxian** [comment]
PR：https://github.com/PaddlePaddle/models/pull/1940

**Comment by ccmeteorljh** [comment]
> PR：#1940

该pr已修复
