### ISSUE TITLE
machine_reading_comprehension训练种的Evaluating报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/models#2017]
[05:16:04]W:	 [Step 3/3] 2019-04-09 05:16:04,003-INFO: epoch: 1, epoch_time_cost: 176.34
[05:16:04]W:	 [Step 3/3] 2019-04-09 05:16:04,004 - brc - INFO - Evaluating the model after epoch 1
[05:16:04]W:	 [Step 3/3] 2019-04-09 05:16:04,004-INFO: Evaluating the model after epoch 1
[05:16:04]W:	 [Step 3/3] ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
[05:16:04]W:	 [Step 3/3] W0409 05:16:04.008666 23001 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
[05:16:04]W:	 [Step 3/3] I0409 05:16:04.153195 23001 build_strategy.cc:297] SeqOnlyAllReduceOps:0, num_trainers:1
[05:16:04]W:	 [Step 3/3] Traceback (most recent call last):
[05:16:04]W:	 [Step 3/3]   File "run.py", line 648, in <module>
[05:16:04]W:	 [Step 3/3]     train(logger, args)
[05:16:04]W:	 [Step 3/3]   File "run.py", line 465, in train
[05:16:04]W:	 [Step 3/3]     args)
[05:16:04]W:	 [Step 3/3]   File "run.py", line 242, in validation
[05:16:04]W:	 [Step 3/3]     return_numpy=False)
[05:16:04]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 205, in run
[05:16:04]W:	 [Step 3/3]     return_numpy=return_numpy)
[05:16:04]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 544, in run
[05:16:04]W:	 [Step 3/3]     return_numpy=return_numpy)
[05:16:04]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 445, in _run_parallel
[05:16:04]W:	 [Step 3/3]     exe.run(fetch_var_names, fetch_var_name)
[05:16:04]W:	 [Step 3/3] paddle.fluid.core.EnforceNotMet: Cannot find fetched variable(array_to_lod_tensor_2.tmp_0).(Perhaps the main_program is not set to ParallelExecutor) at [/workspace/paddle/fluid/framework/details/threaded_ssa_graph_executor.cc:163]
[05:16:04]W:	 [Step 3/3] PaddlePaddle Call Stacks:

**Comment by kolinwei** [comment]
.run_ce.sh
