### ISSUE TITLE
transformer: 'utf-8' codec can't decode byte 0xed

### ISSUE THREAD

**Issue by Genie-Liu** [PaddlePaddle/models#2020]
I down the preprocessed data WMT16_EN_DE from https://transformer-res.bj.bcebos.com/wmt16_ende_data_bpe_clean.tar.gz.

When I run infer.py, A UnicodeDecodeError come out:

Traceback (most recent call last):
  File "infer.py", line 323, in <module>
    args = parse_args()
  File "infer.py", line 81, in parse_args
    src_dict = reader.DataReader.load_dict(args.src_vocab_fpath)
  File "/Users/xxx/Documents/GitHub/models/PaddleNLP/neural_machine_translation/transformer/reader.py", line 281, in load_dict
    line = line.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

Operating System: macOS 10.14
python version: Python 3.6.5

**Comment by Genie-Liu** [comment]
--src_vocab_fpath data/wmt16_ende_data_bpe_clean/vocab_all.bpe.32000

**Comment by Shajiu** [comment]
你在底下先把这个文本转化为utf-8格式就可以了

**Comment by Genie-Liu** [comment]
> 你在底下先把这个文本转化为utf-8格式就可以了

vi能够直接打开，编码也是utf-8. 但是跑程序的时候就报错了。
