### ISSUE TITLE
bert squad任务运行错误

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2034]
在运行结束保存模型时有个报错
Traceback (most recent call last):
  File "run_squad.py", line 427, in <module>
    train(args)
  File "run_squad.py", line 422, in train
    ], processor)
  File "run_squad.py", line 208, in predict
    args.null_score_diff_threshold, args.verbose)
  File "/ssd1/xiege/LARK_4.10/LARK/BERT/reader/squad.py", line 614, in write_predictions
    result = unique_id_to_result[feature.unique_id]
KeyError: 1000010824
terminate called without an active exception

**Comment by kuke** [comment]
Fixed by https://github.com/PaddlePaddle/LARK/pull/98
