### ISSUE TITLE
human_pose_estimation 评估问题

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2040]
1. human_pose_estimation在paddle1.4分支下运行val和test时会报如下的错误：
Traceback (most recent call last):
  File "val.py", line 233, in <module>
    valid(args)
  File "val.py", line 127, in valid
    loss_name=loss.name)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 282, in _compile
    scope=self._scope)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 253, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: Illegal Pass. Generated graph shouldn't has cycle. at [/ssd1/xiege/paddle_ce/Paddle/paddle/fluid/framework/ir/pass.cc:35]
在paddle 1.3运行正常

2.在cpu下运行val.py会在运行22个epoch后报如下的错误：
Traceback (most recent call last):
  File "val.py", line 233, in <module>
    valid(args)
  File "val.py", line 160, in valid
    feed=feeder.feed(data))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 278, in run
    feed_tensor_dict)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected member_->places_.size() == lod_tensors.size(), but received member_->places_.size():26 != lod_tensors.size():14.
The number of samples of current batch is less than the count of devices, currently, it is not allowed. (26 vs 14) at [/paddle/paddle/fluid/framework/parallel_executor.cc:452]

**Comment by zeyu-liu** [comment]
这个是因为你设置了cpu core有26个，但是最后一个batch的size只有14；目前只支持batch size大于等于core num的情况。建议batch size设置为core num的整数倍，同时保证total images也是core num的整数倍，或者不满足情况时丢掉最后一个batch的数据。

> 2.在cpu下运行val.py会在运行22个epoch后报如下的错误：
Traceback (most recent call last):
File "val.py", line 233, in 
valid(args)
File "val.py", line 160, in valid
feed=feeder.feed(data))
File "/opt/internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 278, in run
feed_tensor_dict)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected member->places_.size() == lod_tensors.size(), but received member_->places_.size():26 != lod_tensors.size():14.
The number of samples of current batch is less than the count of devices, currently, it is not allowed. (26 vs 14) at [/paddle/paddle/fluid/framework/parallel_executor.cc:452]
