### ISSUE TITLE
Cannot use CUDAPlace in CPU only version at 

### ISSUE THREAD

**Issue by honourfuture** [PaddlePaddle/models#2137]
https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/sentiment_classification
在学习中文分词训练时顺序执行到
*sh run.sh eval*
遇到下面报错. 因为刚接触.不太清楚如何排查问题

错误如下:
```
-----------  Configuration Arguments -----------
batch_size: 10
checkpoints: checkpoints
data_dir: ./senta_data/
do_infer: False
do_train: False
do_val: True
epoch: 10
init_checkpoint: ./save_models/step_1800/
lr: 0.002
random_seed: 0
save_steps: 10000
senta_config_path: ./senta_config.json
skip_steps: 10
task_name: senta
use_cuda: True
validation_steps: 1000
verbose: False
vocab_path: ./senta_data//word_dict.txt
------------------------------------------------
Traceback (most recent call last):
  File "run_classifier.py", line 369, in <module>
    main(args)
  File "run_classifier.py", line 164, in main
    place = fluid.CUDAPlace(int(os.getenv('FLAGS_selected_gpus', '0')))
paddle.fluid.core.EnforceNotMet: Cannot use CUDAPlace in CPU only version at [/home/teamcity/work/1ec40e2d88fa641/paddle/fluid/pybind/pybind.cc:806]
PaddlePaddle Call Stacks:
0          0x12186cc97p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 567
1          0x12186ca00p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x1218ceca5p paddle::pybind::pybind11_init_core(pybind11::module&)::$_76::operator()(paddle::platform::CUDAPlace&, int) const + 69
3          0x1218cec5ep void pybind11::detail::argument_loader<paddle::platform::CUDAPlace&, int>::call_impl<void, paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&, 0ul, 1ul, pybind11::detail::void_type>(paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&&&, pybind11::detail::index_sequence<0ul, 1ul>, pybind11::detail::void_type&&) + 14
4          0x1218cec49p std::__1::enable_if<std::is_void<void>::value, pybind11::detail::void_type>::type pybind11::detail::argument_loader<paddle::platform::CUDAPlace&, int>::call<void, pybind11::detail::void_type, paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&>(paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&&&) + 9
5          0x1218cec39p void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core(pybind11::module&)::$_76, void, paddle::platform::CUDAPlace&, int, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core(pybind11::module&)::$_76&&, void (*)(paddle::platform::CUDAPlace&, int), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 153
6          0x12182f707p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3399
7          0x1085ad2adp PyObject_Call + 97
8          0x1085b7b96p instancemethod_call + 163
9          0x1085ad2adp PyObject_Call + 97
10         0x1085f373bp slot_tp_init + 64
11         0x1085f083ap type_call + 182
12         0x1085ad2adp PyObject_Call + 97
13         0x1086250a7p PyEval_EvalFrameEx + 1971
14         0x108624702p PyEval_EvalCodeEx + 1551
15         0x10862aa79p fast_function + 290
16         0x108624b49p PyEval_EvalFrameEx + 597
17         0x108624702p PyEval_EvalCodeEx + 1551
18         0x1086240edp PyEval_EvalCode + 32
19         0x108642e5fp run_mod + 49
20         0x108642f06p PyRun_FileExFlags + 130
21         0x108642a88p PyRun_SimpleFileExFlags + 706
22         0x108653cf6p Py_Main + 3030
23      0x7fffb35e0235p start + 1
24                0x17p

```
本地mac mini 
python 2.7.15
![image](https://user-images.githubusercontent.com/30944597/56626977-8aa8c080-6676-11e9-9359-345cda83d0bd.png)

**Comment by honourfuture** [comment]
因为mac 不支持GPU 训练
故在run.sh中
将use_cuda改为false 就可以
![image](https://user-images.githubusercontent.com/30944597/56628418-428c9c80-667c-11e9-8ada-9935abd28266.png)
