### ISSUE TITLE
icnet utils.py should import fluid

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/models#2153]
03:09:17]W:	 [Step 3/3] W0425 03:09:17.928939 22016 device_context.cc:269] device: 0, cuDNN Version: 7.0.
[03:09:23]W:	 [Step 3/3] Traceback (most recent call last):
[03:09:23]W:	 [Step 3/3]   File "train.py", line 155, in <module>
[03:09:23]W:	 [Step 3/3]     main()
[03:09:23]W:	 [Step 3/3]   File "train.py", line 151, in main
[03:09:23]W:	 [Step 3/3]     train(args)
[03:09:23]W:	 [Step 3/3]   File "train.py", line 122, in train
[03:09:23]W:	 [Step 3/3]     feed=get_feeder_data(data, place),
[03:09:23]W:	 [Step 3/3]   File "/workspace/modelce/tasks/icnet/utils.py", line 82, in get_feeder_data
[03:09:23]W:	 [Step 3/3]     image_t = fluid.LoDTensor()
[03:09:23]W:	 [Step 3/3] NameError: global name 'fluid' is not defined

**Comment by kuke** [comment]
Fixed by https://github.com/PaddlePaddle/models/pull/2174
