### ISSUE TITLE
Yolo V3 :TypeError: yolov3_loss() got an unexpected keyword argument 'gt_box'

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/models#2162]
------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 154, in <module>
    train()
  File "train.py", line 46, in train
    model.build_model()
  File "/home/airobot/models/PaddleCV/yolov3/models/yolov3.py", line 153, in build_model
    name="yolo_loss"+str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'gt_box'

**Comment by heavengate** [comment]
models1.4中YOLOv3代码基于Paddle1.4 版本，请安装Paddle1.4版本
