### ISSUE TITLE
windows下icnet模型无法保存

### ISSUE THREAD

**Issue by Einshein** [PaddlePaddle/models#2195]
对数据进行完预处理之后运行train.py，到了写入保存点这一步会报错显示无法创建保存点
其中checkpoint_path被设定为./chkpnt
```
if iter_id % CHECKPOINT_PERIOD == 0 and args.checkpoint_path is not None: #写保存点
    dir_name = args.checkpoint_path + "/" + str(iter_id)
    fluid.io.save_persistables(exe, dirname=dir_name)
    print("Saved checkpoint: %s" % (dir_name))
```

终端显示
```
-----------  Configuration Arguments -----------
batch_size: 4
checkpoint_path: ./chkpnt
init_model: None
random_mirror: True
random_scaling: True
use_gpu: False
------------------------------------------------
Iter[1]; train loss: 5.780; sub4_loss: 3.435; sub24_loss: 3.792; sub124_loss: 3.714
kpis    train_cost      5.780251
Traceback (most recent call last):
  File "c:\Users\a\.vscode\extensions\ms-python.python-2019.3.6558\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\a\.vscode\extensions\ms-python.python-2019.3.6558\pythonFiles\lib\python\ptvsd\__main__.py", line 391, in main
    run()
  File "c:\Users\a\.vscode\extensions\ms-python.python-2019.3.6558\pythonFiles\lib\python\ptvsd\__main__.py", line 272, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\icnet\train.py", line 155, in <module>
    main()
  File "d:\icnet\train.py", line 151, in main
    train(args)
  File "d:\icnet\train.py", line 144, in train
    fluid.io.save_persistables(exe, dirname=dir_name)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 490, in save_persistables
    filename=filename)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 176, in save_vars
    filename=filename)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\io.py", line 212, in save_vars
    executor.run(save_program)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "C:\Users\a\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
**RuntimeError: ./chkpnt/1 mkdir failed!**
```
请问为什么会出现这种现象呢？

**Comment by xiegegege** [comment]
感觉像是windows下模型保存有问题，这有个类似的issue #2140

**Comment by Einshein** [comment]
> 
> 
> 感觉像是windows下模型保存有问题，这有个类似的issue #2140

看上去是同一个问题，这个问题是不是暂时无法解决了;(

**Comment by junjun315** [comment]
路径分隔符win下不一致，需要在接口里处理或者外部处理(os.path.normpath)
