### ISSUE TITLE
fp16 training does not work

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/models#2213]
I want to run fp16 training on both CPU and GPU but I get the same error message.

`python train.py --model=ResNet18 --batch_size=32 --use_gpu=True --fp16=True`

```
Traceback (most recent call last):
  File "train.py", line 462, in <module>
    main()
  File "train.py", line 458, in main
    train(args)
  File "train.py", line 272, in train
    args=args)
  File "train.py", line 232, in build_program
    params_grads, main_prog, startup_prog, args.scale_loss)
  File "/root/models/PaddleCV/image_classification/utils/fp16_utils.py", line 94, in create_master_params_grads
    reduced_master_grad = fluid.layers.collective._allreduce(master_grad)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/collective.py", line 47, in _allreduce
    "sync_mode": sync_mode})
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1689, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1016, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 905, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "allreduce" has not been registered.
```

My specs:
os: ubuntu16.04
pp: `Release` version built from `develop` branch, enabled GPU support
models: `develop` branch

Disabling fp16: `--fp16=False` results in correct training *both* on GPU and CPU.

Can you please help me resolve this issue (if it's mistake on my end) or fix it?

**Comment by gavin1332** [comment]
switch on
WITH_DISTRIBUTED=ON

**Comment by JiaXiao243** [comment]
请问使用--fp16=True 必须得在编译padle的时候cmake -DWITH_DISTRIBUTED=ON吗？请问这两者有什么关系呢？

**Comment by sfraczek** [comment]
Hi,

I have the same error but neither WITH_DISTRIBUTE=ON (it says WITH_DISTRIBUTE**D** flag doesn't exist) nor  --fp16=False help. Do you have any other ideas what might be wrong?

**[edit]** Nevermind. I've found that I had PYTHONPATH pointing to a different paddlepaddle copy and that caused this error.

**Comment by gavin1332** [comment]
https://github.com/PaddlePaddle/Fleet/tree/develop/benchmark/collective/resnet
There is a ResNet50 FP16 example with Fleet API.

**Comment by gavin1332** [comment]
https://github.com/PaddlePaddle/Fleet/blob/develop/benchmark/collective/resnet/scripts/train_gpu.sh#L38

**Comment by gavin1332** [comment]
We found that the former implementation of FP16 of ResNet has poor performance. And we update it in these months with applying DALI and some kernel fusion. Please refer to the above links.
I will close this issue, and you can reopen it if more discussions are required.
