### ISSUE TITLE
中文机器阅读理解 错误，更改为一条数据预测 ValueError: feed_parallel takes multiple mini-batches. Each mini-batch will be feed on each device. The number of devices and number of mini-batches must be same.

### ISSUE THREAD

**Issue by xingzhoupy** [PaddlePaddle/models#2247]
尝试过更改设备数 dev_count 还是报错设备数据和预测数据需一致的错误，所以 我现在想只预测一条数据，求解，谢谢

**Comment by xingzhoupy** [comment]
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/zx/models/PaddleNLP/reading_comprehension/src/run.py", line 651, in <module>
    predict(logger, args)
  File "/home/zx/models/PaddleNLP/reading_comprehension/src/run.py", line 582, in predict
    feed_order, place, dev_count, vocab, brc_data, logger, args)
  File "/home/zx/models/PaddleNLP/reading_comprehension/src/run.py", line 242, in validation
    feed=list(val_feeder.feed_parallel(feed_data, dev_count)),
  File "/home/zx/models/PaddleNLP/reading_comprehension/venv/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 278, in feed_parallel
    raise ValueError("feed_parallel takes multiple mini-batches. Each "
ValueError: feed_parallel takes multiple mini-batches. Each mini-batch will be feed on each device. The number of devices and number of mini-batches must be same.

**Comment by xyzhou-puck** [comment]
您好，我测试1条数据是可以的，能否提供一下您的数据，使用的paddle版本？
