### ISSUE TITLE
阅读理解执行段落抽取报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2258]
python3.6下阅读理解执行段落抽取时报错，报错如下：
Start paragraph extraction, this may take a few hours
Source dir: ../data/preprocessed
Target dir: ../data/extracted
Processing trainset
Traceback (most recent call last):
  File "paragraph_extraction.py", line 198, in <module>
    print(json.dumps(sample, encoding='utf8', ensure_ascii=False))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'
Traceback (most recent call last):
  File "paragraph_extraction.py", line 198, in <module>
    print(json.dumps(sample, encoding='utf8', ensure_ascii=False))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'
Processing devset
Traceback (most recent call last):
  File "paragraph_extraction.py", line 198, in <module>
    print(json.dumps(sample, encoding='utf8', ensure_ascii=False))
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)

**Comment by xyzhou-puck** [comment]
Hi，

在使用python3的时候，可以将 paragraph_extraction.py 中的最后一行替换为：
print(json.dumps(sample, ensure_ascii=False).encode('utf8'))

**Comment by HongyuLi2018** [comment]
当前的阅读理解系统不支持python3环境，请在python2.7环境下进行测试
