### ISSUE TITLE
deeplab v3+训练报错

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/models#2282]
使用models-1.4的deeplabv3+的代码在本地训练，用的是paddle1.4.1，出现以下错误,
```
I0521 16:51:32.690387 24805 build_strategy.cc:285] SeqOnlyAllReduceOps:0, num_trainers:1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vis/gry/paddle-release/python-gcc482-paddle/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/vis/gry/paddle-release/python-gcc482-paddle/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vis/gry/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 585, in __provider_thread__
    raise ex
IndexError: list index out of range

Traceback (most recent call last):
  File "./train.py", line 216, in <module>
    train_loss, = exe.run(binary, fetch_list=[loss_mean])
  File "/home/vis/gry/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 580, in run
    return_numpy=return_numpy)
  File "/home/vis/gry/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 446, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EOFException: There is no next data. at [/paddle/paddle/fluid/operators/reader/read_op.cc:92]
```

训练的脚本就是官网给出的脚本，想问一下这是什么问题呢？

**Comment by qingqing01** [comment]
> paddle.fluid.core.EOFException: There is no next data.

请先排查，数据的路径、处理是否正确。

**Comment by littletomatodonkey** [comment]
好的，我的cityscape数据格式和paddle训练的数据格式好像不一致，我检查一下

**Comment by littletomatodonkey** [comment]
您好，现在可以正常训练了，但是我现在训练的时候，batch size越大， gpu利用率反而越低（单卡单图利用率26%，单卡二图利用率18%），不知道是否是图像预处理太耗时的原因，想问一下是否方便告知paddle训练的具体日志信息呢？

**Comment by eddieheyutong** [comment]
您好您能留个联系方式嘛，因为刚刚使用deeplabv3+,有些问题想向您请教

**Comment by littletomatodonkey** [comment]
这个邮箱就好




在2019年09月25日 13:49，eddieheyutong 写道：

您好您能留个联系方式嘛，因为刚刚使用deeplabv3+,有些问题想向您请教
