### ISSUE TITLE
DeepASR的decoder怎么才算安装成功呢,已经成了so文件，但是调用会报错

### ISSUE THREAD

**Issue by Maxhyl** [PaddlePaddle/models#2334]
这个是安装后打印的结果
![image](https://user-images.githubusercontent.com/49184062/58604038-8dc24c80-82c5-11e9-8e58-344379077ab0.png)

**Comment by junjun315** [comment]
请问有完整的报错么？

**Comment by Maxhyl** [comment]
@junjun315 直接import的话会报这种错
![image](https://user-images.githubusercontent.com/49184062/58674347-fbcc4980-8381-11e9-8208-8922c97875cd.png)   尝试改用cdll调用之后就报这种
![image](https://user-images.githubusercontent.com/49184062/58674373-1e5e6280-8382-11e9-9142-d14404f5235e.png)

**Comment by Maxhyl** [comment]
@junjun315 直接import的话就报这种错：
Traceback (most recent call last):
  File "../../infer_by_ckpt.py", line 23, in <module>
    from decoder.post_latgen_faster_mapped import Decoder
ImportError: No module named decoder.post_latgen_faster_mapped


该用cdll调用之后就报这个
Traceback (most recent call last):
  File "../../infer_by_ckpt.py", line 287, in <module>
    infer_from_ckpt(args)
  File "../../infer_by_ckpt.py", line 227, in infer_from_ckpt
    decoder = cur.Decoder(args.trans_model, args.vocabulary, args.graphs,
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /work/models/PaddleSpeech/DeepASR/decoder/post_latgen_faster_mapped.so: undefined symbol: Decoder
