### ISSUE TITLE
face_detection Train

### ISSUE THREAD

**Issue by jiayifang1** [PaddlePaddle/models#2358]
gpu单卡运行，11G，能够正常测试预发布模型，但是在运行训练代码过程中：
export CUDA_VISIBLE_DEVICES=0
python -u train.py --batch_size=3 --pretrained_model=vgg_ilsvrc_16_fc_reduced
执行这两个步骤之后，也是正常进入训练的，但是训练过程中是如下这样显示的！出现".......MemoryError"这样的问题，并卡在最后的训练处，不再继续进行，希望能得到大家的帮助！！！

Pass 0, batch 1890, face loss 3.608721, head loss 3.827300, time 0.82712
Pass 0, batch 1900, face loss 6.004067, head loss 6.459546, time 0.81461
Pass 0, batch 1910, face loss 4.193470, head loss 3.602981, time 0.82136
Process Process-7:
Traceback (most recent call last):
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jyf/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 393, in _read_into_queue
    for sample in reader():
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 267, in reader
    image_path)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 116, in preprocess
    settings.min_face_size)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/image_util.py", line 424, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
Pass 0, batch 1920, face loss 4.207895, head loss 3.901461, time 0.81387
Pass 0, batch 1930, face loss 4.981308, head loss 4.160357, time 0.82922
Pass 0, batch 1940, face loss 4.242156, head loss 3.531482, time 0.89638
Pass 0, batch 1950, face loss 5.884556, head loss 3.824725, time 0.81456
Pass 0, batch 1960, face loss 3.307667, head loss 2.812590, time 0.81372
Pass 0, batch 1970, face loss 4.135998, head loss 4.142908, time 0.81373
Pass 0, batch 1980, face loss 3.992738, head loss 2.869507, time 0.81205
Pass 0, batch 1990, face loss 3.689611, head loss 3.299284, time 0.81052
Pass 0, batch 2000, face loss 2.499412, head loss 2.287693, time 0.81455
Pass 0, batch 2010, face loss 1.459440, head loss 1.841028, time 0.81367
Pass 0, batch 2020, face loss 2.988102, head loss 2.815126, time 0.83127
Pass 0, batch 2030, face loss 4.024381, head loss 3.740697, time 0.82407
Pass 0, batch 2040, face loss 3.497251, head loss 3.646049, time 0.80784
Pass 0, batch 2050, face loss 3.888634, head loss 3.634361, time 0.88443
Pass 0, batch 2060, face loss 4.123483, head loss 3.784822, time 0.81228
Pass 0, batch 2070, face loss 3.865510, head loss 3.366984, time 0.80212
Process Process-3:
Traceback (most recent call last):
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jyf/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 393, in _read_into_queue
    for sample in reader():
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 267, in reader
    image_path)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 116, in preprocess
    settings.min_face_size)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/image_util.py", line 424, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
Pass 0, batch 2080, face loss 4.575073, head loss 3.918978, time 1.04506
Pass 0, batch 2090, face loss 4.212999, head loss 3.976611, time 0.81284
Pass 0, batch 2100, face loss 4.210123, head loss 3.808105, time 0.80688
Pass 0, batch 2110, face loss 3.437980, head loss 2.679230, time 0.81080
Pass 0, batch 2120, face loss 2.723385, head loss 2.337259, time 0.80899
Pass 0, batch 2130, face loss 5.665165, head loss 5.790230, time 0.81662
Pass 0, batch 2140, face loss 5.166775, head loss 5.815830, time 0.81377
Pass 0, batch 2150, face loss 4.529456, head loss 4.198637, time 0.81539
Pass 0, batch 2160, face loss 1.446540, head loss 1.389654, time 0.85053
Pass 0, batch 2170, face loss 1.424659, head loss 1.341642, time 0.81604

**Comment by ceci3** [comment]
您好，看报错像是内存错误，是出现完MemoryError之后再继续训练吗？

**Comment by jiayifang1** [comment]
是的，但是会卡在训练中途不再继续，应该是内存的问题，有没有什么方法解决一下，硬件条件有限，最好能有优化方法。

**Comment by jiayifang1** [comment]
是的，但是会卡在训练中途不再继续，应该是内存的问题，有没有什么方法解决一下，硬件条件有限，最好能有优化方法。

> 您好，看报错像是内存错误，是出现完MemoryError之后再继续训练吗？

是的，但是会卡在训练中途不再继续，应该是内存的问题，有没有什么方法解决一下，硬件条件有限，最好能有优化方法。

**Comment by qingqing01** [comment]
@jiayifang1 你的机器内存多大？

**Comment by jiayifang1** [comment]
单卡，11G

**Comment by qingqing01** [comment]
@JiabinYang 我指的是CPU的内存哈

**Comment by jiayifang1** [comment]
1080ti  gpu11G，CPU哪个啊4G好像🤔 不是gpu训练嘛，和cpu也有关系鸭

**Comment by qingqing01** [comment]
上面错误 MemoryError，搜索可能的一个原因是CPU的内存不够。  数据处理部分实在CPU上。

**Comment by qingqing01** [comment]
@jiayifang1 您可以将 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/face_detection/train.py#L119 这里的 num_workers 改成1试下， 也可减少batch size试下。

**Comment by jiayifang1** [comment]
好的，我再去试试，之前改了batch size会出现nan情况，我改一下num-workers试一下再，非常感谢您的回复，后续有问题希望继续沟通一下

**Comment by jiayifang1** [comment]
> @jiayifang1 您可以将 https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/face_detection/train.py#L119 这里的 num_workers 改成1试下， 也可减少batch size试下。

嗨，你好，我是了一下你说的方法，还是不行，还是会停止

Pass 0, batch 590, face loss 2.611715, head loss 2.550977, time 0.86776
Pass 0, batch 600, face loss 2.334980, head loss 2.364299, time 0.85015
Pass 0, batch 610, face loss 3.500614, head loss 3.484950, time 0.92723
Pass 0, batch 620, face loss 2.706324, head loss 2.910119, time 0.93420
Pass 0, batch 630, face loss 4.688107, head loss 3.863219, time 0.86212
Process Process-1:
Traceback (most recent call last):
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jyf/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 393, in _read_into_queue
    for sample in reader():
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 267, in reader
    image_path)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 116, in preprocess
    settings.min_face_size)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/image_util.py", line 424, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
Pass 0, batch 640, face loss 3.780930, head loss 3.913529, time 0.91207
Pass 0, batch 650, face loss 3.813128, head loss 3.337091, time 1.01651
Process Process-6:
Traceback (most recent call last):
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jyf/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 393, in _read_into_queue
    for sample in reader():
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 267, in reader
    image_path)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 116, in preprocess
    settings.min_face_size)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/image_util.py", line 424, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
Pass 0, batch 660, face loss 3.383338, head loss 3.590440, time 0.86682
Pass 0, batch 670, face loss 3.641536, head loss 3.607170, time 0.90993
Pass 0, batch 680, face loss 4.343625, head loss 4.161895, time 0.87779
Pass 0, batch 690, face loss 3.943311, head loss 3.571257, time 1.05826
Pass 0, batch 700, face loss 4.255438, head loss 4.210448, time 1.08714
Pass 0, batch 710, face loss 4.193367, head loss 4.017983, time 0.89807
Pass 0, batch 720, face loss 3.884374, head loss 4.156770, time 1.02944
Pass 0, batch 730, face loss 4.433530, head loss 5.099911, time 1.19215
Pass 0, batch 740, face loss 3.718375, head loss 3.832477, time 0.94571
Pass 0, batch 750, face loss 4.145471, head loss 4.095515, time 1.08942
Pass 0, batch 760, face loss 4.030917, head loss 3.466190, time 1.16697
Pass 0, batch 770, face loss 3.006891, head loss 2.933145, time 1.14734
Pass 0, batch 780, face loss 3.903650, head loss 3.921134, time 0.90632
Pass 0, batch 790, face loss 3.405318, head loss 3.503507, time 0.87839
Pass 0, batch 800, face loss 4.022890, head loss 3.354231, time 0.89619
Pass 0, batch 810, face loss 5.421267, head loss 4.168753, time 0.91207
Pass 0, batch 820, face loss 3.876032, head loss 3.891509, time 1.00830
Pass 0, batch 830, face loss 3.252797, head loss 2.505850, time 1.37027
Pass 0, batch 840, face loss 2.678683, head loss 1.903676, time 0.89822
Pass 0, batch 850, face loss 3.374603, head loss 2.998075, time 0.89205
Pass 0, batch 860, face loss 2.764775, head loss 2.306991, time 1.00298
Pass 0, batch 870, face loss 4.194667, head loss 4.075042, time 0.87089
Process Process-5:
Traceback (most recent call last):
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jyf/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jyf/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 393, in _read_into_queue
    for sample in reader():
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 267, in reader
    image_path)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/reader.py", line 116, in preprocess
    settings.min_face_size)
  File "/home/jyf/JYF/Pyramidbox/models/PaddleCV/face_detection/image_util.py", line 424, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
Pass 0, batch 880, face loss 3.586615, head loss 3.338580, time 1.00987
Pass 0, batch 890, face loss 4.833227, head loss 4.374566, time 1.02343
Pass 0, batch 900, face loss 3.000325, head loss 2.972529, time 0.90302
Pass 0, batch 910, face loss 4.183233, head loss 3.463032, time 0.89874
Pass 0, batch 920, face loss 3.811677, head loss 3.714861, time 1.28314
Pass 0, batch 930, face loss 3.741017, head loss 3.515755, time 0.89127

请问跟Process有没有关系呢
