### ISSUE TITLE
window10运行object_detection报错

### ISSUE THREAD

**Issue by yanggb** [PaddlePaddle/models#2422]
环境：win10+python3.7
object_detection和face_detection都存在这个错误。哪位朋友帮帮忙，无论是使用推荐数据还是自己的图片数据都报错

参数配置：
add_arg('learning_rate',    float, 0.001,     "Learning rate.")
add_arg('batch_size',       int,   64,        "Minibatch size of all devices.")
add_arg('epoc_num',         int,   120,       "Epoch number.")
add_arg('use_gpu',          bool,  False,      "Whether use GPU.")
add_arg('parallel',         bool,  False,      "Whether train in parallel on multi-devices.")
add_arg('dataset',          str,   'pascalvoc', "dataset can be coco2014, coco2017, and pascalvoc.")
add_arg('model_save_dir',   str,   'model',     "The path to save model.")
add_arg('pretrained_model', str,   'pretrained/ssd_mobilenet_v1_coco/', "The init model path.")
add_arg('ap_version',       str,   '11point',           "mAP version can be integral or 11point.")
add_arg('image_shape',      str,   '3,300,300',         "Input image shape.")
add_arg('mean_BGR',         str,   '127.5,127.5,127.5', "Mean value for B,G,R channel which will be subtracted.")
add_arg('data_dir',         str,   'data/pascalvoc', "Data directory.")
add_arg('enable_ce',        bool,  True, "Whether use CE to evaluate the model.")

报错log:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "G:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "G:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Python36\lib\site-packages\paddle\fluid\layers\io.py", line 585, in __provider_thread__
    raise ex
  File "G:\Python36\lib\site-packages\paddle\fluid\layers\io.py", line 567, in __provider_thread__
    for tensors in func():
  File "G:\Python36\lib\site-packages\paddle\fluid\layers\io.py", line 617, in __tensor_provider__
    for slots in paddle_reader():
  File "G:\Python36\lib\site-packages\paddle\fluid\data_feeder.py", line 326, in __reader_creator__
    for item in reader():
  File "G:\Python36\lib\site-packages\paddle\reader\decorator.py", line 404, in queue_reader
    p.start()
  File "G:\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "G:\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "G:\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "G:\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "G:\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'multiprocess_reader.<locals>._read_into_queue'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "G:\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by kolinwei** [comment]
请问data_dir配置的是啥？

**Comment by JiaXiao243** [comment]
windows下object_detection运行报错，同一个问题 [#2208](https://github.com/PaddlePaddle/models/issues/2208) ，[#2211](https://github.com/PaddlePaddle/models/issues/2211)
目前还未解决。

**Comment by yanggb** [comment]
> 请问data_dir配置的是啥？

add_arg('data_dir', str, 'data/pascalvoc', "Data directory.")
但是我昨天在ubuntu上训练成功了，代码是copy过去的，不知道是不是windows的bug

**Comment by wopeizl** [comment]
多进程reader目前在win上还没有支持

**Comment by yanggb** [comment]
> 多进程reader目前在win上还没有支持

ok  多谢
