### ISSUE TITLE
ctr训练报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2465]
在paddle1.5分支下，ctr训练有如下报错：
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train()
  File "train.py", line 232, in train
    train_loop(args, main_program, py_reader, loss, auc_var, batch_auc_var, 1, 0)
  File "train.py", line 155, in train_loop
    exec_strategy=exec_strategy)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 175, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 366, in _compile
    scope=self._scope)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 337, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: If you set build_strategy.reduce with 'Reduce',the number of places must be greater than 1. at [/ssd1/xiege/paddle_ce/Paddle/paddle/fluid/framework/parallel_executor.cc:325]

**Comment by jacquesqiao** [comment]
请 @chengduoZH 看一下

**Comment by kolinwei** [comment]
该问题在不设CPU_NUM环境变量时会发生

**Comment by xiegegege** [comment]
现在的报错变成了：
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train()
  File "train.py", line 232, in train
    train_loop(args, main_program, py_reader, loss, auc_var, batch_auc_var, 1, 0)
  File "train.py", line 155, in train_loop
    exec_strategy=exec_strategy)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 175, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 366, in _compile
    scope=self._scope)
  File "/opt/_internal/cpython-3.6.0/lib/python3.6/site-packages/paddle/fluid/compiler.py", line 337, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected dev_id != -1, but received dev_id:-1 == -1:-1.
dev_id should not be -1.[adam, SparseFeatFactors, SparseFeatFactors@GRAD] at [/ssd1/xiege/paddle_ce/Paddle/paddle/fluid/framework/ir/multi_devices_graph_pass/multi_devices_graph_pass.cc:634]
