### ISSUE TITLE
transformer train windows下报错 paddle1.4.1 GPU版

### ISSUE THREAD

**Issue by wang001** [PaddlePaddle/models#2595]
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
Traceback (most recent call last):
  File "E:/tmp/autoMaster/PaddleNLP/neural_machine_translation/transformer/train.py", line 774, in <module>
    train(args)
  File "E:/tmp/autoMaster/PaddleNLP/neural_machine_translation/transformer/train.py", line 694, in train
    token_num, predict, pyreader)
  File "E:/tmp/autoMaster/PaddleNLP/neural_machine_translation/transformer/train.py", line 513, in train_loop
    trainer_id=nccl2_trainer_id)
  File "E:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\parallel_executor.py", line 134, in __init__
    self._compiled_program._compile(place=self._place, scope=self._scope)
  File "E:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\compiler.py", line 307, in _compile
    scope=self._scope)
  File "E:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\compiler.py", line 278, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core.EnforceNotMet: Not compiled with CUDA at [D:\1.4.1\paddle\paddle\fluid\framework\parallel_executor.cc:275]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
W0628 15:22:38.912901  8748 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 8.0
W0628 15:22:38.916891  8748 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0628 15:22:46.824911  8748 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!

**Comment by JiaXiao243** [comment]
paddle==1.4.1，在windows上不支持parallel_executor，故无法跑该模型。从paddle==1.5开始，在window上支持parallel_executor。

**Comment by wang001** [comment]
可是。。。。windows没有1.5.0

**Comment by JiaXiao243** [comment]
大概1~2天后paddle1.5发版

**Comment by wang001** [comment]
谢谢！
