### ISSUE TITLE
attention ocr infer报错

### ISSUE THREAD

**Issue by intgogo** [PaddlePaddle/models#2631]
```
-----------  Configuration Arguments -----------
batch_size: 1
dict: None
input_images_dir: None
input_images_list: None
iterations: 0
model: attention
model_path: models/ocr_attention_params
profile: False
skip_batch_num: 0
use_gpu: True
------------------------------------------------
W0701 11:41:15.507436 17863 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 9.0
W0701 11:41:15.511775 17863 device_context.cc:267] device: 0, cuDNN Version: 7.4.
Init model from: models/ocr_attention_params.
Please input the path of image: test/1.png
Traceback (most recent call last):
  File "/root/lilw/pycharm/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/root/lilw/pycharm/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/lilw/pycharm/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/lilw/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/infer.py", line 159, in <module>
    main()
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/infer.py", line 155, in main
    inference(args)
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/infer.py", line 97, in inference
    return_numpy=False)
  File "/root/lilw/anaconda3/envs/chineseocr/lib/python3.6/site-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/root/lilw/anaconda3/envs/chineseocr/lib/python3.6/site-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator im2sequence error.
Python Callstacks: 
  File "/root/lilw/anaconda3/envs/chineseocr/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/lilw/anaconda3/envs/chineseocr/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/root/lilw/anaconda3/envs/chineseocr/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6164, in im2sequence
    type='im2sequence', inputs=inputs, outputs={'Out': out}, attrs=attrs)
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/attention_model.py", line 71, in encoder_net
    filter_size=[conv_features.shape[2], 1])
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/attention_model.py", line 237, in attention_infer
    images, is_test=True, use_cudnn=use_cudnn)
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/infer.py", line 48, in inference
    ids = infer(images, num_classes, use_cudnn=True if args.use_gpu else False)
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/infer.py", line 155, in main
    inference(args)
  File "/root/lilw/Paddle/models/PaddleCV/ocr_recognition/infer.py", line 159, in <module>
    main()
  File "/root/lilw/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/lilw/pycharm/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/lilw/pycharm/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/lilw/pycharm/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
C++ Callstacks: 
Enforce failed. Expected numel() >= 0, but received numel():-31488 < 0:0.
When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::Resize has been called first. at [/root/lilw/Paddle/paddle/fluid/framework/tensor.cc:43]
```

**Comment by intgogo** [comment]
最后发现是图片只能用48像素高的
