### ISSUE TITLE
PaddleDetection中的cascade模型CPU下训练报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/models#2654]
使用paddle 1.5分支，在CPU下运行PaddleDetection中的cascade模型，有如下报错：
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 159, in main
    outs = exe.run(train_compile_program, fetch_list=train_values)
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 665, in run
    return_numpy=return_numpy)
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 527, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator distribute_fpn_proposals error.
Python Callstacks:
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1764, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/layers/detection.py", line 2837, in distribute_fpn_proposals
    'refer_scale': refer_scale
  File "/ssd1/xiege/model_7.1/models/PaddleCV/PaddleDetection/ppdet/modeling/roi_extractors/roi_extractor.py", line 76, in __call__
    rois, k_min, k_max, self.canconical_level, self.canonical_size)
  File "/ssd1/xiege/model_7.1/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 119, in build
    roi_feat = self.roi_extractor(body_feats, proposals, spatial_scale)
  File "/ssd1/xiege/model_7.1/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 160, in train
    return self.build(feed_vars, 'train')
  File "tools/train.py", line 95, in main
    train_fetches = model.train(feed_vars)
  File "tools/train.py", line 204, in <module>
    main()
C++ Callstacks:
Enforce failed. Expected begin_idx < end_idx, but received begin_idx:0 >= end_idx:0.
The start row index must be lesser than the end row index. at [/ssd1/xiege/paddle_wheel/Paddle_2.7/Paddle/paddle/fluid/framework/tensor.cc:78]

**Comment by qingqing01** [comment]
@sunxiaolong Please look at this question.

**Comment by xiegegege** [comment]
最新的报错：
Invoke operator roi_align_grad error.
Python Callstacks:
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1773, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-2.7.11-ucs2/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 7453, in roi_align
    "sampling_ratio": sampling_ratio
  File "/ssd1/xiege/model_7.23/models/PaddleCV/PaddleDetection/ppdet/modeling/roi_extractors/roi_extractor.py", line 91, in __call__
    sampling_ratio=self.sampling_ratio)
  File "/ssd1/xiege/model_7.23/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 127, in build
    roi_feat = self.roi_extractor(body_feats, proposals, spatial_scale)
  File "/ssd1/xiege/model_7.23/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 168, in train
    return self.build(feed_vars, 'train')
  File "tools/train.py", line 99, in main
    train_fetches = model.train(feed_vars)
  File "tools/train.py", line 211, in <module>
    main()
C++ Callstacks:
holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/ssd1/xiege/paddle_wheel/Paddle/Paddle/paddle/fluid/framework/tensor.cc:23]

**Comment by suyali** [comment]
遇到了同样的问题，怎么解决的呀？@xiegegege

**Comment by xiegegege** [comment]
这个他们已经在修了，应该快merge了~
