### ISSUE TITLE
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected end > start, but received end:1917 <= start:1917.

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2682]
用ssd训练的一个二分类的检测网络，用save_persistables保存模型，使用load_persistable加载报错，但是把该模型用save_inference_model转成inference模型后可以正常使用.
```
Traceback (most recent call last):
  File "/Users/***/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "/Users/***/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__main__.py", line 391, in main
    run()
  File "/Users/gongyanhe/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/__main__.py", line 272, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/***/infer.py", line 95, in <module>
    main(args)
  File "/Users/***/infer.py", line 88, in main
    fetch_list=nmsed_out,return_numpy=False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 744, in _run
    fetch_var_name=fetch_var_name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 429, in _add_feed_fetch_ops
    for i, var in enumerate(fetch_list):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 884, in __getitem__
    'decrease_axis': decrease_axis
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1141, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected end > start, but received end:1917 <= start:1917.
end should greater than start at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/slice_op.cc:57]
PaddlePaddle Call Stacks: 
0          0x11fa563b4p void paddle::platform::EnforceNotMet::Init<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, int) + 628
1          0x11fa560e0p paddle::platform::EnforceNotMet::EnforceNotMet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int) + 80
2          0x11fcc94a4p paddle::operators::SliceOp::InferShape(paddle::framework::InferShapeContext*) const + 2324
3          0x11fbb3b88p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1464
4          0x11fb0d536p void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const + 198
5          0x11fa35a08p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
6          0x10075dd09p PyCFunction_Call + 281
7          0x1007ebf25p PyEval_EvalFrameEx + 38741
8          0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
9          0x1007ec9a7p PyEval_EvalCodeEx + 71
10         0x10073884ap function_call + 186
11         0x100705783p PyObject_Call + 99
12         0x10072086cp method_call + 140
13         0x100705783p PyObject_Call + 99
14         0x10077ba81p slot_tp_init + 81
15         0x1007723c4p type_call + 212
16         0x100705783p PyObject_Call + 99
17         0x1007e7fb4p PyEval_EvalFrameEx + 22500
18         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
19         0x1007ea28ap PyEval_EvalFrameEx + 31418
20         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
21         0x1007ec9a7p PyEval_EvalCodeEx + 71
22         0x10073884ap function_call + 186
23         0x100705783p PyObject_Call + 99
24         0x10072086cp method_call + 140
25         0x100705783p PyObject_Call + 99
26         0x100777459p slot_sq_item + 153
27         0x1007399cep iter_iternext + 62
28         0x100727d0dp enum_next + 45
29         0x1007e5454p PyEval_EvalFrameEx + 11396
30         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
31         0x1007ea28ap PyEval_EvalFrameEx + 31418
32         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
33         0x1007ea28ap PyEval_EvalFrameEx + 31418
34         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
35         0x1007ea28ap PyEval_EvalFrameEx + 31418
36         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
37         0x1007ea28ap PyEval_EvalFrameEx + 31418
38         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
39         0x1007eca01p PyEval_EvalCode + 81
40         0x1007dfc2fp builtin_exec + 623
41         0x10075dcd9p PyCFunction_Call + 233
42         0x1007ebe34p PyEval_EvalFrameEx + 38500
43         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
44         0x1007ea28ap PyEval_EvalFrameEx + 31418
45         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
46         0x1007ea28ap PyEval_EvalFrameEx + 31418
47         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
48         0x1007ea28ap PyEval_EvalFrameEx + 31418
49         0x1007ea424p PyEval_EvalFrameEx + 31828
50         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
51         0x1007ea28ap PyEval_EvalFrameEx + 31418
52         0x1007ec8a0p _PyEval_EvalCodeWithName + 2400
53         0x1007eca01p PyEval_EvalCode + 81
54         0x10081ab7ep PyRun_FileExFlags + 206
55         0x10081ae2fp PyRun_SimpleFileExFlags + 463
56         0x100833d12p Py_Main + 3554
57         0x100000e32p
58         0x100000c84p
```

**Comment by heavengate** [comment]
报错原因为Slice op传入的slice范围[start, end] start=end，请确认一下调用fluid.layers.slice的相关代码

**Comment by imistyrain** [comment]
那为啥infer的模型没问题呢？不记得代码里写slice_op，用的就是mobilenet-ssd的模型

**Comment by heavengate** [comment]
麻烦贴一下主要代码，确认一下paddle等版本信息

**Comment by imistyrain** [comment]
paddle版本1.5

**Comment by imistyrain** [comment]
已找到原因，可正常加载，具体为fetch的时候一定要加[]
即
```
nmsed_out_v ,= exe.run(test_prog,
                      feed={image.name:data},
                      fetch_list=[nmsed_out],return_numpy=False)
```
而不是
```
nmsed_out_v ,= exe.run(test_prog,
                      feed={image.name:data},
                      fetch_list=nmsed_out,return_numpy=False)
```
