### ISSUE TITLE
'DetectionMAP' object has no attribute 'name'

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2689]
在使用[PaddleSlim](https://github.com/PaddlePaddle/models/blob/develop/PaddleSlim/compress.py)量化检测模型时，需要拿到test_program的输出，但是提示'DetectionMAP' object has no attribute 'name'.
```
val_fetch_list = [('map', map_eval.name)]
train_fetch_list = [('loss', loss.name)]
```

**Comment by wanghaoshuang** [comment]
[DetectionMAP](http://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/metrics_cn.html#detectionmap)本身不是Variable类型，所以没有name属性。DetectionMAP相当于一个累计器，可以通过
```
cur_map, accum_map = map_evaluator.get_map_var()
```
获得累计的variables, 然后将cur_map交给fetch list

```
val_fetch_list = [('map', cur_map.name)]
```

**Comment by imistyrain** [comment]
嗯，这个问题解决了，又出新问题了:
```
Traceback (most recent call last):
  File "/home/ar/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 535, in run
    self._train_one_epoch(context)
  File "/home/ar/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 472, in _train_one_epoch
    data=data)
  File "/home/ar/.jumbo/lib/python2.7/site-packages/paddle/fluid/contrib/slim/graph/executor.py", line 50, in run
    feed = feeder.feed(data)
  File "/home/ar/.jumbo/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 282, in feed
    "len(feed_list) (%s)") % (len(each_sample), len(converter))
AssertionError: The number of fields in data (4) does not match len(feed_list) (0)
2019-07-03 15:24:39,706-ERROR: None
```

代码:
```
    com_pass = Compressor(
        place,
        fluid.global_scope(),
        fluid.default_main_program(),
        train_reader=train_reader,
        train_feed_list=None,
        train_fetch_list=train_fetch_list,
        eval_program=test_prog,
        eval_reader=test_reader,
        eval_feed_list=None,
        eval_fetch_list=val_fetch_list,
        train_optimizer=None)

    com_pass.config(args.compress_config)
    com_pass.run()
```

**Comment by imistyrain** [comment]
train_reader=train_reader应改为train_py_reader, eval_reader=test_reader,应改为test_py_reader.

**Comment by zzchust** [comment]
@imistyrain  同学你好，使用paddleslim进行量化检测模型成功了吗？ 能加微信讨论一下吗？微信：zaizhongche
