### ISSUE TITLE
Errors in image_classification/eval.py and image_classification/infer.py

### ISSUE THREAD

**Issue by lixiangchun** [PaddlePaddle/models#2803]
When I run the following command
```python
python eval.py --pretrained_model ResNet50_vd_pretrained --model ResNet50_vd
```

Error occurs:
```
-------------  Configuration Arguments -------------
               batch_size : 256
                class_dim : 1000
              image_shape : 3,224,224
                    model : ResNet50_vd
         pretrained_model : ResNet50_vd_pretrained
        resize_short_size : 256
                  use_gpu : True
             with_mem_opt : True
----------------------------------------------------
memory_optimize is deprecated. Use CompiledProgram and Executor
W0714 13:31:15.868573 89099 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 9.0
W0714 13:31:15.871407 89099 device_context.cc:267] device: 0, cuDNN Version: 7.3.
Traceback (most recent call last):
  File "eval.py", line 143, in <module>
    main()
  File "eval.py", line 139, in main
    eval(args)
  File "eval.py", line 100, in eval
    val_reader = paddle.batch(reader.val(settings=args), batch_size=args.batch_size)
TypeError: val() missing 1 required positional argument: 'batch_size'
```

When `batch_size` was added on line 100:
```python
val_reader = paddle.batch(reader.val(settings=args, batch_size=args.batch_size), batch_size=args.batch_size)
```
Other error occurred:
```
-------------  Configuration Arguments -------------
               batch_size : 256
                class_dim : 1000
              image_shape : 3,224,224
                    model : ResNet50_vd
         pretrained_model : ResNet50_vd_pretrained
        resize_short_size : 256
                  use_gpu : True
             with_mem_opt : True
----------------------------------------------------
memory_optimize is deprecated. Use CompiledProgram and Executor
W0714 13:34:55.088060 89222 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 9.0
W0714 13:34:55.091224 89222 device_context.cc:267] device: 0, cuDNN Version: 7.3.
Traceback (most recent call last):
  File "eval.py", line 143, in <module>
    main()
  File "eval.py", line 139, in main
    eval(args)
  File "eval.py", line 109, in eval
    feed=feeder.feed(data))
  File "/media/ssd1/software/install/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 282, in feed
    "len(feed_list) (%s)") % (len(each_sample), len(converter))
AssertionError: The number of fields in data (256) does not match len(feed_list) (2)
```

Error also found for `infer.py`
```python
python infer.py --pretrained_model ResNet50_vd_pretrained --model ResNet50_vd
```
```
Traceback (most recent call last):
  File "infer.py", line 117, in <module>
    main()
  File "infer.py", line 113, in main
    infer(args)
  File "infer.py", line 94, in infer
    test_reader = paddle.batch(reader.test(settings=args), batch_size=test_batch_size)
TypeError: test() missing 1 required positional argument: 'batch_size'
```

When added `batch_size` on Line 94:
```python
test_reader = paddle.batch(reader.test(settings=args, batch_size=test_batch_size), batch_size=test_batch_size)
```
New error:
```
memory_optimize is deprecated. Use CompiledProgram and Executor
W0714 14:08:49.436848 89879 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 9.0
W0714 14:08:49.439999 89879 device_context.cc:267] device: 0, cuDNN Version: 7.3.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/media/ssd1/software/install/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/media/ssd1/software/install/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/media/ssd1/software/install/anaconda3/lib/python3.7/site-packages/paddle/reader/decorator.py", line 303, in handle_worker
    r = mapper(sample)
  File "/media/ssd1/project/deep_learning/colonoscopy/resnet50_vd/reader_cv2.py", line 223, in process_batch_data
    process_image(sample, settings, mode, color_jitter, rotate))
  File "/media/ssd1/project/deep_learning/colonoscopy/resnet50_vd/reader_cv2.py", line 198, in process_image
    img = resize_short(img, target_size)
  File "/media/ssd1/project/deep_learning/colonoscopy/resnet50_vd/reader_cv2.py", line 94, in resize_short
    percent = float(target_size) / min(img.shape[0], img.shape[1])
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by Shixiaowei02** [comment]
您好，我已复现，您说的问题的确存在。请模型组同事 @shippingwang 跟进，谢谢
