### ISSUE TITLE
crnn_ctc 运行没问题，attention模式出错

### ISSUE THREAD

**Issue by huillll** [PaddlePaddle/models#2815]
```shell
env CUDA_VISIBLE_DEVICES=0 python train.py --skip_test=True --log_period=1000 --save_model_dir=./models_attention --model=attention
-----------  Configuration Arguments -----------
average_window: 0.15
batch_size: 32
eval_period: 15000
init_model: None
log_period: 1000
max_average_window: 12500
min_average_window: 10000
model: attention
parallel: False
profile: False
save_model_dir: ./models_attention
save_model_period: 15000
skip_batch_num: 0
skip_test: 1
test_images: None
test_list: None
total_step: 720000
train_images: None
train_list: None
use_gpu: True
------------------------------------------------
/usr/local/lib/python2.7/dist-packages/paddle/fluid/evaluator.py:71: Warning: The EditDistance is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.EditDistance instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
finish batch shuffle
W0716 12:37:56.041159  6098 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0716 12:37:56.043552  6098 device_context.cc:267] device: 0, cuDNN Version: 7.5.
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    main()
  File "train.py", line 214, in main
    train(args)
  File "train.py", line 148, in train
    results = train_one_batch(data)
  File "train.py", line 109, in train_one_batch
    fetch_list=fetch_vars)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator edit_distance error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 5392, in edit_distance
    attrs={"normalized": normalized})
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/evaluator.py", line 261, in __init__
    input=input, label=label, ignored_tokens=ignored_tokens)
  File "/home/luhui/ai-baidu/models/PaddleCV/ocr_recognition/attention_model.py", line 187, in attention_train_net
    input=maxid, label=label_out, ignored_tokens=[sos, eos])
  File "train.py", line 60, in train
    args, data_shape, num_classes)
  File "train.py", line 214, in main
    train(args)
  File "train.py", line 218, in <module>
    main()
C++ Callstacks: 
Reference string 10 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.cu:92]
PaddlePaddle Call Stacks: 
0       0x7fa9d28407d0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fa9d2840b49p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fa9d2ce17b4p paddle::operators::EditDistanceGPUKernel<paddle::platform::CUDAPlace, float>::Compute(paddle::framework::ExecutionContext const&) const + 5476
3       0x7fa9d2ce1bc3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::EditDistanceGPUKernel<paddle::platform::CUDAPlace, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7fa9d48c5887p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
5       0x7fa9d48c5c61p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
6       0x7fa9d48c325cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7fa9d29cc4bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
8       0x7fa9d29cf55fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7fa9d2831c5dp
10      0x7fa9d28736f6p
11      0x55ee22475fe5p PyEval_EvalFrameEx + 32869
12      0x55ee2246bd0ap PyEval_EvalCodeEx + 1754
13      0x55ee22473c38p PyEval_EvalFrameEx + 23736
14      0x55ee2246bd0ap PyEval_EvalCodeEx + 1754
15      0x55ee224735fep PyEval_EvalFrameEx + 22142
16      0x55ee2246bd0ap PyEval_EvalCodeEx + 1754
17      0x55ee22473c38p PyEval_EvalFrameEx + 23736
18      0x55ee2246bd0ap PyEval_EvalCodeEx + 1754
19      0x55ee22473c38p PyEval_EvalFrameEx + 23736
20      0x55ee2246bd0ap PyEval_EvalCodeEx + 1754
21      0x55ee22473c38p PyEval_EvalFrameEx + 23736
22      0x55ee2246bd0ap PyEval_EvalCodeEx + 1754
23      0x55ee2246b629p PyEval_EvalCode + 25
24      0x55ee2249c61fp
25      0x55ee22497322p PyRun_FileExFlags + 130
26      0x55ee2249667dp PyRun_SimpleFileExFlags + 397
27      0x55ee224451abp Py_Main + 1675
28      0x7faa104bbb97p __libc_start_main + 231
29      0x55ee22444a2ap _start + 42
```

**Comment by wanghaoshuang** [comment]
像是label的lod信息设置的不对
请问你用的paddle版本是？
是用自己的数据，还是官方提供的数据？

**Comment by huillll** [comment]
官方的数据，paddlepaddle版本1.5。crnn_ctc训练没有问题。lod信息是什么信息啊

**Comment by slf12** [comment]
> 官方的数据，paddlepaddle版本1.5。crnn_ctc训练没有问题。lod信息是什么信息啊

Lod是paddle处理变长数据序列的一个方式，详细信息可查看文档https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/user_guides/howto/basic_concept/lod_tensor.html

看报错信息的话，报错位置是https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/edit_distance_op.cu#L114
代码是在对lod信息进行check

**Comment by wanghaoshuang** [comment]
@slf12 正在复现这个问题，请稍等

**Comment by slf12** [comment]
我试了下python2.7 源码编译develop分支和pip安装1.5.1版本的paddle，运行attention模型都没有问题，我的cuda版本是8.0, cudnn版本是7.2, 请问你对代码做了什么修改吗？

**Comment by huillll** [comment]
代码没有修改。你用什么数据训练的啊。可以分享一下吗？我没有任何修改。

**Comment by slf12** [comment]
我用的也是data_reader.py中提供的下载路径的数据集

**Comment by slf12** [comment]
为了和你的环境保持一致，正在尝试在cuda10下安装paddle并运行模型，请稍等

**Comment by slf12** [comment]
经过在cuda10下排查问题，发现是warpctc op在cuda10下有问题，正在修复，你可以先用cuda9或者cuda8来做实验，感谢你提出问题。

**Comment by vison20080808** [comment]
rt，遇到相同问题，环境 Baidu AI Studio：

W0724 17:04:49.308575   351 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0724 17:04:49.311508   351 device_context.cc:267] device: 0, cuDNN Version: 7.3.


File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator edit_distance error.
Python Callstacks: 
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 5392, in edit_distance
    attrs={"normalized": normalized})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/evaluator.py", line 261, in __init__
    input=input, label=label, ignored_tokens=ignored_tokens)
  File "/home/aistudio/work/attention_model.py", line 187, in attention_train_net
    input=maxid, label=label_out, ignored_tokens=[sos, eos])
  File "./work/train.py", line 62, in train
    args, data_shape, num_classes)
  File "./work/train.py", line 243, in main
    train(args)
  File "./work/train.py", line 247, in <module>
    main()
C++ Callstacks: 
Reference string 2 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.cu:92]
PaddlePaddle Call Stacks: 
0       0x7f675b2f12e0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f675b2f1659p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f675b77cafap paddle::operators::EditDistanceGPUKernel<paddle::platform::CUDAPlace, float>::Compute(paddle::framework::ExecutionContext const&) const + 4938
3       0x7f675b77cf23p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::EditDistanceGPUKernel<paddle::platform::CUDAPlace, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7f675d24c657p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
5       0x7f675d24ca31p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
6       0x7f675d24a02cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7f675b47b47ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
8       0x7f675b47e51fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7f675b2e296dp
10      0x7f675b323ca6p
11      0x7f67bfda6199p PyCFunction_Call + 233
12      0x7f67bfe413f9p PyEval_EvalFrameEx + 33545
13      0x7f67bfe434b6p
14      0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
15      0x7f67bfe434b6p
16      0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
17      0x7f67bfe434b6p
18      0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
19      0x7f67bfe434b6p
20      0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
21      0x7f67bfe411d0p PyEval_EvalFrameEx + 32992
22      0x7f67bfe434b6p
23      0x7f67bfe435a8p PyEval_EvalCodeEx + 72
24      0x7f67bfe435ebp PyEval_EvalCode + 59
25      0x7f67bfe73a02p PyRun_FileExFlags + 178
26      0x7f67bfe73b67p PyRun_SimpleFileExFlags + 231
27      0x7f67bfe90d2cp Py_Main + 3676
28            0x400b54p main + 356
29      0x7f67bee04830p __libc_start_main + 240
30            0x400c01p

**Comment by slf12** [comment]
> rt，遇到相同问题，环境 Baidu AI Studio：
> 
> W0724 17:04:49.308575 351 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
> W0724 17:04:49.311508 351 device_context.cc:267] device: 0, cuDNN Version: 7.3.
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 650, in run
> use_program_cache=use_program_cache)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py", line 748, in _run exe.run(program.desc, scope, 0, True, True, fetch_var_name) paddle.fluid.core_avx.EnforceNotMet: Invoke operator edit_distance error. Python Callstacks: File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1748, in append_op attrs=kwargs.get("attrs", None)) File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op return self.main_program.current_block().append_op(_args, __kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 5392, in edit_distance attrs={"normalized": normalized}) File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/evaluator.py", line 261, in **init** input=input, label=label, ignored_tokens=ignored_tokens) File "/home/aistudio/work/attention_model.py", line 187, in attention_train_net input=maxid, label=label_out, ignored_tokens=[sos, eos]) File "./work/train.py", line 62, in train args, data_shape, num_classes) File "./work/train.py", line 243, in main train(args) File "./work/train.py", line 247, in main() C++ Callstacks: Reference string 2 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.cu:92] PaddlePaddle Call Stacks: 0 0x7f675b2f12e0p void paddle::platform::EnforceNotMet::Init<char const_>(char const_, char const_, int) + 352 1 0x7f675b2f1659p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137 2 0x7f675b77cafap paddle::operators::EditDistanceGPUKernel<paddle::platform::CUDAPlace, float>::Compute(paddle::framework::ExecutionContext const&) const + 4938 3 0x7f675b77cf23p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::EditDistanceGPUKernel<paddle::platform::CUDAPlace, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35 4 0x7f675d24c657p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
> 5 0x7f675d24ca31p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
> 6 0x7f675d24a02cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
> 7 0x7f675b47b47ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
> 8 0x7f675b47e51fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocatorstd::string > const&, bool) + 143
> 9 0x7f675b2e296dp
> 10 0x7f675b323ca6p
> 11 0x7f67bfda6199p PyCFunction_Call + 233
> 12 0x7f67bfe413f9p PyEval_EvalFrameEx + 33545
> 13 0x7f67bfe434b6p
> 14 0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
> 15 0x7f67bfe434b6p
> 16 0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
> 17 0x7f67bfe434b6p
> 18 0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
> 19 0x7f67bfe434b6p
> 20 0x7f67bfe405b5p PyEval_EvalFrameEx + 29893
> 21 0x7f67bfe411d0p PyEval_EvalFrameEx + 32992
> 22 0x7f67bfe434b6p
> 23 0x7f67bfe435a8p PyEval_EvalCodeEx + 72
> 24 0x7f67bfe435ebp PyEval_EvalCode + 59
> 25 0x7f67bfe73a02p PyRun_FileExFlags + 178
> 26 0x7f67bfe73b67p PyRun_SimpleFileExFlags + 231
> 27 0x7f67bfe90d2cp Py_Main + 3676
> 28 0x400b54p main + 356
> 29 0x7f67bee04830p __libc_start_main + 240
> 30 0x400c01p

感谢您的反馈，这个问题我们正在修复中，您可先用cuda8，cuda8是没有问题的

**Comment by vison20080808** [comment]
请问修复情况怎么样？

**Comment by slf12** [comment]
> 请问修复情况怎么样？
建议您先用cuda8, 我们最近会排期解决这个问题

**Comment by geng007** [comment]
> > 请问修复情况怎么样？
> > 建议您先用cuda8, 我们最近会排期解决这个问题

> 使用cuda 9，运行attention报bug
>>![图片](https://user-images.githubusercontent.com/38428867/64088228-0f1cf580-cd73-11e9-9cde-cf8b4a999a0d.png)

**Comment by slf12** [comment]
> > > 请问修复情况怎么样？
> > > 建议您先用cuda8, 我们最近会排期解决这个问题
> 
> > 使用cuda 9，运行attention报bug
> > > ![图片](https://user-images.githubusercontent.com/38428867/64088228-0f1cf580-cd73-11e9-9cde-cf8b4a999a0d.png)

这个看报的错误信息用法是embedding层查找的词的id超过了词表的大小，你是改过什么代码吗？
