### ISSUE TITLE
PaddleDetection Infer.py run error

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/models#2893]
python tools/infer.py -c configs/yolov3_mobilenet_v1.yml --infer_img=demo/000000570688.jpg --save_inference_model
W0722 20:50:18.140080  2945 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.2, Runtime API Version: 9.0
W0722 20:50:18.190894  2945 device_context.cc:267] device: 0, cuDNN Version: 7.6.
2019-07-22 20:50:18,213-INFO: Loading checkpoint from /home/airobot/models/PaddleCV/PaddleDetection/output/yolov3_mobilenet_v1/14000...
Traceback (most recent call last):
  File "tools/infer.py", line 257, in <module>
    main()
  File "tools/infer.py", line 167, in main
    save_infer_model(FLAGS, exe, feed_vars, test_fetches, infer_prog)
  File "tools/infer.py", line 113, in save_infer_model
    feeded_var_names = prune_feed_vars(feeded_var_names, target_vars, infer_prog)
  File "tools/infer.py", line 95, in prune_feed_vars
    prog = prog._prune(targets=target_vars)
  File "/home/airobot/anaconda3/envs/paddlepaddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3236, in _prune
    raise ValueError("All targets of prune() can only be "
ValueError: All targets of prune() can only be Variable or Operator.

**Comment by universea** [comment]
After this fix
fix save_inference_model cannot find feed vars (#2842)

* fix save_inference_model cannot find feed vars

* remove comment

* fix format

* add comment for pruned var

* add log for prune

**Comment by gongweibao** [comment]
黏贴代码请使用一下方式以便保持数据格式
```
这里是代码
```
