### ISSUE TITLE
怎么把量化或剪枝后的output模型（weight&&model），转成TF模型或者txt等可读文件呢

### ISSUE THREAD

**Issue by kayzss** [PaddlePaddle/models#2895]

**Comment by kayzss** [comment]
请问剪枝和量化后output（weight/model），怎么用呢？

**Comment by kayzss** [comment]
@qingqing01 @Superjomn  麻烦帮忙回答一下这个问题 拜托了 ！！！

**Comment by gongweibao** [comment]
转成TF模型现在不支持
txt可读文件，直接python中打印一下参数值就可以？

**Comment by kayzss** [comment]
output中有两个二进制文件weights和model，weights都是数字好转成text， models怎么用python转成text呢？ 可以写一个demo吗 @gongweibao

**Comment by wanghaoshuang** [comment]
@kayzss 

>models怎么用python转成text

你可以把weights和model 用[load_inference_model](load_inference_model) API load进来,  然后print program. 应该就是你要的text.

**Comment by wanghaoshuang** [comment]
PaddleSlim产出的模型不兼容tensorflow

**Comment by kayzss** [comment]
代码
exe = fluid.Executor(fluid.CPUPlace())
path = "./int8"
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=exe)
results = exe.run(inference_program,
              feed={feed_target_names[0]: feed_target_names},
              fetch_list=fetch_targets)

错误：
Traceback (most recent call last):
  File "/backup/compression/code/models-develop/PaddleSlim/extractparamsV2.py", line 46, in <module>
    [inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=exe)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/io.py", line 1092, in load_inference_model
    with open(model_filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './int8/__model__'

load_inference_model  这个具体怎么用呢 @gongweibao

**Comment by kayzss** [comment]
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model
你好使用这个API打印模型结构已经没问题了，但是怎么获取模型结构每个block中对应的参数值呢？ @gongweibao

**Comment by wanghaoshuang** [comment]
>怎么获取模型结构每个block中对应的参数值呢？ 

```
params = inference_program.global_block().all_parameters()
for param in params:
     param_value = np.array(fluid.global_scope().find_var(param.name)
     print param_value
```

**Comment by kayzss** [comment]
你好， 执行这句话 params = inference_program.global_block().all_parameters()， 打印出来的params 是空集  @gongweibao

**Comment by kayzss** [comment]
@gongweibao  你好可以帮忙回答以下这个问题吗？ 谢谢了！
