### ISSUE TITLE
reading_comprehension模型预测报错

### ISSUE THREAD

**Issue by AzureDreamDing** [PaddlePaddle/models#2912]
在用reading_comprehension模型进行预测时（按照官方文档操作），遇到如下错误：
Traceback (most recent call last):
  File "run.py", line 652, in <module>
    predict(logger, args)
  File "run.py", line 575, in predict
    exe, args.load_dir, main_program=main_program)
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/io.py", line 701, in load_persistables
    filename=filename)
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/io.py", line 572, in load_vars
    filename=filename)
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/io.py", line 607, in load_vars
    executor.run(load_prog)
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator load error.
Python Callstacks:
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/io.py", line 593, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/io.py", line 572, in load_vars
    filename=filename)
  File "/var/c20732a/paddle/paddle_env/lib/python2.7/site-packages/paddle/fluid/io.py", line 701, in load_persistables
    filename=filename)
  File "run.py", line 575, in predict
    exe, args.load_dir, main_program=main_program)
  File "run.py", line 652, in <module>
    predict(logger, args)
C++ Callstacks:
Cannot open file ../data/saved_model/pn_decoder_random_attn_fc_w for load op at [/paddle/paddle/fluid/operators/load_op.cc:39]

检查目录发现有pn_decoder:random_attn_fc_w这个文件。读取的模型文件是直接wget下来的并解压的，所以可能是在load模型文件时发生的错误。请帮忙看下如何解决。谢谢。
（试了paddlepaddle 1.3.1, 1.5.0, 1.5.1 都是同样的错误）

**Comment by xyzhou-puck** [comment]
您好，请问您的模型是直接进行预测的吗（没有经过训练）

**Comment by AzureDreamDing** [comment]
> 您好，请问您的模型是直接进行预测的吗（没有经过训练）

@xyzhou-puck 您好，我用的模型是通过bash download.sh直接下载下来，存放在/saved_model下的。
我是按照模型首页 https://github.com/PaddlePaddle/models/tree/develop/PaddleNLP/reading_comprehension 的步骤顺序执行下来的（跳过了**评估**步骤），所以应该是没有经过自己训练的。

谢谢！

**Comment by AzureDreamDing** [comment]
@xyzhou-puck 您好！请问是需要先自己训练模型，然后才能预测嘛？

**Comment by xyzhou-puck** [comment]
您好，这个repo之前变量名修改过，但是预训练的模型变量名没有更改，导致无法正确load预训练模型，您可以把data/saved_model/ 下含有 “:” 的文件名改为 "_"，即可正确运行，我也会update一下这个模型，保证可以正确运行

**Comment by AzureDreamDing** [comment]
@xyzhou-puck 好的，明白啦，谢谢您！
