### ISSUE TITLE
PaddleDetection: when i use CPU running infer, there occured an error as follow

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#2924]
my command: python tools/infer.py -c configs/faster_rcnn_r50_1x.yml --infer_img=demo/000000570688.jpg   --save_inference_model
error: 
2019-07-25 15:43:24,798-INFO: Loading checkpoint from output/faster_rcnn_r50_1x...
Traceback (most recent call last):
  File "tools/infer.py", line 257, in <module>
    main()
  File "tools/infer.py", line 167, in main
    save_infer_model(FLAGS, exe, feed_vars, test_fetches, infer_prog)
  File "tools/infer.py", line 113, in save_infer_model
    feeded_var_names = prune_feed_vars(feeded_var_names, target_vars, infer_prog)
  File "tools/infer.py", line 95, in prune_feed_vars
    prog = prog._prune(targets=target_vars)
  File "/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3236, in _prune
    raise ValueError("All targets of prune() can only be "
ValueError: All targets of prune() can only be Variable or Operator.
Can anyone help me please?

**Comment by qingqing01** [comment]
I can run sucessfuly by the latetst version:

```
(pyenv) PaddleDetection# python tools/infer.py -c configs/faster_rcnn_r50_1x.yml --infer_img=demo/000000570688.jpg --save_inference_model -o weights=https://paddlemodels.bj.bcebos.com/object_detection/faster_rcnn_r50_1x.tar use_gpu=false
W0725 09:17:41.220073 97778 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.0, Runtime API Version: 9.0
W0725 09:17:41.232821 97778 device_context.cc:267] device: 0, cuDNN Version: 7.5.
2019-07-25 09:17:41,255-INFO: Found /root/.cache/paddle/weights/faster_rcnn_r50_1x
2019-07-25 09:17:41,256-INFO: Loading checkpoint from /root/.cache/paddle/weights/faster_rcnn_r50_1x...
2019-07-25 09:17:41,557-INFO: Save inference model to output/faster_rcnn_r50_1x, input: [u'image', u'im_info', u'im_shape'], output: [u'multiclass_nms_0.tmp_0']...
2019-07-25 09:17:42,800-INFO: Not found annotation file annotations/instances_val2017.json, load coco17 categories.
2019-07-25 09:17:46,931-INFO: Infer iter 0
2019-07-25 09:17:46,957-INFO: Detection bbox results save in output/000000570688.jpg
```

Do you change any code?

**Comment by jerrywgz** [comment]
You can update develop code. It is fixed in https://github.com/PaddlePaddle/models/pull/2913

**Comment by endy-see** [comment]
> I can run sucessfuly by the latetst version:
> 
> ```
> (pyenv) PaddleDetection# python tools/infer.py -c configs/faster_rcnn_r50_1x.yml --infer_img=demo/000000570688.jpg --save_inference_model -o weights=https://paddlemodels.bj.bcebos.com/object_detection/faster_rcnn_r50_1x.tar use_gpu=false
> W0725 09:17:41.220073 97778 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.0, Runtime API Version: 9.0
> W0725 09:17:41.232821 97778 device_context.cc:267] device: 0, cuDNN Version: 7.5.
> 2019-07-25 09:17:41,255-INFO: Found /root/.cache/paddle/weights/faster_rcnn_r50_1x
> 2019-07-25 09:17:41,256-INFO: Loading checkpoint from /root/.cache/paddle/weights/faster_rcnn_r50_1x...
> 2019-07-25 09:17:41,557-INFO: Save inference model to output/faster_rcnn_r50_1x, input: [u'image', u'im_info', u'im_shape'], output: [u'multiclass_nms_0.tmp_0']...
> 2019-07-25 09:17:42,800-INFO: Not found annotation file annotations/instances_val2017.json, load coco17 categories.
> 2019-07-25 09:17:46,931-INFO: Infer iter 0
> 2019-07-25 09:17:46,957-INFO: Detection bbox results save in output/000000570688.jpg
> ```
> 
> Do you change any code?

no，i will try it with the update develop code

**Comment by endy-see** [comment]
> You can update develop code. It is fixed in #2913

I found that when i run PaddleDetection/tools/infer.py on cpu(exactly on my Mac), the system would stuck everytime which made me reopen my computer! I wander what's this problem...
