### ISSUE TITLE
Test VOC dataset error

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#2937]
I run PaddleDetection's faster_rcnn_r50_fpn_2x on my own dataset of VOC format success, but there occured an error when i run infer.py , the error as follows:
Traceback (most recent call last):
  File "tools/eval.py", line 119, in <module>
    main()
  File "tools/eval.py", line 107, in main
    eval_results(results, eval_feed, cfg.metric, resolution, FLAGS.output_file)
  File "/home/zhaoyanmei/models/PaddleCV/PaddleDetection/ppdet/utils/eval_utils.py", line 114, in eval_results
    res = np.mean(results[-1]['accum_map'][0])
KeyError: 'accum_map'

Can anyone help me please?

**Comment by Superjomn** [comment]
Is the script changed or the data format is not supported by the original script?

**Comment by endy-see** [comment]
> Is the script changed or the data format is not supported by the original script?

my config made some changes to match voc dataset as follow:
metric: VOC
FasterRCNNTrainFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/DadiDetection
    annotation: ImageSets/Main/trainval.txt
    image_dir: JPEGImages
    use_default_label: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  drop_last: false
  num_workers: 2

FasterRCNNEvalFeed:
  batch_size: 1
  dataset:
    dataset_dir: dataset/DadiDetection
    annotation: ImageSets/Main/test.txt
    image_dir: JPEGImages
    use_default_label: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32

FasterRCNNTestFeed:
  batch_size: 1
  dataset:
    annotation: ImageSets/Main/test.txt
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  drop_last: false

**Comment by qingqing01** [comment]
@yanmeizhao The RCNN model do not support VOC metrics now. Need to add  DetectionMap to the network in https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py#L120

refer SSD on VOC:

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/architectures/ssd.py#L78


Or you can do not run evalution during training.   We can support it in next after merged  https://github.com/PaddlePaddle/models/pull/2801

**Comment by endy-see** [comment]
> @yanmeizhao The RCNN model do not support VOC metrics now. Need to add DetectionMap to the network in https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py#L120
> 
> refer SSD on VOC:
> 
> https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/modeling/architectures/ssd.py#L78
> 
> Or you can do not run evalution during training. We can support it in next after merged #2801

so i had to resolve this problem by myself...
