### ISSUE TITLE
similarity_net 运行报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#2968]
环境：
python：2.7.15
paddle：1.5
cuda：9
cudnn：7
gpu：v100

命令：
python run_classifier.py  --compute_accuracy False --valid_data_dir ./data/test_pairwise_data --task_name simnet --config_path ./config/bow_pairwise.json --do_train True --do_valid False --vocab_path ./data/term2id.dict --do_infer False --save_steps 1000 --batch_size 128 --use_cuda True --train_data_dir ./data/train_pairwise_data --epoch 1 --skip_steps 10 --output_dir output_1 --test_data_dir ./data/test_pairwise_data --verbose_result False --infer_data_dir ./data/infer_data --task_mode pairwise --validation_steps 100 --do_test True

报错：
Traceback (most recent call last):
  File "run_classifier.py", line 471, in <module>
    main(conf_dict, args)
  File "run_classifier.py", line 448, in main
    train(conf_dict, args)
  File "run_classifier.py", line 306, in train
    mode="test")
  File "run_classifier.py", line 190, in valid_and_test
    fetch_list=[pred.name])
NameError: free variable 'pred' referenced before assignment in enclosing scope

**Comment by zhangyimi** [comment]
感谢反馈，马上修复。

**Comment by Lizhengo** [comment]
这个错误是run_classifier.py中的141行多了一个缩进，写到if条件外面应该就可以了。
