### ISSUE TITLE
NameError: global name 'bufsize' is not defined

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/models#2983]
当运行[PaddleDetection](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleDetection)中推理的代码
```
export PYTHONPATH=`pwd`:$PYTHONPATH
python tools/infer.py -c configs/mask_rcnn_r50_1x.yml \
    -o weights=https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar \
    --infer_img=demo/000000570688.jpg
```
提示
```
Traceback (most recent call last):
  File "tools/infer.py", line 261, in <module>
    main()
  File "tools/infer.py", line 161, in main
    reader = create_reader(test_feed)
  File "PaddleDetection/ppdet/data/data_feed.py", line 101, in create_reader
    'bufsize': bufsize,
NameError: global name 'bufsize' is not defined
```

**Comment by qingqing01** [comment]
Fixed in https://github.com/PaddlePaddle/models/pull/2989   另外为了稳定，建议可以使用release分支。 develop开发分支在持续更新。
