### ISSUE TITLE
PaddleSlim剪切报错 pruner.py 维度上的index报错，未解决

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/models#3002]
data_dir work/coco/train2017
use_multiprocess  False
2019-08-01 23:19:57,543-INFO: checkpoints: []
2019-08-01 23:19:57,543-INFO: checkpoints: []
2019-08-01 23:19:57,544-INFO: _get_best_ratios
2019-08-01 23:19:57,544-INFO: _get_best_ratios
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 534, in run
    strategy.on_epoch_begin(context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 640, in on_epoch_begin
    params, ratios = self._get_best_ratios(context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 618, in _get_best_ratios
    param_shape_backup=param_shape_backup)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 477, in _prune_parameters
    param_shape_backup=param_shape_backup)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 322, in _forward_pruning_ralated_params
    param_shape_backup=param_shape_backup)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 159, in _prune_parameter_by_idx
    np.array(param_t), pruned_idx, pruned_axis, lazy=lazy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/pruner.py", line 95, in prune_tensor
    mask[pruned_idx] = True
IndexError: index 257 is out of bounds for axis 0 with size 256
2019-08-01 23:19:58,209-ERROR: None
2019-08-01 23:19:58,209-ERROR: None
2019-08-01 23:19:58,228-WARNING: 
     You can try our memory optimize feature to save your memory usage:
         # create a build_strategy variable to set memory optimize option
         build_strategy = compiler.BuildStrategy()
         build_strategy.enable_inplace = True
         build_strategy.memory_optimize = True
         
         # pass the build_strategy to with_data_parallel API
         compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
             loss_name=loss.name, build_strategy=build_strategy)
      
     !!! Memory optimize is our experimental feature !!!
         some variables may be removed/reused internal to save memory usage, 
         in order to fetch the right value of the fetch_list, please set the 
         persistable property to true for each variable in fetch_list

         # Sample
         conv1 = fluid.layers.conv2d(data, 4, 5, 1, act=None) 
         # if you need to fetch conv1, then:
         conv1.persistable = True

                 
I0801 23:20:01.227057  1035 parallel_executor.cc:329] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0801 23:20:01.267546  1035 build_strategy.cc:340] SeqOnlyAllReduceOps:0, num_trainers:1

**Comment by universea** [comment]
主要是这个报错：
2019-08-01 23:19:57,544-INFO: _get_best_ratios
2019-08-01 23:19:57,544-INFO: _get_best_ratios
Traceback (most recent call last):
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 534, in run
strategy.on_epoch_begin(context)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 640, in on_epoch_begin
params, ratios = self._get_best_ratios(context)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 618, in _get_best_ratios
param_shape_backup=param_shape_backup)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 477, in _prune_parameters
param_shape_backup=param_shape_backup)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 322, in _forward_pruning_ralated_params
param_shape_backup=param_shape_backup)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 159, in _prune_parameter_by_idx
np.array(param_t), pruned_idx, pruned_axis, lazy=lazy)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/pruner.py", line 95, in prune_tensor
mask[pruned_idx] = True
IndexError: index 257 is out of bounds for axis 0 with size 256
2019-08-01 23:19:58,209-ERROR: None
2019-08-01 23:19:58,209-ERROR: None

**Comment by universea** [comment]
看着像 pruned_params 的问题

**Comment by universea** [comment]
File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/prune/pruner.py", line 95, in prune_tensor
mask[pruned_idx] = True
IndexError: index 257 is out of bounds for axis 0 with size 256

**Comment by universea** [comment]
配置文件如下：
version: 1.0
pruners:
    pruner_1:
        class: 'StructurePruner'
        pruning_axis:
            'conv*': 0
        criterions:
            '*': 'l1_norm'
strategies:
    uniform_pruning_strategy:
        class: 'UniformPruneStrategy'
        pruner: 'pruner_1'
        start_epoch: 0
        target_ratio: 0.5
        pruned_params: 'conv.*w_0'
        metric_name: 'map'
compressor:
    epoch: 15
    #init_model: './checkpoints/0' # Please enable this option for loading checkpoint.
    checkpoint_path: './checkpoint/'
    strategies:
        - uniform_pruning_strategy

**Comment by universea** [comment]
将pruned_params: 'conv.*w_0'改为pruned_params: '.*_sep_weights'，能跑但是Pruned size和radio为0，没有效果，而且中断后第二次运行出现以下错误
index created!
data_dir work/coco/train2017
use_multiprocess  True
2019-08-02 08:44:53,838-INFO: checkpoints: ['0', '1']
2019-08-02 08:44:53,838-INFO: checkpoints: ['0', '1']
Traceback (most recent call last):
  File "work/PaddleSlim/compress_ssd.py", line 340, in <module>
    main()
  File "work/PaddleSlim/compress_ssd.py", line 336, in main
    val_file_list=val_file_list)
  File "work/PaddleSlim/compress_ssd.py", line 290, in train
    eval_graph = com_pass.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 521, in run
    context, self.strategies = self._load_checkpoint(context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 386, in _load_checkpoint
    context.from_file(context_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/contrib/slim/core/compressor.py", line 146, in from_file
    data = pickle.load(context_file, encoding='bytes')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by wanghaoshuang** [comment]
多谢反馈，PaddleSlim在检测任务上实验还不充分，我们会尽快复现并修复该问题。

**Comment by universea** [comment]
> 多谢反馈，PaddleSlim在检测任务上实验还不充分，我们会尽快复现并修复该问题。
我是在AI Studio 上跑的

**Comment by universea** [comment]
> 多谢反馈，PaddleSlim在检测任务上实验还不充分，我们会尽快复现并修复该问题。

我是在AI Studio 上跑的

**Comment by universea** [comment]
> 多谢反馈，PaddleSlim在检测任务上实验还不充分，我们会尽快复现并修复该问题。
请问什么大概时候可以解决呀，需要帮忙不？

**Comment by wanghaoshuang** [comment]
@universea  可以在AI Sudio上把任务分享给我么？

**Comment by universea** [comment]
@wanghaoshuang 
我是在AISTUDIO上跑的命令行，不是notebook，现在的aistudio机制没办法fork，我可以把账号给你，方便微信联系吗？微信号是： universe_A

**Comment by A1exy** [comment]
@universea     请问UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte这个问题解决了没？

**Comment by wanghaoshuang** [comment]
@A1exy 

paddle/fluid/contrib/slim/core/compressor.py中
142 行 with open(file_name) as context_file:
改为 with open(file_name,'rb') as context_file:


https://github.com/PaddlePaddle/Paddle/blob/e5b9753a1895e7221a05e4d15787dd8b720eaad0/python/paddle/fluid/contrib/slim/core/compressor.py#L142

**Comment by A1exy** [comment]
@wanghaoshuang 
该方法有效，谢谢。
还有就是请问下昨天那个Prune后Inference维度不匹配的需求大概什么时候可以上传代码?

**Comment by zzchust** [comment]
mark
