### ISSUE TITLE
进行分类训练 莫名自动不运行了

### ISSUE THREAD

**Issue by sckalman123** [PaddlePaddle/models#3013]
请教下 我用 models/PaddleCV/image_classification/  这个进行分类训练 程序运行了200次左右就不再运行了 这个问题困扰我很久了 哪位大神帮忙看下？
已做的尝试如下  1 增加内存  2 再AIstudio 上训练   3 更换数据集

**Comment by sckalman123** [comment]
Pass 0, trainbatch 109, loss 2.51004,                             acc1 0.21875, acc5 0.50000, lr 0.10000, time 2.75 sec
Pass 0, trainbatch 110, loss 2.18330,                             acc1 0.43750, acc5 0.68750, lr 0.10000, time 2.75 sec
Pass 0, trainbatch 111, loss 2.94438,                             acc1 0.34375, acc5 0.59375, lr 0.10000, time 2.27 sec
Pass 0, trainbatch 112, loss 3.03557,                             acc1 0.40625, acc5 0.65625, lr 0.10000, time 2.26 sec
Pass 0, trainbatch 113, loss 2.82445,                             acc1 0.28125, acc5 0.40625, lr 0.10000, time 2.90 sec
Pass 0, trainbatch 114, loss 1.88679,                             acc1 0.40625, acc5 0.68750, lr 0.10000, time 2.92 sec
Pass 0, trainbatch 115, loss 2.42208,                             acc1 0.21875, acc5 0.43750, lr 0.10000, time 2.38 sec
Pass 0, trainbatch 116, loss 1.65175,                             acc1 0.50000, acc5 0.81250, lr 0.10000, time 2.95 sec
Pass 0, trainbatch 117, loss 3.60051,                             acc1 0.34375, acc5 0.50000, lr 0.10000, time 2.15 sec
Pass 0, trainbatch 118, loss 2.49101,                             acc1 0.31250, acc5 0.59375, lr 0.10000, time 3.00 sec
Pass 0, trainbatch 119, loss 2.73844,                             acc1 0.50000, acc5 0.75000, lr 0.10000, time 2.85 sec
Pass 0, trainbatch 120, loss 2.48738,                             acc1 0.31250, acc5 0.53125, lr 0.10000, time 2.55 sec
Pass 0, trainbatch 121, loss 1.52484,                             acc1 0.37500, acc5 0.62500, lr 0.10000, time 2.34 sec
Pass 0, trainbatch 122, loss 1.73376,                             acc1 0.53125, acc5 0.65625, lr 0.10000, time 2.53 sec
Pass 0, trainbatch 123, loss 1.52444,                             acc1 0.37500, acc5 0.62500, lr 0.10000, time 2.64 sec
Pass 0, trainbatch 124, loss 3.09096,                             acc1 0.43750, acc5 0.50000, lr 0.10000, time 2.55 sec
Pass 0, trainbatch 125, loss 3.08240,                             acc1 0.31250, acc5 0.43750, lr 0.10000, time 3.04 sec
Pass 0, trainbatch 126, loss 1.63966,                             acc1 0.40625, acc5 0.59375, lr 0.10000, time 2.40 sec
Pass 0, trainbatch 127, loss 2.63035,                             acc1 0.43750, acc5 0.59375, lr 0.10000, time 2.76 sec
Pass 0, trainbatch 128, loss 2.35903,                             acc1 0.34375, acc5 0.65625, lr 0.10000, time 2.85 sec
Pass 0, trainbatch 129, loss 2.60210,                             acc1 0.37500, acc5 0.62500, lr 0.10000, time 2.77 sec
Pass 0, trainbatch 130, loss 3.56675,                             acc1 0.21875, acc5 0.43750, lr 0.10000, time 2.38 sec
Pass 0, trainbatch 131, loss 1.61987,                             acc1 0.40625, acc5 0.62500, lr 0.10000, time 2.63 sec
Pass 0, trainbatch 132, loss 1.35780,                             acc1 0.43750, acc5 0.65625, lr 0.10000, time 2.73 sec

**Comment by sckalman123** [comment]
wsy@wsy:~/suncan/fluid/models/PaddleCV/image_classification$ python train.py        --model=SE_ResNeXt50_32x4d  --batch_size=32        --total_images=4803        --class_dim=6  --image_shape=3,224,224        --model_save_dir=output/        --with_mem_opt=False        --with_inplace=True        --lr_strategy=piecewise_decay        --lr=0.1  --data_dir=/home/wsy/suncan/fluid/python_learn/LearnPaddle2/note11/images/
-------------  Configuration Arguments -------------
               batch_size : 32
               checkpoint : None
                class_dim : 6
                 data_dir : /home/wsy/suncan/fluid/python_learn/LearnPaddle2/note11/images/
                enable_ce : False
                     fp16 : False
              image_shape : 3,224,224
               is_distill : False
                 l2_decay : 0.0001
  label_smoothing_epsilon : 0.2
              lower_ratio : 0.75
              lower_scale : 0.08
                       lr : 0.1
              lr_strategy : piecewise_decay
              mixup_alpha : 0.2
                    model : SE_ResNeXt50_32x4d
           model_save_dir : output/
            momentum_rate : 0.9
               num_epochs : 120
         pretrained_model : None
        resize_short_size : 256
               scale_loss : 1.0
             total_images : 4803
              upper_ratio : 1.33333333333
                  use_gpu : True
      use_label_smoothing : False
                use_mixup : False
             with_inplace : 1
             with_mem_opt : 0
----------------------------------------------------
W0805 13:12:31.410238  4182 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 52, Driver API Version: 10.1, Runtime API Version: 10.0
W0805 13:12:31.412382  4182 device_context.cc:267] device: 0, cuDNN Version: 7.4.
I0805 13:12:31.526055  4182 parallel_executor.cc:329] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0805 13:12:32.862170  4182 build_strategy.cc:340] SeqOnlyAllReduceOps:0, num_trainers:1
libpng warning: iCCP: known incorrect sRGB profile
Pass 0, trainbatch 0, loss 1.82162,                             acc1 0.21875, acc5 0.43750, lr 0.10000, time 3.84 sec
Pass 0, trainbatch 1, loss 2.51673,                             acc1 0.25000, acc5 0.43750, lr 0.10000, time 1.26 sec
Pass 0, trainbatch 2, loss 3.73522,                             acc1 0.09375, acc5 0.40625, lr 0.10000, time 0.77 sec
Pass 0, trainbatch 3, loss 8.40159,                             acc1 0.09375, acc5 0.40625, lr 0.10000, time 0.77 sec
libpng warning: iCCP: known incorrect sRGB profile
Pass 0, trainbatch 4, loss 11.92326,                             acc1 0.12500, acc5 0.34375, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 5, loss 9.63670,                             acc1 0.18750, acc5 0.21875, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 6, loss 6.30791,                             acc1 0.25000, acc5 0.40625, lr 0.10000, time 0.77 sec
Pass 0, trainbatch 7, loss 7.74398,                             acc1 0.15625, acc5 0.37500, lr 0.10000, time 0.77 sec
Pass 0, trainbatch 8, loss 2.84560,                             acc1 0.21875, acc5 0.37500, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 9, loss 2.37175,                             acc1 0.21875, acc5 0.40625, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 10, loss 4.25705,                             acc1 0.18750, acc5 0.28125, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 11, loss 3.75080,                             acc1 0.18750, acc5 0.31250, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 12, loss 4.48633,                             acc1 0.25000, acc5 0.46875, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 13, loss 4.82184,                             acc1 0.25000, acc5 0.50000, lr 0.10000, time 0.78 sec
libpng warning: iCCP: known incorrect sRGB profile
Pass 0, trainbatch 14, loss 1.97209,                             acc1 0.31250, acc5 0.53125, lr 0.10000, time 0.79 sec
Pass 0, trainbatch 15, loss 4.51114,                             acc1 0.25000, acc5 0.43750, lr 0.10000, time 0.77 sec
libpng warning: iCCP: known incorrect sRGB profile
Pass 0, trainbatch 16, loss 2.93016,                             acc1 0.28125, acc5 0.43750, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 17, loss 4.07867,                             acc1 0.21875, acc5 0.37500, lr 0.10000, time 0.79 sec
Pass 0, trainbatch 18, loss 3.68400,                             acc1 0.34375, acc5 0.53125, lr 0.10000, time 0.78 sec
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/reader/decorator.py", line 303, in handle_worker
    r = mapper(sample)
  File "/home/wsy/suncan/fluid/models/PaddleCV/image_classification/reader_cv2.py", line 216, in process_batch_data
    process_image(sample, settings, mode, color_jitter, rotate))
  File "/home/wsy/suncan/fluid/models/PaddleCV/image_classification/reader_cv2.py", line 187, in process_image
    img = random_crop(img, crop_size, settings)
  File "/home/wsy/suncan/fluid/models/PaddleCV/image_classification/reader_cv2.py", line 81, in random_crop
    (size, size)
error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'


libpng warning: iCCP: known incorrect sRGB profile
Pass 0, trainbatch 19, loss 2.47428,                             acc1 0.15625, acc5 0.50000, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 20, loss 3.27152,                             acc1 0.31250, acc5 0.59375, lr 0.10000, time 0.79 sec
libpng warning: iCCP: known incorrect sRGB profile
Pass 0, trainbatch 21, loss 1.96325,                             acc1 0.12500, acc5 0.18750, lr 0.10000, time 0.82 sec
Pass 0, trainbatch 22, loss 1.96282,                             acc1 0.09375, acc5 0.31250, lr 0.10000, time 0.79 sec
Pass 0, trainbatch 23, loss 1.82166,                             acc1 0.21875, acc5 0.40625, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 24, loss 1.88504,                             acc1 0.12500, acc5 0.25000, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 25, loss 3.57963,                             acc1 0.40625, acc5 0.65625, lr 0.10000, time 0.79 sec
Pass 0, trainbatch 26, loss 1.66445,                             acc1 0.21875, acc5 0.56250, lr 0.10000, time 0.79 sec
Pass 0, trainbatch 27, loss 3.66242,                             acc1 0.31250, acc5 0.43750, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 28, loss 3.52557,                             acc1 0.34375, acc5 0.40625, lr 0.10000, time 0.78 sec
Pass 0, trainbatch 29, loss 5.77537,                             acc1 0.28125, acc5 0.34375, lr 0.10000, time 0.78 sec

**Comment by wopeizl** [comment]
是最新的develop分支models么？

**Comment by sckalman123** [comment]
是的 是用的最新的 develop 分支

**Comment by wopeizl** [comment]
怀疑跟数据集有关系，可能部分图片有问题，可以安装imagemagick工具查（ https://imagemagick.org/index.php）， 然后 find ./ -type f -name "*.png"|xargs identify -verbose|grep png:iCCP: , 如果有输出说明数据集文件有问题

**Comment by sckalman123** [comment]
wsy@wsy:~/suncan/fluid/python_learn/LearnPaddle2/note11/images$ find ./ -type f -name "*.png"|xargs identify -verbose|grep png:iCCP:

**Comment by sckalman123** [comment]
没有任何输出 数据集没有问题  另外我也单侧是测试了只有一点点数据集的图片 运行到20次的时候就出现同样的现象

**Comment by sckalman123** [comment]
基本上没有改动  就是github 的源码  然后数据集就是建了几个文件夹 放了些确定没问题的图片 麻烦您那边也先试试   我环境是ubuntu 16.04  显卡24G 内存16G  同时再aistuido 上也同样测试过 结果是一样的
这个我是要用在实际项目中的  用你们的paddle 替换tesnsorflow 的 麻烦您那边也试试 并优先解决下。
另外再这里来回发信息 几个小时一句话很浪费时间   能不能加下qq  41485179 沟通？

**Comment by wangguibao** [comment]
```
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/paddle/reader/decorator.py", line 303, in handle_worker
r = mapper(sample)
File "/home/wsy/suncan/fluid/models/PaddleCV/image_classification/reader_cv2.py", line 216, in process_batch_data
process_image(sample, settings, mode, color_jitter, rotate))
File "/home/wsy/suncan/fluid/models/PaddleCV/image_classification/reader_cv2.py", line 187, in process_image
img = random_crop(img, crop_size, settings)
File "/home/wsy/suncan/fluid/models/PaddleCV/image_classification/reader_cv2.py", line 81, in random_crop
(size, size)
error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

这里有个thread报错了。

最后几行报错信息：
```
error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```
我搜了一下网上说法，多数都是在说图像问题，您可以参考下：
https://blog.csdn.net/weixin_43358444/article/details/83217902
https://github.com/aleju/imgaug/issues/205#issuecomment-441366693
https://stackoverflow.com/questions/52916736/error-215assertion-failed-ssize-empty-in-function-cvresize

所以还是先请您检查一下是否有相关问题？

**Comment by sckalman123** [comment]
经测试   由于两个原因引起的   1 存在一张1像素的照片   （程序不够健壮）  2 如果存在（copy） 这种文件名的照片  split 时也会出错    

这两点改进后  运行了7+个小时  程序 莫名又挂掉了  只有一个killed 的提示 ，请帮忙提供下办法如果检测这个问题

**Comment by wangguibao** [comment]
```
这两点改进后 运行了7+个小时 程序 莫名又挂掉了 只有一个killed 的提示 ，请帮忙提供下办法如果检测这个问题
```
Hi，这个现在解决了吗？
