### ISSUE TITLE
ocr_recognition 运行infer报错，看了很久没看出问题

### ISSUE THREAD

**Issue by banbishan** [PaddlePaddle/models#3045]
```
(pd) root@EDLL20190423:/mnt/e/ocr_recognition/ocr_recognition# python infer.py --model_path="./models/model_15000" --inp
ut_images_list="input_list.txt" --input_images_dir="input_images" --use_gpu="False" --model="attention"
-----------  Configuration Arguments -----------
batch_size: 1
dict: None
input_images_dir: input_images
input_images_list: input_list.txt
iterations: 0
model: attention
model_path: ./models/model_15000
profile: False
skip_batch_num: 0
use_gpu: 0
------------------------------------------------
Traceback (most recent call last):
  File "infer.py", line 157, in <module>
    main()
  File "infer.py", line 153, in main
    inference(args)
  File "infer.py", line 78, in inference
    fluid.io.load_params(exe, dirname=model_dir, filename=model_file_name)
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/io.py", line 699, in load_params
    filename=filename)
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/io.py", line 611, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/io.py", line 648, in load_vars
    executor.run(load_prog)
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load_combine error.
Python Callstacks:
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/io.py", line 647, in load_vars
    attrs={'file_path': os.path.join(load_dirname, filename)})
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/io.py", line 611, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/io.py", line 699, in load_params
    filename=filename)
  File "infer.py", line 78, in inference
    fluid.io.load_params(exe, dirname=model_dir, filename=model_file_name)
  File "infer.py", line 153, in main
    inference(args)
  File "infer.py", line 157, in <module>
    main()
C++ Callstacks:
You are not allowed to load partial data via load_combine_op, use load_op instead. at [/paddle/paddle/fluid/operators/load_combine_op.h:100]
PaddlePaddle Call Stacks:
0       0x7fa8d0743650p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fa8d07439c9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fa8d0fa23b4p paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const + 1620
3       0x7fa8d0fa275ep paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 798
4       0x7fa8d0fa2b33p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7fa8d1a8a547p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
6       0x7fa8d1a8acb1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7fa8d1a88b5bp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 267
8       0x7fa8d08c2c9ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 206
9       0x7fa8d08c5d1fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
10      0x7fa8d0735e9dp
11      0x7fa8d077297ep
12      0x7fa8f134cc54p _PyCFunction_FastCallDict + 340
13      0x7fa8f13d4c0ep
14      0x7fa8f13f775ap _PyEval_EvalFrameDefault + 778
15      0x7fa8f13cde66p
16      0x7fa8f13ceed6p
17      0x7fa8f13d4b95p
18      0x7fa8f13f851cp _PyEval_EvalFrameDefault + 4300
19      0x7fa8f13cde66p
20      0x7fa8f13cee73p
21      0x7fa8f13d4b95p
22      0x7fa8f13f775ap _PyEval_EvalFrameDefault + 778
23      0x7fa8f13cde66p
24      0x7fa8f13ceed6p
25      0x7fa8f13d4b95p
26      0x7fa8f13f851cp _PyEval_EvalFrameDefault + 4300
27      0x7fa8f13cde66p
28      0x7fa8f13ceed6p
29      0x7fa8f13d4b95p
30      0x7fa8f13f851cp _PyEval_EvalFrameDefault + 4300
31      0x7fa8f13cde66p
32      0x7fa8f13ceed6p
33      0x7fa8f13d4b95p
34      0x7fa8f13f851cp _PyEval_EvalFrameDefault + 4300
35      0x7fa8f13ce29ep
36      0x7fa8f13ceed6p
37      0x7fa8f13d4b95p
38      0x7fa8f13f775ap _PyEval_EvalFrameDefault + 778
39      0x7fa8f13cec5bp
40      0x7fa8f13d4b95p
41      0x7fa8f13f775ap _PyEval_EvalFrameDefault + 778
42      0x7fa8f13cf9b9p PyEval_EvalCodeEx + 809
43      0x7fa8f13d075cp PyEval_EvalCode + 28
44      0x7fa8f1450744p
45      0x7fa8f1450b41p PyRun_FileExFlags + 161
46      0x7fa8f1450d43p PyRun_SimpleFileExFlags + 451
47      0x7fa8f1454833p Py_Main + 1555
48      0x7fa8f131e88ep main + 238
49      0x7fa8f0a30830p __libc_start_main + 240
50      0x7fa8f13fe160p
```

**Comment by Xreki** [comment]
加载模型参数出错了。

> C++ Callstacks:
You are not allowed to load partial data via load_combine_op, use load_op instead. at [/paddle/paddle/fluid/operators/load_combine_op.h:100]

意思是说，你的参数是分开存储的，一个参数存一个文件。你加载参数的时候，就不要指定`params_filename`。

**Comment by banbishan** [comment]
@Xreki 感谢！！！解决了，之前一直在看这句话，还以为让我换算子。

**Comment by gaozheyuan** [comment]
所以应该如何操作？
