### ISSUE TITLE
similarity_net infer报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#3107]
BUG复现步骤：

环境：

linux

python2.7

paddle1.5.1

cuda 9

cudnn 7

命令
sh run.sh infer

报错信息：
start test process ...
Traceback (most recent call last):
  File "run_classifier.py", line 476, in <module>
    main(conf_dict, args)
  File "run_classifier.py", line 457, in main
    infer(args)
  File "run_classifier.py", line 435, in infer
    infer_file.write(_data + "\t" + _pred + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u4f60' in position 0: ordinal not in range(128)

**Comment by Lizhengo** [comment]
你好，在run_classifier.py开头import codecs, 然后在433行那里改成codecs.open(args.infer_result_path, "w", "utf-8")再试试？
<img width="611" alt="image" src="https://user-images.githubusercontent.com/28192236/63020315-5e88a800-bed0-11e9-9dd8-214de8e03881.png">
