### ISSUE TITLE
/models-1.5/PaddleCV/image_classification执行infer和eval报同样错误

### ISSUE THREAD

**Issue by duanlin0505** [PaddlePaddle/models#3120]
[image_classification]$ fluid infer.py                                        
/home/hicqa/paddle/paddle_release_home/python/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:38: UserWarning: [Errno 13] Permission denied.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
-------------  Configuration Arguments -------------
                class_dim : 1000
              image_shape : 3,224,224
                    model : SE_ResNeXt50_32x4d
         pretrained_model : None
        resize_short_size : 256
           save_inference : False
                  use_gpu : True
             with_mem_opt : True
memory_optimize is deprecated. Use CompiledProgram and Executor
W0816 11:01:36.875445 44793 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.0, Runtime API Version: 10.0
W0816 11:01:36.880609 44793 device_context.cc:267] device: 0, cuDNN Version: 7.4.
Traceback (most recent call last):
  File "infer.py", line 115, in <module>
    main()
  File "infer.py", line 111, in main
    infer(args)
  File "infer.py", line 80, in infer
    fluid.io.load_persistables(exe, pretrained_model)
  File "/home/hicqa/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 747, in load_persistables
    filename=filename)
  File "/home/hicqa/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 599, in load_vars
    load_dirname = os.path.normpath(dirname)
  File "/home/hicqa/paddle/paddle_release_home/python/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ceci3** [comment]
您好，您有指定 --pretrained_model 这个参数吗？

**Comment by duanlin0505** [comment]
不知道是哪个参数导致的问题，默认参数执行的
