### ISSUE TITLE
ocr attention 模型运行报错

### ISSUE THREAD

**Issue by banbishan** [PaddlePaddle/models#3370]
系统：ubuntu18.08
paddle版本：1.5 cpu
图片为宽高不一的图片，宽/高都小于512/48，示例如下
294 28 img_0000001.jpg 7,66,714,51,1441,14,293,407,1746,3257,78
92 22 img_0000002.jpg 617,569,1434,1423
62 28 img_0000003.jpg 137,36

报错如下：
```
finish batch shuffle

Traceback (most recent call last):
  File "train.py", line 235, in <module>
    main()
  File "train.py", line 231, in main
    train(args)
  File "train.py", line 164, in train
    results = train_one_batch(data)
  File "train.py", line 125, in train_one_batch
    fetch_list=fetch_vars)
  File "/home/jason/anaconda3/envs/pdc/lib/python3.6/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/jason/anaconda3/envs/pdc/lib/python3.6/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator edit_distance error.
Python Callstacks: 
  File "/home/jason/anaconda3/envs/pdc/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/jason/anaconda3/envs/pdc/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/jason/anaconda3/envs/pdc/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 5430, in edit_distance
    attrs={"normalized": normalized})
  File "/home/jason/anaconda3/envs/pdc/lib/python3.6/site-packages/paddle/fluid/evaluator.py", line 261, in __init__
    input=input, label=label, ignored_tokens=ignored_tokens)
  File "/home/jason/dataset/ocr_recognition/attention_model.py", line 200, in attention_train_net
    input=maxid, label=label_out, ignored_tokens=[sos, eos])
  File "train.py", line 74, in train
    args, data_shape, num_classes)
  File "train.py", line 231, in main
    train(args)
  File "train.py", line 235, in <module>
    main()
C++ Callstacks: 
Reference string 12 is empty. at [/paddle/paddle/fluid/operators/edit_distance_op.h:42]
PaddlePaddle Call Stacks: 
0       0x7f0424dd6650p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f0424dd69c9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f04253f2582p paddle::operators::EditDistanceKernel<paddle::platform::CPUPlace, float>::Compute(paddle::framework::ExecutionContext const&) const + 2946
3       0x7f04253f2603p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::EditDistanceKernel<paddle::platform::CPUPlace, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7f042611d547p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
5       0x7f042611dcb1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
6       0x7f042611bb5bp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 267
7       0x7f0424f55c9ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 206
8       0x7f0424f58d1fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7f0424dc8e9dp
10      0x7f0424e0597ep
11      0x560291d56c54p _PyCFunction_FastCallDict + 340
12      0x560291ddec0ep
13      0x560291e0175ap _PyEval_EvalFrameDefault + 778
14      0x560291dd7e66p
15      0x560291dd8ed6p
16      0x560291ddeb95p
17      0x560291e0251cp _PyEval_EvalFrameDefault + 4300
18      0x560291dd7e66p
19      0x560291dd8ed6p
20      0x560291ddeb95p
21      0x560291e0251cp _PyEval_EvalFrameDefault + 4300
22      0x560291dd829ep
23      0x560291dd8ed6p
24      0x560291ddeb95p
25      0x560291e0175ap _PyEval_EvalFrameDefault + 778
26      0x560291dd829ep
27      0x560291dd8ed6p
28      0x560291ddeb95p
29      0x560291e0175ap _PyEval_EvalFrameDefault + 778
30      0x560291dd8c5bp
31      0x560291ddeb95p
32      0x560291e0175ap _PyEval_EvalFrameDefault + 778
33      0x560291dd99b9p PyEval_EvalCodeEx + 809
34      0x560291dda75cp PyEval_EvalCode + 28
35      0x560291e5a744p
36      0x560291e5ab41p PyRun_FileExFlags + 161
37      0x560291e5ad43p PyRun_SimpleFileExFlags + 451
38      0x560291e5e833p Py_Main + 1555
39      0x560291d2888ep main + 238
40      0x7f0440ce5b97p __libc_start_main + 231
41      0x560291e08160p
```

**Comment by wanghaoshuang** [comment]
hi，你有对models下的code做修改么？如果有的话，把修改部分贴一下？

**Comment by banbishan** [comment]
> hi，你有对models下的code做修改么？如果有的话，把修改部分贴一下？

只修改了data_reader.py中的NUM_CLASSES = 5990

**Comment by wanghaoshuang** [comment]
从log看，你给的label应该有个空的sequence, edit_distance op没有正确处理这个空的sequence.
你可以尝试用fluid.layers.Print 打印下label, 看下其lod信息。

**Comment by banbishan** [comment]
> 从log看，你给的label应该有个空的sequence, edit_distance op没有正确处理这个空的sequence.
> 你可以尝试用fluid.layers.Print 打印下label, 看下其lod信息。

我用python检查过，我把train.list按行读入，用split（' '）分开后，用len看长度，都是4，看了label用split（','）分隔后的长度都大于1.
