### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by qwertyuiop194** [PaddlePaddle/models#3407]
在原始代码上，载入自己的训练集，出现如下错误；print（len(b_out)） = 4; 里面是double_buffer_0, mean、accuracy1，accuracy2; 共4项

这里面也没有loss等参数啊，为何在将其赋值为loss
 train_py_reader, train_cost, train_acc1, train_acc5, global_lr = b_out[0],b_out[1],b_out[2],b_out[3],b_out[4]

Traceback (most recent call last):
  File "train.py", line 622, in <module>
    main()
  File "train.py", line 618, in main
    train(args)
  File "train.py", line 379, in train
    train_py_reader, train_cost, train_acc1, train_acc5, global_lr = b_out[0],b_out[1],b_out[2],b_out[3],b_out[4]
IndexError: list index out of range

**Comment by eddieheyutong** [comment]
你好你用的是deeplab吗

**Comment by qwertyuiop194** [comment]
不是
