### ISSUE TITLE
PaddleDetection保存预测模型报错

### ISSUE THREAD

**Issue by zhangzhiyong** [PaddlePaddle/models#3469]
git clone PaddlePaddle/models 的develop分支，在本机上能够将实现图片预测，但是保存预测模型准备进行生产环境部署测试是，保存预测模型错误。步骤如下：

1、在PaddleDetection下执行python tools/infer.py -c configs/mask_rcnn_r50_1x.yml \
    -o weights=https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar \
    --infer_img=demo/000000570688.jpg，能够看到预测的图片上已经识别物体打上标记框

2、执行python tools/infer.py -c configs/mask_rcnn_r50_1x.yml --infer_img=demo/000000570688.jpg --save_inference_model ，增加了--save_inference_model参数进行预测模型导出，提示错误如下：

2019-10-03 10:17:20,007-INFO: Loading parameters from output/mask_rcnn_r50_1x/model_final...
Traceback (most recent call last):
  File "tools/infer.py", line 317, in <module>
    main()
  File "tools/infer.py", line 184, in main
    save_infer_model(FLAGS, exe, feed_vars, test_fetches, infer_prog)
  File "tools/infer.py", line 128, in save_infer_model
    infer_prog)
  File "tools/infer.py", line 109, in prune_feed_vars
    prog = prog._prune(feeded_var_names, targets=target_vars)
TypeError: _prune() got multiple values for argument 'targets'

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/models/pull/3472 已修复，多谢反馈
