### ISSUE TITLE
PaddleDetection load params failed

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/models#3489]
config file: yolov3_mobilenet_v1_voc.yml

code:
```
def main():
    cfg = load_config(FLAGS.config)
    if 'architecture' in cfg:
        main_arch = cfg.architecture
    else:
        raise ValueError("'architecture' not specified in config file.")

    merge_config(FLAGS.opt)
    if 'log_iter' not in cfg:
        cfg.log_iter = 20

    # check if set use_gpu=True in paddlepaddle cpu version
    check_gpu(cfg.use_gpu)

    if cfg.use_gpu:
        devices_num = fluid.core.get_cuda_device_count()
    else:
        devices_num = int(
            os.environ.get('CPU_NUM', multiprocessing.cpu_count()))

    if 'train_feed' not in cfg:
        train_feed = create(main_arch + 'TrainFeed')
    else:
        train_feed = create(cfg.train_feed)

    if 'eval_feed' not in cfg:
        eval_feed = create(main_arch + 'EvalFeed')
    else:
        eval_feed = create(cfg.eval_feed)

    place = fluid.CUDAPlace(0) if cfg.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)

    lr_builder = create('LearningRate')
    optim_builder = create('OptimizerBuilder')

    # build program
    startup_prog = fluid.Program()
    train_prog = fluid.Program()
    with fluid.program_guard(train_prog, startup_prog):
        with fluid.unique_name.guard():
            model = create(main_arch)
            train_pyreader, feed_vars = create_feed(train_feed)
            train_fetches = model.train(feed_vars)
            loss = train_fetches['loss']
            lr = lr_builder()
            optimizer = optim_builder(lr)
            optimizer.minimize(loss)

#    graph = IrGraph(core.Graph(train_prog.desc), for_test=True)
#    marked_nodes = set()
#    for op in graph.all_op_nodes():
#        print(op.name())
#        if op.name().find('conv') > -1:
#            marked_nodes.add(op)
#    graph.draw('.', 'forward', marked_nodes)
#
#    return

    train_reader = create_reader(train_feed, cfg.max_iters * devices_num,
                                 FLAGS.dataset_dir)
    train_pyreader.decorate_sample_list_generator(train_reader, place)

    # parse train fetches
    train_keys, train_values, _ = parse_fetches(train_fetches)
    train_values.append(lr)

    train_fetch_list=[]
    for k, v in zip(train_keys, train_values):
        train_fetch_list.append((k, v))
    print("train_fetch_list: {}".format(train_fetch_list))

    eval_prog = fluid.Program()
    with fluid.program_guard(eval_prog, startup_prog):
        with fluid.unique_name.guard():
            model = create(main_arch)
            eval_pyreader, feed_vars = create_feed(eval_feed)
            fetches = model.eval(feed_vars)
    eval_prog = eval_prog.clone(True)

    eval_reader = create_reader(eval_feed, args_path=FLAGS.dataset_dir)
    eval_pyreader.decorate_sample_list_generator(eval_reader, place)

    # parse eval fetches
    extra_keys = []
    if cfg.metric == 'COCO':
        extra_keys = ['im_info', 'im_id', 'im_shape']
    if cfg.metric == 'VOC':
        extra_keys = ['gt_box', 'gt_label', 'is_difficult']
    eval_keys, eval_values, eval_cls = parse_fetches(fetches, eval_prog,
                                                         extra_keys)

    eval_fetch_list=[]
    for k, v in zip(eval_keys, eval_values):
        eval_fetch_list.append((k, v))


    exe.run(startup_prog)

    start_iter = 0


    checkpoint.load_params(exe, train_prog, cfg.pretrain_weights, ignore_params=[])
```

models commit:
```
commit b860c3baf7fadad705ff94bff0f058e4ebaf9680
```

error log:
```
2019-10-10 02:59:24,844-INFO: Decompressing /root/.cache/paddle/weights/MobileNetV1_pretrained.tar...
Traceback (most recent call last):
  File "compress.py", line 231, in <module>
    main()
  File "compress.py", line 160, in main
    checkpoint.load_params(exe, train_prog, cfg.pretrain_weights, ignore_params=[])
  File "/root/models/PaddleCV/PaddleDetection/ppdet/utils/checkpoint.py", line 92, in load_params
    path = _get_weight_path(path)
  File "/root/models/PaddleCV/PaddleDetection/ppdet/utils/checkpoint.py", line 77, in _get_weight_path
    path = get_weights_path(path)
  File "/root/models/PaddleCV/PaddleDetection/ppdet/utils/download.py", line 72, in get_weights_path
    return get_path(url, WEIGHTS_HOME)
  File "/root/models/PaddleCV/PaddleDetection/ppdet/utils/download.py", line 171, in get_path
    _decompress(fullname)
  File "/root/models/PaddleCV/PaddleDetection/ppdet/utils/download.py", line 287, in _decompress
    tf.extractall(path=fpath_tmp)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 2081, in extractall
    self.extract(tarinfo, path)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 2235, in makefile
    copyfileobj(source, target)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/local/python2.7.15/lib/python2.7/shutil.py", line 63, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 831, in read
    buf += self.fileobj.read(size - len(buf))
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 743, in read
    return self.readnormal(size)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 758, in readnormal
    return self.__read(size)
  File "/usr/local/python2.7.15/lib/python2.7/tarfile.py", line 750, in __read
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data
```

**Comment by wanghaoshuang** [comment]
清理/root/.cache/paddle/weights/MobileNetV1_pretrained.tar之后可以正常执行。
