### ISSUE TITLE
paddleDection数据集路径以及配置问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#3520]
2019-10-11 21:12:13,636-INFO: Found /Users/shuxsu/.cache/paddle/dataset/coco/train2017
2019-10-11 21:12:13,636-INFO: Found /Users/shuxsu/.cache/paddle/dataset/coco/val2017
2019-10-11 21:12:13,636-INFO: Found /Users/shuxsu/.cache/paddle/dataset/coco/annotations
Traceback (most recent call last):
File "train.py", line 284, in 
main()
File "train.py", line 165, in main
devices_num, FLAGS.dataset_dir)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/data_feed.py", line 139, in create_reader
my_source)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/reader.py", line 135, in create
return reader._make_reader(mode, my_source)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/reader.py", line 51, in _make_reader
sc = build_source(sc_conf)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/source/init.py", line 61, in build_source
return RoiDbSource(**args)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/source/roidb_source.py", line 63, in init
anno_file), 'invalid file[%s] for RoiDbSource' % (anno_file)
AssertionError: invalid file[/Users/shuxsu/.cache/paddle/dataset/coco/annotations/instances_train.json] for RoiDbSource
数据集是通过项目提供的labelme2coco.py将 labelme数据集转换的coco数据集

**Comment by SunAhong1993** [comment]
> 2019-10-11 21:12:13,636-INFO: Found /Users/shuxsu/.cache/paddle/dataset/coco/train2017
> 2019-10-11 21:12:13,636-INFO: Found /Users/shuxsu/.cache/paddle/dataset/coco/val2017
> 2019-10-11 21:12:13,636-INFO: Found /Users/shuxsu/.cache/paddle/dataset/coco/annotations
> Traceback (most recent call last):
> File "train.py", line 284, in
> main()
> File "train.py", line 165, in main
> devices_num, FLAGS.dataset_dir)
> File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/data_feed.py", line 139, in create_reader
> my_source)
> File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/reader.py", line 135, in create
> return reader._make_reader(mode, my_source)
> File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/reader.py", line 51, in _make_reader
> sc = build_source(sc_conf)
> File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/source/init.py", line 61, in build_source
> return RoiDbSource(**args)
> File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/data/source/roidb_source.py", line 63, in init
> anno_file), 'invalid file[%s] for RoiDbSource' % (anno_file)
> AssertionError: invalid file[/Users/shuxsu/.cache/paddle/dataset/coco/annotations/instances_train.json] for RoiDbSource
> 数据集是通过项目提供的labelme2coco.py将 labelme数据集转换的coco数据集

你好~ 使用labelme2coco.py生成的json文件命名为“instance_train.json”，而不是“instances_train.json”（多了一个s），将configure文件中的annotation路径修改为”annotations/instance_train.json“即可。
