### ISSUE TITLE
测试已经训练好的模型出现问题

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/models#3584]
错误信息
```
libprotobuf ERROR /home/teamcity/work/ef54dc8a5b211854/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: (cannot determine missing fields for lite message)
Traceback (most recent call last):
File "infer.py", line 319, in 
main()
File "infer.py", line 183, in main
checkpoint.load_checkpoint(exe, infer_prog, cfg.weights)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/utils/checkpoint.py", line 89, in load_checkpoint
fluid.io.load_persistables(exe, path, prog)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 755, in load_persistables
filename=filename)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 619, in load_vars
filename=filename)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 656, in load_vars
executor.run(load_prog)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 657, in run
use_program_cache=use_program_cache)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 755, in run
exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Call stacks:
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1774, in append_op
attrs=kwargs.get("attrs", None))
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 641, in load_vars
'file_path': os.path.join(load_dirname, new_var.name)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 619, in load_vars
filename=filename)
File "/Library/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 755, in load_persistables
filename=filename)
File "/Users/shuxsu/Downloads/models-develop/PaddleCV/PaddleDetection/ppdet/utils/checkpoint.py", line 89, in load_checkpoint
fluid.io.load_persistables(exe, path, prog)
File "infer.py", line 183, in main
checkpoint.load_checkpoint(exe, infer_prog, cfg.weights)
File "infer.py", line 319, in 
main()
C++ Call stacks:
Cannot parse tensor desc at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/tensor_util.cc:466]
PaddlePaddle Call Stacks:
0 0x1a26508f8cp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1 0x1a26508cbbp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2 0x1a27916e30p paddle::framework::TensorFromStream(std::1::basic_istream<char, std::1::char_traits >&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&) + 1248
3 0x1a27620b0fp paddle::framework::DeserializeFromStream(std::1::basic_istream<char, std::1::char_traits >&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 431
4 0x1a268791d1p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::LoadLodTensor(std::1::basic_istream<char, std::1::char_traits >&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*, paddle::framework::ExecutionContext const&) const + 97
5 0x1a26878a83p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 627
6 0x1a268787d0p std::1::function::func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&) + 32
7 0x1a278d52c5p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 485
8 0x1a278d5038p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 488
9 0x1a278d17f4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 324
10 0x1a2667e27fp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 319
11 0x1a2667dd2cp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > const&, bool) + 172
12 0x1a265706fdp void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_84, void, paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_84&&, void ()(paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope, int, bool, bool, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 301
13 0x1a264eda38p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
14 0x10b2cc10ap _PyCFunction_FastCallDict + 362
15 0x10b253171p _PyObject_FastCallKeywords + 385
16 0x10b3a1718p call_function + 392
17 0x10b39f175p _PyEval_EvalFrameDefault + 46837
18 0x10b3928c9p _PyEval_EvalCodeWithName + 425
19 0x10b3a1a8ap fast_function + 362
20 0x10b3a167cp call_function + 236
21 0x10b39f225p _PyEval_EvalFrameDefault + 47013
22 0x10b3928c9p _PyEval_EvalCodeWithName + 425
23 0x10b3a1a8ap fast_function + 362
24 0x10b3a167cp call_function + 236
25 0x10b39f175p _PyEval_EvalFrameDefault + 46837
26 0x10b3928c9p _PyEval_EvalCodeWithName + 425
27 0x10b3a1a8ap fast_function + 362
28 0x10b3a167cp call_function + 236
29 0x10b39f225p _PyEval_EvalFrameDefault + 47013
30 0x10b3928c9p _PyEval_EvalCodeWithName + 425
31 0x10b3a1a8ap fast_function + 362
32 0x10b3a167cp call_function + 236
33 0x10b39f225p _PyEval_EvalFrameDefault + 47013
34 0x10b3928c9p _PyEval_EvalCodeWithName + 425
35 0x10b3a1a8ap fast_function + 362
36 0x10b3a167cp call_function + 236
37 0x10b39f175p _PyEval_EvalFrameDefault + 46837
38 0x10b3a19dcp fast_function + 188
39 0x10b3a167cp call_function + 236
40 0x10b39f175p _PyEval_EvalFrameDefault + 46837
41 0x10b3a19dcp fast_function + 188
42 0x10b3a167cp call_function + 236
43 0x10b39f175p _PyEval_EvalFrameDefault + 46837
44 0x10b3928c9p _PyEval_EvalCodeWithName + 425
45 0x10b3eb55cp PyRun_FileExFlags + 252
46 0x10b3eaa34p PyRun_SimpleFileExFlags + 372
47 0x10b4117c6p Py_Main + 3734
48 0x10b242f59p main + 313
49 0x7fff715d73d5p start + 1
50 0x6p
```

**Comment by willthefrog** [comment]
已assign相关同学跟进。

**Comment by jerrywgz** [comment]
可以发下paddle版本吗

**Comment by shuxsu** [comment]
> 可以发下paddle版本吗

版本？  PaddlePaddle 1.5.2, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: OFF
    with_mkldnn: OFF
    with_python: ON

**Comment by shuxsu** [comment]
根据错误信息 我百度了找到了几篇文章  但是根据他相应的  还是没有解决。。。
文章链接给您  希望能尽早帮我解决这个问题  哭了
我是用笔记本的cpu进行测试的   模型是用工作站训练的
https://ai.baidu.com/forum/topic/show/956320
https://blog.csdn.net/c8241998/article/details/91975794
https://blog.csdn.net/qq_38604355/article/details/92817246
https://www.cnblogs.com/dzqiu/p/9518190.html

**Comment by jerrywgz** [comment]
我这边使用1.5.2 cpu版本的paddle https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/Tables.html#whl-release 测试yolo mask_rcnn的infer都是可以跑通的，可以使用上面这个链接里的paddle whl试下

**Comment by shuxsu** [comment]
我用gpu的可以跑通城但是没有结果 图片并没有分类 分割

**Comment by jerrywgz** [comment]
你跑的是哪个模型，是使用的你自己的数据还是coco数据？

**Comment by shuxsu** [comment]
跑的自己训练的模型  cityscape 数据集转换的coco数据集成训练后 进行测试

**Comment by qingqing01** [comment]
@jerrywgz  @shuxsu 是自己训练模型，从log来看是模型加载时出了问题，请确保config里模型路径 `weights`字段是正确的。

**Comment by shuxsu** [comment]
weights 路径绝对正确啊…

**Comment by shuxsu** [comment]
字段正确是指？

**Comment by jerrywgz** [comment]
可以先尝试在infer的时候将图片resize到训练的尺寸

**Comment by shuxsu** [comment]
> 可以先尝试在infer的时候将图片resize到训练的尺寸

图片并没有修改过  都是统一的cityscape数据集  而且 我用训练的图片 也并没有效果  同样报错

**Comment by jerrywgz** [comment]
你在训练的过程中应该有对输入图片做resize吧，比如[800,1333]这样的尺寸

**Comment by shuxsu** [comment]
> resize
代码我没有修改过。。。 就修改了一点配置文件和 coco_eval 那个类别对应的文件

**Comment by jerrywgz** [comment]
训练阶段PaddleDetection会默认对图片做resize操作，只是在配置文件中省略了这段配置，详细配置可以参考：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/config_example/mask_rcnn_r50_fpn_1x.yml#L330 而在infer阶段默认是不会做resize操作的，我的意思是可以尝试对infer的输入图片也添加resize的操作
resize相关代码可以参考：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/data/data_feed.py#L464

**Comment by shuxsu** [comment]
> 训练阶段PaddleDetection会默认对图片做resize操作，只是在配置文件中省略了这段配置，详细配置可以参考：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/docs/config_example/mask_rcnn_r50_fpn_1x.yml#L330 而在infer阶段默认是不会做resize操作的，我的意思是可以尝试对infer的输入图片也添加resize的操作
> resize相关代码可以参考：https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/PaddleDetection/ppdet/data/data_feed.py#L464

我用下载好的模型  jupyter里面能测试  终端就是会报错  什么原因呢

**Comment by shuxsu** [comment]
> 已assign相关同学跟进。

我最近提了好几个issues  一直没人回复 能帮忙推进一下吗
https://github.com/PaddlePaddle/models/issues/3681
https://github.com/PaddlePaddle/models/issues/3589#issuecomment-544223364
https://github.com/PaddlePaddle/models/issues/3589#issuecomment-544357297

**Comment by jerrywgz** [comment]
经过和用户的沟通，目前所遇到的问题做下总结：
1. 模型加载报bn参数不存在问题：由于models代码版本较老，处于未加入finetune功能的版本导致
2. 使用检测库提供脚本将数据转为coco格式后，训练仅有一个类的问题：经沟通发现原数据格式为cityscape格式，而检测库提供脚本为labelme格式，并不兼容cityscape格式，目前已经将问题修复并提pr，将转换脚本改名为x2coco.py https://github.com/PaddlePaddle/models/pull/3760/files
3. 训练参数问题：在对小数据集finetune时，将pretrain_weights设置为paddle release模型链接，并可以将迭代轮数降低；num_classes设置为（类别个数+背景类）
4. resize问题：maskrcnn中默认训练时resize到800，1333大小，infer时不对图片做resize，如果效果不够理想可以对sample_transform进行调整
