### ISSUE TITLE
generative_paddle run error

### ISSUE THREAD

**Issue by universea** [PaddlePaddle/models#3737]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  **import imp
stage 0
Traceback (most recent call last):
  File "network.py", line 529, in <module>
    train(config)
  File "network.py", line 480, in train
    optimizer.minimize(bow_loss)**
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-20>", line 2, in minimize
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 594, in minimize
    no_grad_set=no_grad_set)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/backward.py", line 578, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected x_dims[i] * expand_times[i] == out_dims[i], but received x_dims[i] * expand_times[i]:-500 != out_dims[i]:-1.
Each dimension size of Input(Out@GRAD) should be equal to multiplication of crroresponding dimension size of Input(X) and Attr(expand_times) value. at [/paddle/paddle/fluid/operators/expand_op.cc:153]
PaddlePaddle Call Stacks: 
0       0x7f9b41b3dc28p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f9b41b3df77p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f9b42186401p paddle::operators::ExpandGradOp::InferShape(paddle::framework::InferShapeContext*) const + 1425
3       0x7f9b41ca4d2ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f9b41be0afcp
5       0x7f9b41b6caf6p
6       0x55a5eecfa744p _PyMethodDef_RawFastCallKeywords + 596
7       0x55a5eecfa861p _PyCFunction_FastCallKeywords + 33
8       0x55a5eed666e8p _PyEval_EvalFrameDefault + 21240
9       0x55a5eecf9ccbp _PyFunction_FastCallKeywords + 251
10      0x55a5eed61806p _PyEval_EvalFrameDefault + 1046
11      0x55a5eecaa539p _PyEval_EvalCodeWithName + 761
12      0x55a5eecf9ef5p _PyFunction_FastCallKeywords + 805
13      0x55a5eed61806p _PyEval_EvalFrameDefault + 1046
14      0x55a5eecaa539p _PyEval_EvalCodeWithName + 761
15      0x55a5eecf9f57p _PyFunction_FastCallKeywords + 903
16      0x55a5eed628ccp _PyEval_EvalFrameDefault + 5340
17      0x55a5eecaa539p _PyEval_EvalCodeWithName + 761
18      0x55a5eecab635p _PyFunction_FastCallDict + 469
19      0x55a5eed63232p _PyEval_EvalFrameDefault + 7746
20      0x55a5eecaa81ap _PyEval_EvalCodeWithName + 1498
21      0x55a5eecab635p _PyFunction_FastCallDict + 469
22      0x55a5eed63232p _PyEval_EvalFrameDefault + 7746
23      0x55a5eecaa81ap _PyEval_EvalCodeWithName + 1498
24      0x55a5eecf9f57p _PyFunction_FastCallKeywords + 903
25      0x55a5eed61806p _PyEval_EvalFrameDefault + 1046
26      0x55a5eecaa539p _PyEval_EvalCodeWithName + 761
27      0x55a5eecf9ef5p _PyFunction_FastCallKeywords + 805
28      0x55a5eed61a93p _PyEval_EvalFrameDefault + 1699
29      0x55a5eecf9ccbp _PyFunction_FastCallKeywords + 251
30      0x55a5eed61806p _PyEval_EvalFrameDefault + 1046
31      0x55a5eecaa539p _PyEval_EvalCodeWithName + 761
32      0x55a5eecab424p PyEval_EvalCodeEx + 68
33      0x55a5eecab44cp PyEval_EvalCode + 28
34      0x55a5eedc0b74p
35      0x55a5eedcaeb1p PyRun_FileExFlags + 161
36      0x55a5eedcb0a3p PyRun_SimpleFileExFlags + 451
37      0x55a5eedcc195p
38      0x55a5eedcc2bcp _Py_UnixMain + 60
39      0x7f9b60115830p __libc_start_main + 240
40      0x55a5eed71062p

**Comment by wanghaoshuang** [comment]
可以使用[fluid.layers.print](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/control_flow_cn.html#print) API打印出exepand的输入，观察其shape是否满足要求。
expand API: https://www.paddlepaddle.org.cn/documentation/docs/en/1.5/api/layers/nn.html#expand

同时，可以用Print输出观察下expand op的反向输入

**Comment by cchan19** [comment]
same error. Does this program match the data of the baidu competition ? 
https://aistudio.baidu.com/aistudio/competition/detail/14

**Comment by cchan19** [comment]
> 可以使用[fluid.layers.print](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/control_flow_cn.html#print) API打印出exepand的输入，观察其shape是否满足要求。
> expand API: https://www.paddlepaddle.org.cn/documentation/docs/en/1.5/api/layers/nn.html#expand
> 
> 同时，可以用Print输出观察下expand op的反向输入

似乎还没到fluid.layers.print 这个API起作用的时候就报错了。
