### ISSUE TITLE
win10无法运行yolov3！

### ISSUE THREAD

**Issue by shengyuqing** [PaddlePaddle/models#3862]
首先是我的环境配置
1）PaddlePaddle版本：paddlepaddle-gpu，1.6.0.post107
2）使用GPU进行训练，CUDA10，cuDNN,7.3
3）系统环境：WIN10

跑官网下载的yolov3目标检测算法报错，报错信息：
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Found 2 CUDA devices.
W1103 20:15:19.473218 8236 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W1103 20:15:19.535706 8236 device_context.cc:243] device: 0, cuDNN Version: 7.3.
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
Load in 1 categories.
C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py:774: UserWarning: The following exception is not an EOF exception.
"The following exception is not an EOF exception.")
Traceback (most recent call last):
File "train.py", line 219, in
train(cfg)
File "train.py", line 180, in train
fetch_list=[v.name for v in fetch_list])
File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 775, in run
six.reraise(*sys.exc_info())
File "C:\Users\Admin\Anaconda3\lib\site-packages\six.py", line 693, in reraise
raise value
File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 770, in run
use_program_cache=use_program_cache)
File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 819, in _run_impl
program._compile(scope, self.place)
File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\compiler.py", line 392, in _compile
places=self._places)
File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\compiler.py", line 355, in _compile_data_parallel
self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: Windows not support stack backtrace yet.PaddleCheckError: Windows can support Single GPU only. at [D:\1.6.0\paddle\paddle\fluid\framework\parallel_executor.cc:417]

试了多次都不行，求助！

**Comment by heavengate** [comment]
```
paddle.fluid.core_avx.EnforceNotMet: Windows not support stack backtrace yet.PaddleCheckError: Windows can support Single GPU only. at 
```
由于nvidia nccl不支持Windows，因此Windows上只能跑单GPU，可以试下
```
set CUDA_VISIBLE_DEVICES=0
```
来设置单卡运行，另外，对应学习率需要调低一些，否则可能出nan

**Comment by zhaotun** [comment]
@heavengate  你好，我参考[这里](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification)在windows平台做图像分类的finetune训练，遇到了相同的问题
![image](https://user-images.githubusercontent.com/13940249/69709857-32b8c780-1139-11ea-90a2-1d5d308fec74.png)

机器有4个显卡，使用的命令是
```shell
python train.py --model=MobileNetV2_x2_0 --pretrained_model=pre_trained_model/MobileNetV2_x2_0_pretrained --batch_size=16 --total_images=14105 --class_dim=3 --image_shape=3,224,224 --model_save_dir=output/ --lr_strategy=piecewise_decay --lr=0.01
```
你提到设置单卡运行，具体在如何设置、在哪设置呢，谢谢。
