### ISSUE TITLE
在自己的数据集上通过 finetune 训练出来的图像分类模型，如何进行模型合并和测试？

### ISSUE THREAD

**Issue by zhaotun** [PaddlePaddle/models#4005]
你好，我是 paddle 新手，参考 [图像分类以及模型库](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification) 的内容，在自己的数据集上进行 finetune 训练图像分类模型，使用的命令是
```shell
python train.py --data_dir=data/Faces --model=MobileNetV1_x0_25 --pretrained_model=pre_trained_model/MobileNetV1_x0_25_pretrained --batch_size=16 --total_images=49779 
--class_dim=2 --image_shape=3,224,224 --model_save_dir=output/ --lr_strategy=piecewise_decay --lr=0.001
```
训练后在 output/MobileNetV1_x0_25 目录下得到了每个epoch保存的模型
![image](https://user-images.githubusercontent.com/13940249/69786466-74a74380-11f5-11ea-92e2-b3bad19b3766.png)
每个文件夹中有200多个文件
![image](https://user-images.githubusercontent.com/13940249/69786510-8d175e00-11f5-11ea-9b66-9adab6a7be20.png)
 
怎么把这些模型文件合并，转为`__model__` 文件呢？在 [#1022](https://github.com/PaddlePaddle/models/issues/1022) 看到一句 “可以先自行使用 fluid.io.save_inference_model保存，便有了__model__ 文件。”，但是 save_inference_model 函数的几个参数不知道怎么给啊，能不能给个完整的例子，谢谢！

**Comment by shippingwang** [comment]
你好，尝试下这个？
python infer.py \
       --model=model_name \
       --pretrained_model=${path_to_pretrain_model} \
       --save_inference=True
详见[注意事项](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9-1 )

**Comment by zhaotun** [comment]
@shippingwang  输入以下命令
```shell
python infer.py --model=MobileNetV1_x0_25 --pretrained_model=output/MobileNetV1_x0_25/6/ --save_inference=True
```
发生如下错误
```shell
F:\Paddle\models-develop\PaddleCV\image_classification>python infer.py --model=MobileNetV1_x0_25 --pretrained_model=output/MobileNetV1_x0_25/6/ --save_inference=True
-------------  Configuration Arguments -------------
                class_dim : 1000
                crop_size : 224
                 data_dir : ./data/ILSVRC2012/
               image_mean : [0.485, 0.456, 0.406]
              image_shape : 3,224,224
                image_std : [0.229, 0.224, 0.225]
            interpolation : None
               label_path : ./utils/tools/readable_label.txt
                    model : MobileNetV1_x0_25
             padding_type : SAME
         pretrained_model : output/MobileNetV1_x0_25/6/
          reader_buf_size : 2048
            reader_thread : 1
        resize_short_size : 256
           save_inference : 1
                     topk : 1
                  use_gpu : True
                   use_se : True
----------------------------------------------------
C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py:774: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "infer.py", line 138, in <module>
    main()
  File "infer.py", line 134, in main
    infer(args)
  File "infer.py", line 86, in infer
    exe.run(fluid.default_startup_program())
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 817, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 894, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2528, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\initializer.py", line 189, in __call__
    stop_gradient=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2410, in create_parameter
    initializer(param, self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layer_helper_base.py", line 330, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layer_helper.py", line 128, in append_bias_op
    attr=bias_attr, shape=size, dtype=input_var.dtype, is_bias=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layers\nn.py", line 397, in fc
    pre_activation = helper.append_bias_op(pre_bias, dim_start=num_flatten_dims)
  File "F:\Paddle\models-develop\PaddleCV\image_classification\models\mobilenet_v1.py", line 138, in net
    bias_attr=ParamAttr(name="fc7_offset"))
  File "infer.py", line 77, in infer
    out = model.net(input=image, class_dim=args.class_dim)
  File "infer.py", line 134, in main
    infer(args)
  File "infer.py", line 138, in <module>
    main()

----------------------
Error Message Summary:
----------------------
PaddleCheckError: cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability, error code : 30, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: unknown error at [D:\1.6.1\paddle\paddle\fluid\platform\gpu_info.cc:84]
  [operator < fill_constant > error]
```

**Comment by shippingwang** [comment]
注意指定 class_dim=2

**Comment by zhaotun** [comment]
@shippingwang  指定 class_dim = 2 后，可以了，谢谢！
