### ISSUE TITLE
GoogLeNet模型训练完成后读取参数出现问题

### ISSUE THREAD

**Issue by IWQOS-ASTBAR** [PaddlePaddle/models#4039]
读取其他模型的参数均没有问题，但GoogLeNet出现问题：Traceback (most recent call last):
  File "D:/python_adver/attack_code/acc.py", line 135, in <module>
    out = fluid.layers.softmax(out_logits)
  File "D:\python_adver\attack_code\venv\lib\site-packages\paddle\fluid\layers\nn.py", line 1983, in softmax
    "use_cudnn": use_cudnn})
  File "D:\python_adver\attack_code\venv\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "D:\python_adver\attack_code\venv\lib\site-packages\paddle\fluid\framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\python_adver\attack_code\venv\lib\site-packages\paddle\fluid\framework.py", line 1095, in __init__
    "not suprt args type , should be[ string_type, binary_type, Varibale]"
ValueError: not suprt args type , should be[ string_type, binary_type, Varibale]

**Comment by IWQOS-ASTBAR** [comment]
可能是模型问题，如果是的话请尽快调整

**Comment by lea4n** [comment]
> 可能是模型问题，如果是的话请尽快调整

请提供环境和版本信息，os／py／paddle，谢谢。

**Comment by IWQOS-ASTBAR** [comment]
os:win10+pycharm
python:3.7
paddle:1.6训练模型，1.5读取模型

**Comment by shippingwang** [comment]
为什么要1.6训练模型，之后用1.5读取模型呢？
这里的读取是指加载保存下来的参数么？

**Comment by IWQOS-ASTBAR** [comment]
给的train.py文件只能在1.6版本以上才能运行
读取指的是加载保存下来的参数
因为在做AI安全对抗比赛，这个比赛只能用1.5版本
其他模型参数均可以成功加载，但GooleNet不行，可能是版本间api的兼容性问题
有办法处理吗？

**Comment by lanxianghit** [comment]
> 
> 
> 给的train.py文件只能在1.6版本以上才能运行
> 读取指的是加载保存下来的参数
> 因为在做AI安全对抗比赛，这个比赛只能用1.5版本
> 其他模型参数均可以成功加载，但GooleNet不行，可能是版本间api的兼容性问题
> 有办法处理吗？

在版本升级过程中会尽量保证向前兼容（即基于老版本写的代码可以在新版本上正确运行），但无法完全保证向后兼容，比如这里提到的使用1.6训练，但使用1.5进行加载的情况。

针对您目前参加的比赛只能使用1.5版本的情况，不知道时间方面是否允许重新训练模型？如果可以，建议从PaddlePaddle/models repo中clone代码后切换到“release/1.5”分支，使用基于1.5版本的模型代码重新训练模型，这样可以保证使用1.5版本进行加载的正确性。
![图片](https://user-images.githubusercontent.com/47554610/70587515-1458ce80-1c05-11ea-90b5-b0e3e537f28c.png)

**Comment by IWQOS-ASTBAR** [comment]
ok收到，我试下，如果不行，再来留言，感谢

**Comment by IWQOS-ASTBAR** [comment]
还是没法加载参数........
![image](https://user-images.githubusercontent.com/58623947/70615014-91f0fe80-1c46-11ea-92c0-345f2983e3dd.png)
使用1.5版本进行训练的，训练命令如下：
python -m paddle.distributed.launch train.py \
	--model=GoogleNet \
	--batch_size=256 \
	--total_images=12000 \
	--class_dim=121 \
	--image_shape=3,224,224 \
	--model_save_dir=output/ \
	--with_mem_opt=True \
	--lr_strategy=cosine_decay \
	--lr=0.01 \
	--num_epochs=200 \
	--checkpoint=output/GoogleNet/199/ \
	--l2_decay=1e-4

**Comment by lanxianghit** [comment]
> 
> 
> 还是没法加载参数........
> ![image](https://user-images.githubusercontent.com/58623947/70615014-91f0fe80-1c46-11ea-92c0-345f2983e3dd.png)
> 使用1.5版本进行训练的，训练命令如下：
> python -m paddle.distributed.launch train.py
> --model=GoogleNet
> --batch_size=256
> --total_images=12000
> --class_dim=121
> --image_shape=3,224,224
> --model_save_dir=output/
> --with_mem_opt=True
> --lr_strategy=cosine_decay
> --lr=0.01
> --num_epochs=200
> --checkpoint=output/GoogleNet/199/
> --l2_decay=1e-4

@shippingwang @heavengate 辛苦再帮忙跟进一下吧
