### ISSUE TITLE
PaddleDetection Retinanet 评估失败 Cannot find fetched variable(im_id)

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/models#4127]
软硬件环境：GPU P4, CUDA7.0; CUDNN9.0
代码版本 paddleDetection（ commit_id d7fcd54d7b038823ae0938ea48242cd38b7ec942）
paddle 1.6.2
背景：将异步读取的pyreader改为同步feeder读取
```python
`def eval_run_feeder(exe, compile_program, reader, feeder, keys, values, cls):
    """
    Run evaluation program, return program outputs.
    """
    iter_id = 0
    results = []
    if len(cls) != 0:
        values = []
        for i in range(len(cls)):
            _, accum_map = cls[i].get_map_var()
            cls[i].reset(exe)
            values.append(accum_map)
    print("@@@@@@values", values)
    images_num = 0
    start_time = time.time()
    has_bbox = 'bbox' in keys


    for it, data in enumerate(reader()):
        print("data",data)
        outs = exe.run(compile_program,
                       feed=feeder.feed(data),
                       fetch_list=values,
                       return_numpy=False)

        res = {
            k: (np.array(v), v.recursive_sequence_lengths())
            for k, v in zip(keys, outs)
        }
        results.append(res)
        if iter_id % 100 == 0:
            logger.info('Test iter {}'.format(iter_id))
        iter_id += 1
        images_num += len(res['bbox'][1][0]) if has_bbox else 1


    end_time = time.time()
    fps = images_num / (end_time - start_time)
    if has_bbox:
        logger.info('Total number of images: {}, inference time: {} fps.'.
                    format(images_num, fps))
    else:
        logger.info('Total iteration: {}, inference time: {} batch/s.'.format(
            images_num, fps))

    return results
`
```

**报错如下**：
```shell
`1225 12:21:15.713791 20964 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1225 12:21:15.724485 20964 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1225 12:21:15.738996 20964 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train_feeder.py", line 374, in <module>
    main()
  File "tools/train_feeder.py", line 299, in main
    eval_keys, eval_values, eval_cls)
  File "tools/train_feeder.py", line 79, in eval_run_feeder
    return_numpy=False)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::details::FastThreadedSSAGraphExecutor::InsertFetchOps(std::vector<std::string, std::allocator<std::string> > const&, std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*, std::unordered_map<std::string, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> >, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> > > > >*, std::unordered_map<paddle::framework::details::OpHandleBase*, std::atomic<int>, std::hash<paddle::framework::details::OpHandleBase*>, std::equal_to<paddle::framework::details::OpHandleBase*>, std::allocator<std::pair<paddle::framework::details::OpHandleBase* const, std::atomic<int> > > >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*)
3   paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
5   paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
6   paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)

----------------------
Error Message Summary:
----------------------
Error: Cannot find fetched variable(im_id).(Perhaps the main_program is not set to ParallelExecutor) at (/paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:145)`
```

**Comment by baiyfbupt** [comment]
```shell
Error: Cannot find fetched variable(im_id).(Perhaps the main_program is not set to ParallelExecutor) at (/paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:145)`
```
这个报错信息是说program中找不到fetch_list写的`im_id`这个Variable所以无法fetch，建议检查一下定义的输入data层`fluid.layers.data或fluid.data`有没有写这个placeholder

**Comment by ellinyang** [comment]
> 这个报错信息是说program中找不到fetch_list写的`im_id`这个Variable所以无法fetch，建议检查一下定义的输入data层`fluid.layers.data`

我的理解是 fetch_list和模型输出有关，为何和输入data层有关？
另外，请问为何同样的program,  pyreader输入，就能找到fetch_list写的`im_id`，不报错；仅改写了一下data_feed，就报错了。（data_reader也一样）

**Comment by baiyfbupt** [comment]
> 我的理解是 fetch_list和模型输出有关，为何和输入data层有关？
> 另外，请问为何同样的program, pyreader输入，就能找到fetch_list写的`im_id`，不报错；仅改写了一下data_feed，就报错了。（data_reader也一样）

hi, fetch的不仅可以是模型的输出，也可以是program中的任何variable，包括输入data
根据你使用的代码版本`im_id`是网络的一个feed data: [im_id定义](https://github.com/PaddlePaddle/models/blob/d7fcd54d7b038823ae0938ea48242cd38b7ec942/PaddleCV/PaddleDetection/ppdet/modeling/model_input.py#L28)，所以建议还是检查一下改py_reader为同步reader以后有没有给这个`im_id`增加相应的fluid.layers.data接口

**Comment by baiyfbupt** [comment]
也可以用下面的方式将网络中所有的variable打印出来看一下，对比一下改写py_reader后是否比之前缺失了`im_id`这个variable
需要注意的是，这里的program应该是一个原始program, 不要经过compile
```python
# get all variables
all_vars = []
for v in program.list_vars():
    all_vars.append((v.name, v.shape))
print("="*50+"all_vars"+"="*50)
print(all_vars)
```

**Comment by ellinyang** [comment]
> 也可以用下面的方式将网络中所有的variable打印出来看一下，对比一下改写py_reader后是否比之前缺失了`im_id`这个variable
> 需要注意的是，这里的program应该是一个原始program, 不要经过compile
> 
> ```python
> # get all variables
> all_vars = []
> for v in program.list_vars():
>     all_vars.append((v.name, v.shape))
> print("="*50+"all_vars"+"="*50)
> print(all_vars)
> ```

打印了。program里有“im_id”这个variable，且fetch_list里im_id  的persistable设置为True后，依旧报错。


```extra_key name: "im_id"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 0
  }
}
persistable: true

extra_key name: "im_shape"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 3
    }
    lod_level: 0
  }
}
persistable: true```

`I1229 03:18:27.945735 29116 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1229 03:18:27.979439 29116 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1229 03:18:28.037343 29116 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1229 03:18:28.062338 29116 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
2019-12-29 03:18:28,863-INFO: iter: 0, lr: 0.006667, 'loss_bbox': '0.165303', 'loss_rpn_cls': '0.014365', 'loss_rpn_bbox': '0.005772', 'loss_cls': '0.978696', 'loss': '1.164135', time: 0.033, eta: 0:00:59
2019-12-29 03:18:37,011-INFO: Save model to output/work_dirs/10.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!!!!values!!!! [u'multiclass_nms_0.tmp_0', u'im_info', u'im_id', u'im_shape']
I1229 03:18:37.858000 29116 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1229 03:18:37.868824 29116 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1229 03:18:37.879050 29116 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1229 03:18:37.886502 29116 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train_feeder.py", line 334, in <module>
    main()
  File "tools/train_feeder.py", line 287, in main
    eval_keys, eval_values, eval_cls)
  File "tools/train_feeder.py", line 80, in eval_run_feeder
    return_numpy=False)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::details::FastThreadedSSAGraphExecutor::InsertFetchOps(std::vector<std::string, std::allocator<std::string> > const&, std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*, std::unordered_map<std::string, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> >, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::vector<paddle::framework::details::VarHandleBase*, std::allocator<paddle::framework::details::VarHandleBase*> > > > >*, std::unordered_map<paddle::framework::details::OpHandleBase*, std::atomic<int>, std::hash<paddle::framework::details::OpHandleBase*>, std::equal_to<paddle::framework::details::OpHandleBase*>, std::allocator<std::pair<paddle::framework::details::OpHandleBase* const, std::atomic<int> > > >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*, std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> >*)
3   paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
4   paddle::framework::details::ScopeBufferedMonitor::Apply(std::function<void ()> const&, bool)
5   paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)
6   paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&)

----------------------
Error Message Summary:
----------------------
Error: Cannot find fetched variable(im_id).(Perhaps the main_program is not set to ParallelExecutor) at (/paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:145)`

**Comment by ellinyang** [comment]
做了一组实验，定位到两个问题
1.paddle版本的原因，paddle1.5.1可以评估，但都评估值一直为0，或接近0的值，而1.6.2是直接报错。
2.fluid.compiler.CompiledProgram 的问题，因为是在训练时评估，对eval_prog也编译了一下，导致评估结果一直很差；若不编译，直接用eval_prog评估效果正常，不知是和原因？

```# compile program for multi-devices
    build_strategy = fluid.BuildStrategy()
    build_strategy.memory_optimize = False
    build_strategy.enable_inplace = False
    sync_bn = getattr(model.backbone, 'norm_type', None) == 'sync_bn'
    #sync_bn = False
    # only enable sync_bn in multi GPU devices
    build_strategy.sync_batch_norm = sync_bn and devices_num > 1 and cfg.use_gpu
    train_compile_program = fluid.compiler.CompiledProgram(
        train_prog).with_data_parallel(
            loss_name=loss.name, build_strategy=build_strategy)
    if FLAGS.eval:
        # eval_compile_program = fluid.compiler.CompiledProgram(eval_prog)
        eval_compile_program = eval_prog```

**Comment by qingqing01** [comment]
@ellinyang 

1. im_id之所以要fetch，是使用COCO API评估mAP指标时需要。
2. 你去掉py_reader，使用feeder.feed是如何修改的代码？ 可以贴下git diff吗？
3.  使用py_reader时，eval_program，依然使用了 compile_program，代码： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/tools/train.py#L192 
4. PaddleDetection已搬到到 https://github.com/PaddlePaddle/PaddleDetection ，代码也持续在 该repo更新，可以在该repo中提问，我们会及时回复。

**Comment by ellinyang** [comment]
> @ellinyang
> 
> 1. im_id之所以要fetch，是使用COCO API评估mAP指标时需要。
> 2. 你去掉py_reader，使用feeder.feed是如何修改的代码？ 可以贴下git diff吗？
> 3. 使用py_reader时，eval_program，依然使用了 compile_program，代码： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/tools/train.py#L192
> 4. PaddleDetection已搬到到 https://github.com/PaddlePaddle/PaddleDetection ，代码也持续在 该repo更新，可以在该repo中提问，我们会及时回复。


1.理解。所以奇怪为何在1.6.2里一直报错,提示找不到 im_id;
2.3.4 train_feeder.py文件如下。几乎复用原始的train.py代码。但对eval_program编不编译会直接导致评估效果。

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import time
import numpy as np
import datetime
from collections import deque


def set_paddle_flags(**kwargs):
    for key, value in kwargs.items():
        if os.environ.get(key, None) is None:
            os.environ[key] = str(value)


# NOTE(paddle-dev): All of these flags should be set before 
# `import paddle`. Otherwise, it would not take any effect.
set_paddle_flags(
    FLAGS_eager_delete_tensor_gb=0,  # enable GC to save memory
)

from paddle import fluid

from ppdet.core.workspace import load_config, merge_config, create
from ppdet.data.data_feed import create_reader

from ppdet.utils.eval_utils import parse_fetches, eval_run, eval_results
from ppdet.utils.stats import TrainingStats
from ppdet.utils.cli import ArgsParser
from ppdet.utils.check import check_gpu
import ppdet.utils.checkpoint as checkpoint
from ppdet.modeling.model_input import create_feed

import logging
FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
logging.basicConfig(level=logging.INFO, format=FORMAT)
logger = logging.getLogger(__name__)


def eval_run_feeder(exe, compile_program, reader, feeder, keys, values, cls):
    """
    Run evaluation program, return program outputs.
    """
    iter_id = 0
    results = []
    if len(cls) != 0:
        values = []
        for i in range(len(cls)):
            _, accum_map = cls[i].get_map_var()
            cls[i].reset(exe)
            values.append(accum_map)
    print("!!!!values!!!!", values)
    images_num = 0
    start_time = time.time()
    has_bbox = 'bbox' in keys


    for it, data in enumerate(reader()):
        outs = exe.run(compile_program,
                       feed=feeder.feed(data),
                       fetch_list=values,
                       return_numpy=False)

        res = {
            k: (np.array(v), v.recursive_sequence_lengths())
            for k, v in zip(keys, outs)
        }
        results.append(res)
        if iter_id % 100 == 0:
            logger.info('Test iter {}'.format(iter_id))
        iter_id += 1
        images_num += len(res['bbox'][1][0]) if has_bbox else 1


    end_time = time.time()
    fps = images_num / (end_time - start_time)
    if has_bbox:
        logger.info('Total number of images: {}, inference time: {} fps.'.
                    format(images_num, fps))
    else:
        logger.info('Total iteration: {}, inference time: {} batch/s.'.format(
            images_num, fps))

    return results



def main():
    cfg = load_config(FLAGS.config)
    #
    # import pdb
    # pdb.set_trace()
    if 'architecture' in cfg:
        main_arch = cfg.architecture
    else:
        raise ValueError("'architecture' not specified in config file.")

    merge_config(FLAGS.opt)
    if 'log_iter' not in cfg:
        cfg.log_iter = 20

    # check if set use_gpu=True in paddlepaddle cpu version
    check_gpu(cfg.use_gpu)

    if cfg.use_gpu:
        devices_num = fluid.core.get_cuda_device_count()
    else:
        devices_num = int(os.environ.get('CPU_NUM', 1))

    if 'train_feed' not in cfg:
        train_feed = create(main_arch + 'TrainFeed')
    else:
        train_feed = create(cfg.train_feed)

    if FLAGS.eval:
        if 'eval_feed' not in cfg:
            eval_feed = create(main_arch + 'EvalFeed')
        else:
            eval_feed = create(cfg.eval_feed)

    place = fluid.CUDAPlace(0) if cfg.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)

    lr_builder = create('LearningRate')
    optim_builder = create('OptimizerBuilder')

    # build program
    startup_prog = fluid.Program()
    train_prog = fluid.Program()
    with fluid.program_guard(train_prog, startup_prog):
        with fluid.unique_name.guard():
            model = create(main_arch)
            _, feed_vars = create_feed(train_feed, use_pyreader=False)

            # import pdb
            # pdb.set_trace()
            train_fetches = model.train(feed_vars)
            loss = train_fetches['loss']
            lr = lr_builder()
            optimizer = optim_builder(lr)
            optimizer.minimize(loss)

    train_reader = create_reader(train_feed, cfg.max_iters * devices_num,
                                 FLAGS.dataset_dir)

    train_feeder = fluid.DataFeeder(place=place, feed_list=feed_vars.values())

    # for block in train_prog.blocks:
    #     print("train_program var:{}".format(block.vars))

    # parse train fetches
    train_keys, train_values, _ = parse_fetches(train_fetches)
    train_values.append(lr)

    if FLAGS.eval:
        eval_prog = fluid.Program()
        with fluid.program_guard(eval_prog, startup_prog):
            with fluid.unique_name.guard():
                model = create(main_arch)

                _, feed_vars = create_feed(eval_feed, use_pyreader=False)
                fetches = model.eval(feed_vars)
        eval_prog = eval_prog.clone(True)


        eval_reader = create_reader(eval_feed, args_path=FLAGS.dataset_dir)

        eval_feeder = fluid.DataFeeder(place=place, feed_list=feed_vars.values())


        # parse eval fetches
        extra_keys = []
        if cfg.metric == 'COCO':
            extra_keys = ['im_info', 'im_id', 'im_shape']
        if cfg.metric == 'VOC':
            extra_keys = ['gt_box', 'gt_label', 'is_difficult']
        eval_keys, eval_values, eval_cls = parse_fetches(fetches, eval_prog,
                                                         extra_keys)

        # all_vars = []
        # for v in eval_prog.list_vars():
        #     all_vars.append((v.name, v.shape))
        # print("=" * 50 + "all_vars" + "=" * 50)
        # print(all_vars)

    # compile program for multi-devices
    build_strategy = fluid.BuildStrategy()
    build_strategy.memory_optimize = False
    build_strategy.enable_inplace = False
    sync_bn = getattr(model.backbone, 'norm_type', None) == 'sync_bn'
    #sync_bn = False
    # only enable sync_bn in multi GPU devices
    build_strategy.sync_batch_norm = sync_bn and devices_num > 1 and cfg.use_gpu
    train_compile_program = fluid.compiler.CompiledProgram(
        train_prog).with_data_parallel(
            loss_name=loss.name, build_strategy=build_strategy)
    if FLAGS.eval:
        # eval_compile_program = fluid.compiler.CompiledProgram(
        #     eval_prog).with_data_parallel(
        #     share_vars_from=train_compile_program)
        # eval_compile_program = fluid.compiler.CompiledProgram(eval_prog)
        eval_compile_program = eval_prog

    exe.run(startup_prog)

    fuse_bn = getattr(model.backbone, 'norm_type', None) == 'affine_channel'
    # fuse_bn = False

    start_iter = 0
    if FLAGS.resume_checkpoint:
        checkpoint.load_checkpoint(exe, train_prog, FLAGS.resume_checkpoint)
        start_iter = checkpoint.global_step()

        logger.info("resume_checkpoint start iter:{}".format(start_iter))
    elif cfg.pretrain_weights and fuse_bn:
        checkpoint.load_and_fusebn(exe, train_prog, cfg.pretrain_weights)
    elif cfg.pretrain_weights:
        checkpoint.load_pretrain(exe, train_prog, cfg.pretrain_weights)

    # whether output bbox is normalized in model output layer
    is_bbox_normalized = False
    if hasattr(model, 'is_bbox_normalized') and \
            callable(model.is_bbox_normalized):
        is_bbox_normalized = model.is_bbox_normalized()

    # if map_type not set, use default 11point, only use in VOC eval
    map_type = cfg.map_type if 'map_type' in cfg else '11point'

    train_stats = TrainingStats(cfg.log_smooth_window, train_keys)
    #train_pyreader.start()
    start_time = time.time()
    end_time = time.time()

    cfg_name = os.path.basename(FLAGS.config).split('.')[0]
    save_dir = os.path.join(cfg.save_dir, FLAGS.work_name)
    time_stat = deque(maxlen=cfg.log_iter)
    best_box_ap_list = [0.0, 0]  #[map, iter]

    max_iter = cfg.max_iters
    for it, data in enumerate(train_reader()):
        it = it + start_iter
        if it > max_iter:
            break
        start_time = end_time
        end_time = time.time()
        time_stat.append(end_time - start_time)
        time_cost = np.mean(time_stat)
        eta_sec = (cfg.max_iters - it) * time_cost
        eta = str(datetime.timedelta(seconds=int(eta_sec)))

        outs = exe.run(train_compile_program,
                       feed=train_feeder.feed(data),
                       fetch_list=train_values,
                       return_numpy=False)
        # outs = exe.run(train_compile_program, fetch_list=train_values)
        stats = {k: np.array(v).mean() for k, v in zip(train_keys, outs[:-1])}
        train_stats.update(stats)
        logs = train_stats.log()
        if it % cfg.log_iter == 0:
            strs = 'iter: {}, lr: {:.6f}, {}, time: {:.3f}, eta: {}'.format(
                it, np.mean(outs[-1]), logs, time_cost, eta)
            logger.info(strs)

        if it > 0 and it % cfg.snapshot_iter == 0 or it == cfg.max_iters - 1:
            save_name = str(it) if it != cfg.max_iters - 1 else "model_final"
            checkpoint.save(exe, train_prog, os.path.join(save_dir, save_name))

            if FLAGS.eval:
                # evaluation
                results = eval_run_feeder(exe, eval_compile_program, eval_reader, eval_feeder,
                                   eval_keys, eval_values, eval_cls)
                resolution = None
                if 'mask' in results[0]:
                    resolution = model.mask_head.resolution
                box_ap_stats = eval_results(
                    results, eval_feed, cfg.metric, cfg.num_classes, resolution,
                    is_bbox_normalized, FLAGS.output_eval, map_type)
                if box_ap_stats[0] > best_box_ap_list[0]:
                    best_box_ap_list[0] = box_ap_stats[0]
                    best_box_ap_list[1] = it
                    checkpoint.save(exe, train_prog,
                                    os.path.join(save_dir, "best_model"))
                logger.info("Best test box ap: {}, in iter: {}".format(
                    best_box_ap_list[0], best_box_ap_list[1]))



if __name__ == '__main__':
    parser = ArgsParser()
    parser.add_argument(
        "-r",
        "--resume_checkpoint",
        default=None,
        type=str,
        help="Checkpoint path for resuming training.")
    parser.add_argument(
        "--eval",
        action='store_true',
        default=False,
        help="Whether to perform evaluation in train")
    parser.add_argument(
        "--output_eval",
        default=None,
        type=str,
        help="Evaluation directory, default is current directory.")
    parser.add_argument(
        "-d",
        "--dataset_dir",
        default=None,
        type=str,
        help="Dataset path, same as DataFeed.dataset.dataset_dir")
    parser.add_argument(
        "--work_name",
        default="work_dirs",
        type=str,
        help="Dataset path, same as DataFeed.dataset.dataset_dir")
    FLAGS = parser.parse_args()
    main()
```

**Comment by jerrywgz** [comment]
im_id 这个var在评估过程中不作为网络中任何op的输入输出的，因此在构图的时候不会将im_id加进来。之所以用pyreader可以是因为，pyreader的逻辑是将reader作为一个op嵌入到网络中，这样im_id就成了这个‘reader’op的输入。你这边如果想用compile_program+data_feeder的话，在网络的任意位置（比如ppdet/modeling/architectures/retinanet.py）加上tmp=feed_vars['im_id'] + 1 这样的操作就可以暂时解决这个问题，我在1.6.1上是验证可以的
