### ISSUE TITLE
PaddleDetection快速开始tools/train.py 报错CUDNN_STATUS_BAD_PARAM 

### ISSUE THREAD

**Issue by mikeFang1986** [PaddlePaddle/models#4145]
系统：ubuntu16.04
CUDA Version 10.0.130
CUDnn 7.4.2
Nccl  2.4.8
python 3.7

python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --use_tb=True --tb_log_dir=tb_fruit_dir/scalar --eval
运行时，报错如下：
use_gpu: true
weights: output/yolov3_mobilenet_v1_fruit/best_model

2019-12-30 17:02:35,740-INFO: places would be ommited when DataLoader is not iterable
W1230 17:02:36.778067  9089 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W1230 17:02:36.781242  9089 device_context.cc:244] device: 0, cuDNN Version: 7.4.
W1230 17:02:36.781275  9089 device_context.cc:270] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.4, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
2019-12-30 17:02:37,792-INFO: Found /home/css/.cache/paddle/weights/yolov3_mobilenet_v1
2019-12-30 17:02:37,792-INFO: Loading parameters from /home/css/.cache/paddle/weights/yolov3_mobilenet_v1...
2019-12-30 17:02:37,797-INFO: In load_params, ignore yolo_output.0.conv.weights
2019-12-30 17:02:37,797-INFO: In load_params, ignore yolo_output.0.conv.bias
2019-12-30 17:02:37,798-INFO: In load_params, ignore yolo_output.1.conv.weights
2019-12-30 17:02:37,798-INFO: In load_params, ignore yolo_output.1.conv.bias
2019-12-30 17:02:37,800-INFO: In load_params, ignore yolo_output.2.conv.weights
2019-12-30 17:02:37,800-INFO: In load_params, ignore yolo_output.2.conv.bias
2019-12-30 17:02:39,540-INFO: places would be ommited when DataLoader is not iterable
I1230 17:02:39.740296  9089 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1230 17:02:39.834806  9089 graph_pattern_detector.cc:96] ---  detected 1 subgraphs
I1230 17:02:39.953145  9089 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1230 17:02:40.066726  9089 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1230 17:02:40.164924  9089 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 340, in <module>
    main()
  File "tools/train.py", line 246, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::details::ComputationOpHandle::RunImpl()
8   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
10  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
11  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
12  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 4363, in batch_norm
    attrs=attrs)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 97, in _conv_norm
    moving_variance_name=bn_name + '_variance')
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 157, in __call__
    input, 3, int(32 * scale), 2, 1, name=self.prefix_name + "conv1")
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 56, in build
    body_feats = self.backbone(im)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 80, in train
    return self.build(feed_vars, mode='train')
  File "tools/train.py", line 128, in main
    train_fetches = model.train(feed_vars)
  File "tools/train.py", line 340, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: CUDNN_STATUS_BAD_PARAM at (/paddle/paddle/fluid/operators/batch_norm_op.cu:183)
  [operator < batch_norm > error]

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
Process Process-6:
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/dataset.py", line 48, in reset
    (self.__class__.__name__))
NotImplementedError: MappedDataset.reset not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/dataset.py", line 48, in reset
    (self.__class__.__name__))
NotImplementedError: BatchedDataset.reset not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/transform/parallel_map.py", line 153, in _consume
    outq.put(result)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/transform/shared_queue/queue.py", line 71, in put
    super(SharedQueue, self).put(buff, **kwargs)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/queues.py", line 89, in put
    self._notempty.notify()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/threading.py", line 352, in notify
    waiter.release()
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/data/transform/parallel_map.py", line 226, in _reader_exit
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/util.py", line 337, in _exit_function
    _run_finalizers()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/multiprocessing/queues.py", line 192, in _finalize_join
    thread.join()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

python ppdet/modeling/tests/test_architectures.py，确认通过

**Comment by mikeFang1986** [comment]
修改了export CUDA_VISIBLE_DEVICES=0,1,2,3，可以训练200次，后来还是报错了，
2019-12-31 09:50:26,863-INFO: iter: 0, lr: 0.000000, 'loss': '25742.060547', time: 0.241, eta: 1:20:28
2019-12-31 09:50:34,725-INFO: iter: 20, lr: 0.000002, 'loss': '2238.673340', time: 1.260, eta: 6:59:39
2019-12-31 09:50:39,574-INFO: iter: 40, lr: 0.000004, 'loss': '51.575729', time: 0.260, eta: 1:26:23
2019-12-31 09:50:46,307-INFO: iter: 60, lr: 0.000006, 'loss': '32.693623', time: 0.337, eta: 1:51:50
2019-12-31 09:50:53,085-INFO: iter: 80, lr: 0.000008, 'loss': '22.929565', time: 0.325, eta: 1:48:02
2019-12-31 09:50:57,432-INFO: iter: 100, lr: 0.000010, 'loss': '25.804705', time: 0.231, eta: 1:16:31
2019-12-31 09:51:05,188-INFO: iter: 120, lr: 0.000010, 'loss': '23.545839', time: 0.388, eta: 2:08:29
2019-12-31 09:51:11,555-INFO: iter: 140, lr: 0.000010, 'loss': '22.209671', time: 0.314, eta: 1:43:52
2019-12-31 09:51:15,616-INFO: iter: 160, lr: 0.000010, 'loss': '22.101305', time: 0.207, eta: 1:08:34
2019-12-31 09:51:22,481-INFO: iter: 180, lr: 0.000010, 'loss': '21.038012', time: 0.343, eta: 1:53:26
2019-12-31 09:51:29,135-INFO: iter: 200, lr: 0.000010, 'loss': '18.767527', time: 0.312, eta: 1:42:51
2019-12-31 09:51:29,207-INFO: Save model to output/yolov3_mobilenet_v1_fruit/200.
I1231 09:51:29.724607 14873 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I1231 09:51:29.730973 14873 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I1231 09:51:29.735814 14873 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1231 09:51:29.739861 14873 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 340, in <module>
    main()
  File "tools/train.py", line 271, in main
    eval_keys, eval_values, eval_cls)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/utils/eval_utils.py", line 128, in eval_run
    return_numpy=False)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::details::ComputationOpHandle::RunImpl()
8   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
10  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
11  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
12  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/css/anaconda3/envs/fl_pp_env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 4363, in batch_norm
    attrs=attrs)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 97, in _conv_norm
    moving_variance_name=bn_name + '_variance')
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 157, in __call__
    input, 3, int(32 * scale), 2, 1, name=self.prefix_name + "conv1")
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 56, in build
    body_feats = self.backbone(im)
  File "/home/css/work/fl/pp_env/fast_rcnn/PaddleDetection/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 83, in eval
    return self.build(feed_vars, mode='test')
  File "tools/train.py", line 149, in main
    fetches = model.eval(feed_vars)
  File "tools/train.py", line 340, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: CUDNN_STATUS_BAD_PARAM at (/paddle/paddle/fluid/operators/batch_norm_op.cu:134)
  [operator < batch_norm > error]
terminate called without an active exception
W1231 09:51:30.091799 14937 init.cc:206] *** Aborted at 1577757090 (unix time) try "date -d @1577757090" if you are using GNU date ***
W1231 09:51:30.097236 14937 init.cc:206] PC: @                0x0 (unknown)
W1231 09:51:30.097362 14937 init.cc:206] *** SIGABRT (@0x3e800003a19) received by PID 14873 (TID 0x7faea8ffd700) from PID 14873; stack trace: ***
W1231 09:51:30.100087 14937 init.cc:206]     @     0x7faf5a5b0390 (unknown)
W1231 09:51:30.102305 14937 init.cc:206]     @     0x7faf5a20a428 gsignal
W1231 09:51:30.104569 14937 init.cc:206]     @     0x7faf5a20c02a abort
W1231 09:51:30.106323 14937 init.cc:206]     @     0x7faf4201d81c __gnu_cxx::__verbose_terminate_handler()
W1231 09:51:30.107872 14937 init.cc:206]     @     0x7faf4201bf19 __cxxabiv1::__terminate()
W1231 09:51:30.109581 14937 init.cc:206]     @     0x7faf4201bf4f std::terminate()
W1231 09:51:30.111191 14937 init.cc:206]     @     0x7faf4201bc2c __gxx_personality_v0
W1231 09:51:30.112466 14937 init.cc:206]     @     0x7faf41f68bc8 _Unwind_ForcedUnwind_Phase2
W1231 09:51:30.113617 14937 init.cc:206]     @     0x7faf41f68eae _Unwind_ForcedUnwind
W1231 09:51:30.115314 14937 init.cc:206]     @     0x7faf5a5af070 __GI___pthread_unwind
W1231 09:51:30.116974 14937 init.cc:206]     @     0x7faf5a5a7845 __pthread_exit
W1231 09:51:30.117314 14937 init.cc:206]     @     0x55d490b92249 PyThread_exit_thread
W1231 09:51:30.117440 14937 init.cc:206]     @     0x55d490a16d3c PyEval_RestoreThread.cold.800
W1231 09:51:30.119024 14937 init.cc:206]     @     0x7faf0d7bcd79 pybind11::gil_scoped_release::~gil_scoped_release()
W1231 09:51:30.120441 14937 init.cc:206]     @     0x7faf0d770c47 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9operators6reader22LoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE58_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESY_
W1231 09:51:30.121943 14937 init.cc:206]     @     0x7faf0d7d0fe1 pybind11::cpp_function::dispatcher()
W1231 09:51:30.122329 14937 init.cc:206]     @     0x55d490b12fd4 _PyMethodDef_RawFastCallKeywords
W1231 09:51:30.122689 14937 init.cc:206]     @     0x55d490b130f1 _PyCFunction_FastCallKeywords
W1231 09:51:30.123044 14937 init.cc:206]     @     0x55d490b7fa5e _PyEval_EvalFrameDefault
W1231 09:51:30.123390 14937 init.cc:206]     @     0x55d490ac38aa _PyEval_EvalCodeWithName
W1231 09:51:30.123749 14937 init.cc:206]     @     0x55d490ac46e5 _PyFunction_FastCallDict
W1231 09:51:30.124125 14937 init.cc:206]     @     0x55d490b7c57d _PyEval_EvalFrameDefault
W1231 09:51:30.124445 14937 init.cc:206]     @     0x55d490b1254b _PyFunction_FastCallKeywords
W1231 09:51:30.124809 14937 init.cc:206]     @     0x55d490b7add0 _PyEval_EvalFrameDefault
W1231 09:51:30.125138 14937 init.cc:206]     @     0x55d490b1254b _PyFunction_FastCallKeywords
W1231 09:51:30.125494 14937 init.cc:206]     @     0x55d490b7add0 _PyEval_EvalFrameDefault
W1231 09:51:30.125836 14937 init.cc:206]     @     0x55d490ac461b _PyFunction_FastCallDict
W1231 09:51:30.126164 14937 init.cc:206]     @     0x55d490ae2ac3 _PyObject_Call_Prepend
W1231 09:51:30.126529 14937 init.cc:206]     @     0x55d490ad5392 PyObject_Call
W1231 09:51:30.126693 14937 init.cc:206]     @     0x55d490bd2d27 t_bootstrap
W1231 09:51:30.126783 14937 init.cc:206]     @     0x55d490b8db98 pythread_wrapper
W1231 09:51:30.128527 14937 init.cc:206]     @     0x7faf5a5a66ba start_thread
已放弃 (核心已转储)

**Comment by mikeFang1986** [comment]
修改训练命令，去掉 --eval，问题没有复现
python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --use_tb=True --tb_log_dir=tb_fruit_dir/scalar
请问原因是啥?去掉改选项对训练出的模型会有啥影响吗？

**Comment by mikeFang1986** [comment]
python tools/eval.py -c configs/yolov3_mobilenet_v1_fruit.yml -o weights=output/yolov3_mobilenet_v1_fruit/model_final

python -u tools/infer.py -c configs/yolov3_mobilenet_v1_fruit.yml \
                         -o weights=output/yolov3_mobilenet_v1_fruit/model_final \
                         --infer_img=demo/orange_71.jpg
会出现同样的错误，因该是不能推理

**Comment by xiegegege** [comment]
我之前遇到过CUDNN_STATUS_BAD_PARAM这个报错，当时是cudnn版本太低导致的，我看log里有句warning:The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.4, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version。或许你可以试着把本地cudnn升到7.6试下？

**Comment by mikeFang1986** [comment]
> 我之前遇到过CUDNN_STATUS_BAD_PARAM这个报错，当时是cudnn版本太低导致的，我看log里有句warning:The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.4, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version。或许你可以试着把本地cudnn升到7.6试下？

是的那，非常感谢。不能放过warning~
