### ISSUE TITLE
模型滤波器通道数报错

### ISSUE THREAD

**Issue by chliang** [PaddlePaddle/models#4168]
图像分类，输入图像通道改为6，配置文件 `'--image_shape 6 500  512', `中通道也改成了6，
但是 运行过程中报错。
使用最简单的 alexnet测试。

https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/models/alexnet.py
```
----------------------
Error Message Summary:
----------------------
Error: ShapeError: The number of input channels should be equal to filter channels * groups. But received: the input channels is [6], the 
shapeof input is [1, 6, 500, 512], the filter 
channel is [3], the shape of filter is [64, 3, 11, 11],the groups is [1]
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:6 != filter_dims[1] * groups:3.] at (D:\1.6.2\paddle\paddle\fluid\operators\conv_op.cc:94)     
  [operator < conv2d > error]
```

问题 ，滤波器的通道数怎么改，里面是默认是3 么？不应该是和输入数据的通道数一致么

**Comment by guoshengCS** [comment]
是会和输入的通道数一致的，是否是格式有问题呢，看和[README](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/README.md)中的不太一致，还请 @shippingwang 帮忙确认下。

**Comment by chliang** [comment]
```
But received: the input channels is [6], 
the  shapeof input is [1, 6, 500, 512], 
the filter channel is [3],
the shape of filter is [64, 3, 11, 11]
```
上面错误信息可以看出，输入数据通道数是6，卷积核通道是3

**Comment by guoshengCS** [comment]
是说设置 image_shape使用的参数格式，看README中的是 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m paddle.distributed.launch train.py \
       --model=ResNet50 \
       --batch_size=256 \
       --total_images=1281167 \
       --class_dim=1000 \
       --image_shape 3 224 224 \
       --model_save_dir=output/ \
       --lr_strategy=piecewise_decay \
       --reader_thread=4 \
       --lr=0.1
```

**Comment by chliang** [comment]
> 是说设置 image_shape使用的参数格式，看README中的是
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3 python -m paddle.distributed.launch train.py \
>        --model=ResNet50 \
>        --batch_size=256 \
>        --total_images=1281167 \
>        --class_dim=1000 \
>        --image_shape 3 224 224 \
>        --model_save_dir=output/ \
>        --lr_strategy=piecewise_decay \
>        --reader_thread=4 \
>        --lr=0.1
> ```

这个是 我贴错了，不是这问题，我这么 写 `--image_shape 6 500  512` 还是一样的

**Comment by guoshengCS** [comment]
可以试下在这里打印下这个feed_image https://github.com/PaddlePaddle/models/blob/2934b0be0e5a3d2088720b58c0fb72baca5d6c3e/PaddleCV/image_classification/utils/utility.py#L375 ，也请 @shippingwang 帮忙确认下吧

**Comment by chliang** [comment]
> 可以试下在这里打印下这个feed_image
> 
> https://github.com/PaddlePaddle/models/blob/2934b0be0e5a3d2088720b58c0fb72baca5d6c3e/PaddleCV/image_classification/utils/utility.py#L375
> 
> ，也请 @shippingwang 帮忙确认下吧

![image](https://user-images.githubusercontent.com/1207569/71887841-e0c48200-3179-11ea-9d1f-3e57083dc5f8.png)

**Comment by shippingwang** [comment]
详细的报错信息给一下，是在alexnet的第一个conv就报错了么？
btw, image_shape改自定义，得注意下reader yield的出来的是不是想要的

**Comment by chliang** [comment]
> 详细的报错信息给一下，是在alexnet的第一个conv就报错了么？
> btw, image_shape改自定义，得注意下reader yield的出来的是不是想要的

看我上面提供的信息，第一层输入的图像通道数是6，和image_shape 设置通道数一直。🙏 应该就是在第一个卷积就出现了错误。

**Comment by chliang** [comment]
```
c:\program files\python37\lib\site-packages\paddle\fluid\executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\project\yy\PaddleClassification\train.py", line 348, in <module>
    main()
  File "d:\project\yy\PaddleClassification\train.py", line 344, in main
    train(args)
  File "d:\project\yy\PaddleClassification\train.py", line 253, in train
    fetch_list=train_fetch_list)
  File "c:\program files\python37\lib\site-packages\paddle\fluid\executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "c:\program files\python37\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "c:\program files\python37\lib\site-packages\paddle\fluid\executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "c:\program files\python37\lib\site-packages\paddle\fluid\executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "c:\program files\python37\lib\site-packages\paddle\fluid\executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "c:\program files\python37\lib\site-packages\paddle\fluid\framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "c:\program files\python37\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\paddle\fluid\layers\nn.py", line 2803, in conv2d
    "data_format": data_format,
  File "d:\project\yy\PaddleClassification\models\alexnet.py", line 49, in net
    name=layer_name[0] + "_weights"))
  File "d:\project\yy\PaddleClassification\build_model.py", line 39, in _basic_model
    net_out = model.net(input=image, class_dim=args.class_dim)
  File "d:\project\yy\PaddleClassification\build_model.py", line 120, in create_model        
    loss_out = _basic_model(data, model, args, is_train)
  File "d:\project\yy\PaddleClassification\train.py", line 65, in build_program
    data_loader, loss_out = create_model(model, args, is_train)
  File "d:\project\yy\PaddleClassification\train.py", line 172, in train
    args=args)
  File "d:\project\yy\PaddleClassification\train.py", line 344, in main
    train(args)
  File "d:\project\yy\PaddleClassification\train.py", line 348, in <module>
    main()
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)

----------------------
Error Message Summary:
----------------------
Error: ShapeError: The number of input channels should be equal to filter channels * groups. 
But received: the input channels is [6], the shapeof input is [1, 6, 500, 512], the filter channel is [3], the shape of filter is [64, 3, 11, 11],the groups is [1]
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:6 != filter_dims[1] * groups:3.] at (D:\1.6.2\paddle\paddle\fluid\operators\conv_op.cc:94)       
  [operator < conv2d > error]
```

**Comment by chliang** [comment]
@shippingwang

**Comment by wulipc** [comment]
加载的权重会影响参数的shape， 因为你加载的模型的第一层参数是针对三通道的， 所有输入6通道的数据的时候会有报错； 请手动删除第一层的权重， 或者不使用预训练模型。

**Comment by chliang** [comment]
> 加载的权重会影响参数的shape， 因为你加载的模型的第一层参数是针对三通道的， 所有输入6通道的数据的时候会有报错； 请手动删除第一层的权重， 或者不使用预训练模型。

按照你说的，解决了。非常感谢

**Comment by wulipc** [comment]
> > 加载的权重会影响参数的shape， 因为你加载的模型的第一层参数是针对三通道的， 所有输入6通道的数据的时候会有报错； 请手动删除第一层的权重， 或者不使用预训练模型。
> 
> 按照你说的，解决了。非常感谢

@guoshengCS  建议paddle调整一下参数加载策略， 如果shape不一致就不要强行加载了吧， 目前的策略会给用户带来困惑。
