### ISSUE TITLE
dialogue_general_understanding linux python3 报错

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/models#4174]
train udc start..........
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from train import do_train
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/train.py", line 29, in <module>
    import dgu.reader as reader
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/reader.py", line 26, in <module>
    reload(sys)
NameError: name 'reload' is not defined
train udc finish..........

**Comment by xyzhou-puck** [comment]
Thanks for reporting this errors, we will fix this problem very soon.

**Comment by zhengya01** [comment]
> Thanks for reporting this errors, we will fix this problem very soon.

这个模型在paddle-develop版本上没有适配，报错信息如下：

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2500, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 231, in __impl__
    attrs={'axis': -1})
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/transformer_encoder.py", line 119, in scaled_dot_product_attention
    product += attn_bias
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/transformer_encoder.py", line 148, in multi_head_attention
    dropout_rate)
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/transformer_encoder.py", line 274, in encoder_layer
    name=name + '_multi_head_att')
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/transformer_encoder.py", line 337, in encoder
    name=name + '_layer_' + str(i))
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/bert.py", line 144, in _build_model
    name='encoder')
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu/bert.py", line 86, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/dgu_net.py", line 49, in create_net
    use_fp16=False)
  File "/ssd2/zhengya01/devlop_conv/test/models/PaddleNLP/PaddleDialogue/dialogue_general_understanding/train.py", line 97, in do_train
    args=args)
  File "main.py", line 37, in <module>
    do_train(args)

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 12, 210, 210] and the shape of Y = [-1, 12, -1]. Received [210] in X is not equal to [12] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_add > error]
