### ISSUE TITLE
Got "ValueError: The input should be a vector, please check your input data." problem

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/models#420]
I met the following errors when I tried to run my DSSM model,
```text
> [INFO 2017-11-06 11:53:25,772 reader.py:66] [reader] load trainset from /home/work/zhaoyijin/video-recsys-model/dssm/train_data_dir/train/train
Traceback (most recent call last):
  File "train.py", line 247, in <module>
    use_gpu=args.use_gpu)
  File "train.py", line 229, in train
    num_passes=num_passes)
  File "/home/work/zhaoyijin/paddle_new/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 169, in train
    in_args = feeder(data_batch)
  File "/home/work/zhaoyijin/paddle_new/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 282, in __call__
    return self.convert(dat, argument)
  File "/home/work/zhaoyijin/paddle_new/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 133, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/home/work/zhaoyijin/paddle_new/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 267, in convert
    scanner.pre_scan(each_step)
  File "/home/work/zhaoyijin/paddle_new/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 114, in pre_scan
    "The input should be a vector, please check your input data."
ValueError: The input should be a vector, please check your input data.
```
Here is my code related to data input, in reader.py
```python
def train(self):
        logger.info("[reader] load trainset from %s" % self.train_path)
        with open(self.train_path) as f:
            for line_id, line in enumerate(f):
                yield self.record_reader(line)

def _read_classification_record(self, line):
        fs = line.strip().split('\t')
        label = int(fs[0])
        user_id = self.feature_dic['baidu_id'].get(fs[1], UNK)
        video_id = self.feature_dic['item_id'].get(fs[3], UNK)
        cluster_id = self.feature_dic['cluster_no'].get(fs[10], UNK)
        title_len = len(fs[5])
        if not self.is_infer:
            out_list = [video_id, cluster_id, title_len, user_id, label, ]
            return tuple(out_list)
        out_list = [video_id, cluster_id, title_len, user_id]
        return tuple(out_list)
```
train.py:
```python
def train(train_data_path=None,
          test_data_path=None,
          dic_path=None,
          model_type=ModelType.create_classification(),
          batch_size=10,
          num_passes=10,
          share_semantic_generator=False,
          share_embed=False,
          class_num=None,
          num_workers=1,
          use_gpu=False):
    '''
    Train the DSSM.
    '''
    if not train_data_path or not test_data_path:
        logger.error("No input data")
        exit(1)

    dataset = reader.Dataset(
        train_path=train_data_path,
        test_path=test_data_path,
        dic_path=dic_path,
        model_type=model_type, )

    train_reader = paddle.batch(
        paddle.reader.shuffle(dataset.train, buf_size=1000),
        batch_size=batch_size)

    test_reader = paddle.batch(
        paddle.reader.shuffle(dataset.test, buf_size=1000),
        batch_size=batch_size)

    paddle.init(use_gpu=use_gpu, trainer_count=num_workers)

    cost, prediction, label = DSSM(
        dnn_dims=layer_dims,
        feature_size_dict=dataset.load_feature_size_dic(dic_path),
        model_type=model_type,
        share_semantic_generator=share_semantic_generator,
        class_num=class_num,
        share_embed=share_embed)()

    parameters = paddle.parameters.create(cost)

    adam_optimizer = paddle.optimizer.Adam(
        learning_rate=1e-3,
        regularization=paddle.optimizer.L2Regularization(rate=1e-3),
        model_average=paddle.optimizer.ModelAverage(average_window=0.5))

    trainer = paddle.trainer.SGD(
        cost=cost,
        extra_layers=paddle.evaluator.auc(input=prediction, label=label)
        if not model_type.is_rank() else None,
        parameters=parameters,
        update_equation=adam_optimizer)

    feeding = {'video_id': 0, 'cluster_id': 1, 'title_len': 2, 'user_id':3, 'label_input':4}

    def _event_handler(event):
        '''
        Define batch handler
        '''
        if isinstance(event, paddle.event.EndIteration):
            # output train log
            if event.batch_id % args.num_batches_to_log == 0:
                logger.info("Pass %d, Batch %d, Cost %f, %s" % (
                    event.pass_id, event.batch_id, event.cost, event.metrics))

            # test model
            if event.batch_id > 0 and \
                    event.batch_id % args.num_batches_to_test == 0:
                if test_reader is not None:
                    if model_type.is_classification():
                        result = trainer.test(
                            reader=test_reader, feeding=feeding)
                        logger.info("Test at Pass %d, %s" % (event.pass_id,
                                                             result.metrics))
                    else:
                        result = None
            # save model
            if event.batch_id > 0 and \
                    event.batch_id % args.num_batches_to_save_model == 0:
                model_desc = "{type}_{arch}".format(
                    type=str(args.model_type), arch=str(args.model_arch))
                with open("%sdssm_%s_pass_%05d.tar" %
                          (args.model_output_prefix, model_desc,
                           event.pass_id), "w") as f:
                    trainer.save_parameter_to_tar(f)

    trainer.train(
        reader=train_reader,
        event_handler=_event_handler,
        feeding=feeding,
        num_passes=num_passes)

    logger.info("Training has finished.")
```

**Comment by luotao1** [comment]
错误提示已经非常明显了。请先对着 http://doc.paddlepaddle.org/doc_cn/getstarted/concepts/use_concepts_cn.html 查一下数据格式。

**Comment by Bella-Zhao** [comment]
问题找到，dense_vector传入了float，不是vector
