### ISSUE TITLE
aistudio上运行PaddleNLP-sentiment_classification，训练sh run.sh train 报错

### ISSUE THREAD

**Issue by casolxia** [PaddlePaddle/models#4268]
paddle-gpu版本为aistudio默认安装版本

paddlehub 1.0.0 
paddlepaddle-gpu 1.4.1.post97

Traceback (most recent call last):
  File "run_classifier.py", line 327, in <module>
    main(args)
  File "run_classifier.py", line 157, in main
    shuffle=True)
  File "/home/aistudio/work/models-develop/PaddleNLP/sentiment_classification/reader.py", line 75, in data_generator
    return fluid.io.batch(self.get_train_examples(self.data_dir, epoch, self.max_seq_len), batch_size)
AttributeError: module 'paddle.fluid.io' has no attribute 'batch'

是需要升级paddlepaddle版本么

**Comment by casolxia** [comment]
应该是版本问题需要paddlepaddle-1.6的版本

**Comment by zhupengyang** [comment]
好的，如果已经解决，请关闭一下issue哦
