### ISSUE TITLE
ocr识别模型保存inference model时遇到类型不匹配的问题

### ISSUE THREAD

**Issue by endy-see** [PaddlePaddle/models#4313]
将训练好的模型在infer.py中加载，并用infer net保存inference model时出错，保存的代码如下：
fluid.io.save_inference_model(args.save_model_dir+filename, feeded_var_names=['pixel'], target_vars=[ids], executor=exe, main_program=inference_program, params_filename="__params__")
其中inference_program是在inference model load时候生成的。
报错如下：
Traceback (most recent call last):
  File "infer.py", line 194, in <module>
    main()
  File "infer.py", line 190, in main
    inference(args)
  File "infer.py", line 156, in inference
    if args.save_inference_model:
  File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 1141, in save_inference_model
    var, 1., name="save_infer_model/scale_{}".format(i))
  File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 14031, in scale
    name=name, dtype=x.dtype, persistable=False)
  File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 355, in create_variable
    return self.main_program.current_block().create_var(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2301, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 684, in __init__
    "matched.".format(self.name, old_dtype, dtype))
ValueError: Variable save_infer_model/scale_0 has been created before. The previous data type is VarType.FP32; the new data type is VarType.INT64. They are not matched.

**Comment by endy-see** [comment]
原因是在infer.py中再次保存inference model时传的参数不对，我按下面的方式纠正就可以了
filename = 'model_50000'
    if args.save_inference_model:
        fluid.io.save_inference_model(args.save_model_dir+filename, feeded_var_names=['pixel'], target_vars=[ids], executor=exe, main_program=fluid.default_main_program(), model_filename='__model__', params_filename="__params__")
