### ISSUE TITLE
用paddle视频分类模型进行finetune开发报错。

### ISSUE THREAD

**Issue by davidwhite-www** [PaddlePaddle/models#4353]
用paddle视频分类的TSN模型进行finetune开发。下载了Paddle提供的Model Zoo里已发布模型，通过--resume指定权重存放路径。使用的命令行为：
python train.py --model_name=TSN --config=./configs/tsn.yaml --log_interval=10 --valid_interval=1 --use_gpu=True --save_dir='./checkpoints' --fix_random_seed=False --resume='./TSN_final.pdparams' 

报如下错误：（改成TSM模型、STNET模型等，一直报如下错误。之前用paddle1.6.3也是报错，现在升级到1.7.0还是报如下错误。同样的模型，用eval和predict不会报错，是我的用法有问题吗？）
C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "d:/paddle/PaddleVideo/train.py", line 265, in <module>
    train(args)
  File "d:/paddle/PaddleVideo/train.py", line 172, in train
    exe, '', main_program=train_prog, filename=args.resume)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 917, in load_persistables
    filename=filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 742, in load_vars
    filename=filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 794, in load_vars
    executor.run(load_prog)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 792, in load_vars
    'model_from_memory': vars_from_memory
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 742, in load_vars
    filename=filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 917, in load_persistables
    filename=filename)
  File "d:/paddle/PaddleVideo/train.py", line 172, in train
    exe, '', main_program=train_prog, filename=args.resume)
  File "d:/paddle/PaddleVideo/train.py", line 265, in <module>
    train(args)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] at (D:/1.7.0/paddle/paddle/fluid/framework/.tensor_util.cu:527)
  [operator < load_combine > error]

**Comment by SunGaofeng** [comment]
这地方说明文档表述有点问题，--resume是用在断点继续训练的，需要加载模型和优化器相关的参数。TSN_final.pdparams里面只包含了模型参数，没有优化器相关的参数，导致加载的时候出错了。

需要将train.py第171行的
     fluid.io.load_persistables(exe, '', main_program=train_prog, filename=args.resume)
改成
     fluid.io.load_params(exe, '', main_program=train_prog, filename=args.resume)
这样只加载模型参数，而不用管跟优化器相关的参数。

我们后面会修复下这个问题，增加一个--finetune选项，以便跟--resume区分开来。

**Comment by davidwhite-www** [comment]
谢谢，按这个方法，问题已解决。

**Comment by davidwhite-www** [comment]
谢谢，按这个方法，问题已解决。
