### ISSUE TITLE
PaddleHub 情感分析教程运行错误

### ISSUE THREAD

**Issue by githubusr2** [PaddlePaddle/models#4364]
PaddleHub 情感分析教程运行如下错误：
七、开始Finetune
我们选择finetune_and_eval接口来进行模型训练，这个接口在finetune的过程中，会周期性的进行模型效果的评估，以便我们了解整个训练过程的性能变化。
run_states = cls_task.finetune_and_eval()
[2020-03-01 16:25:06,188] [    INFO] - Strategy with scheduler: {'warmup': 0.1, 'linear_decay': {'start_point': 0.1, 'end_learning_rate': 0}, 'noam_decay': False, 'discriminative': {'blocks': 0, 'factor': 2.6}, 'gradual_unfreeze': 0, 'slanted_triangle': {'cut_fraction': 0.0, 'ratio': 32}}, regularization: {'L2': 0.0, 'L2SP': 0.0, 'weight_decay': 0.01} and clip: {'GlobalNorm': 1.0, 'Norm': 0.0}
2020-03-01 16:25:06,315-WARNING: 
     You can try our memory optimize feature to save your memory usage:
         # create a build_strategy variable to set memory optimize option
         build_strategy = compiler.BuildStrategy()
         build_strategy.enable_inplace = True
         build_strategy.memory_optimize = True
         
         # pass the build_strategy to with_data_parallel API
         compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
             loss_name=loss.name, build_strategy=build_strategy)
      
     !!! Memory optimize is our experimental feature !!!
         some variables may be removed/reused internal to save memory usage, 
         in order to fetch the right value of the fetch_list, please set the 
         persistable property to true for each variable in fetch_list

         # Sample
         conv1 = fluid.layers.conv2d(data, 4, 5, 1, act=None) 
         # if you need to fetch conv1, then:
         conv1.persistable = True

                 
[2020-03-01 16:25:07,187] [    INFO] - Try loading checkpoint from nlp_senta_turtorial_demo/ckpt.meta
[2020-03-01 16:25:07,189] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-03-01 16:25:07,221] [    INFO] - PaddleHub finetune start
[2020-03-01 16:25:07,227] [    INFO] - 20 pretrained paramaters loaded by PaddleHub
[2020-03-01 16:25:11,932] [   TRAIN] - step 10 / 300: loss=0.71818 acc=0.16562 [step/sec: 2.13]
[2020-03-01 16:25:16,371] [   TRAIN] - step 20 / 300: loss=0.71554 acc=0.15937 [step/sec: 2.25]
[2020-03-01 16:25:20,792] [   TRAIN] - step 30 / 300: loss=0.70258 acc=0.26250 [step/sec: 2.26]
[2020-03-01 16:25:25,574] [   TRAIN] - step 40 / 300: loss=0.68916 acc=0.60313 [step/sec: 2.09]
[2020-03-01 16:25:30,040] [   TRAIN] - step 50 / 300: loss=0.66774 acc=0.85000 [step/sec: 2.24]
[2020-03-01 16:25:30,044] [    INFO] - Evaluation on dev dataset start
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 585, in __provider_thread__
    raise ex
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 567, in __provider_thread__
    for tensors in func():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 617, in __tensor_provider__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 326, in __reader_creator__
    for item in reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/batch.py", line 35, in batch_reader
    for instance in r:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/nlp_reader.py", line 1203, in _data_reader
    text = preprocess(item.text_a)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/nlp_reader.py", line 1178, in preprocess
    processed = self.lac.lexical_analysis(data=data_dict)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py", line 543, in __call__
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator mul error.
Python Callstacks: 
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 323, in fc
    "y_num_col_dims": 1})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py", line 200, in _build_net
    act="softmax")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 329, in _build_env
    self.env.outputs = self._build_net()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 474, in main_program
    self._build_env()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 826, in _run
    with fluid.program_guard(self.main_program, self.startup_program):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 799, in eval
    run_states = self._run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 688, in _default_eval_interval_event
    self.eval(phase="dev")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 580, in hook_function
    func(*args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 930, in _run_with_py_reader
    self._eval_interval_event()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 828, in _run
    return self._run_with_py_reader(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 775, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 763, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "<ipython-input-8-33eafd68b5ee>", line 1, in <module>
    run_states = cls_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3183, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 370, in dispatch_queue
    yield self.process_one()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle._run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
C++ Callstacks: 
Input X(0)is not initialized at [/paddle/paddle/fluid/framework/operator.cc:1109]
PaddlePaddle Call Stacks: 
0       0x7fdca7ea2d60p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fdca7ea30d9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fdca9b2f04fp paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 1343
3       0x7fdca9b2f23fp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
4       0x7fdca9b322a3p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 243
5       0x7fdca9b32bb4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
6       0x7fdca9b304dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7fdca801541ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 222
8       0x7fdca80162ffp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
9       0x7fdca7e9296ep
10      0x7fdca7ed576ep
11      0x55b857d62744p _PyMethodDef_RawFastCallKeywords + 596
12      0x55b857d62861p _PyCFunction_FastCallKeywords + 33
13      0x55b857dce6e8p _PyEval_EvalFrameDefault + 21240
14      0x55b857d12539p _PyEval_EvalCodeWithName + 761
15      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
16      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
17      0x55b857d12539p _PyEval_EvalCodeWithName + 761
18      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
19      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
20      0x55b857d12d09p _PyEval_EvalCodeWithName + 2761
21      0x55b857d13860p _PyFunction_FastCallDict + 1024
22      0x55b857d31e53p _PyObject_Call_Prepend + 99
23      0x55b857d24dbep PyObject_Call + 110
24      0x55b857e21bc7p
25      0x55b857d6a8fbp _PyObject_FastCallKeywords + 1179
26      0x55b857dcea8fp _PyEval_EvalFrameDefault + 22175
27      0x55b857d1281ap _PyEval_EvalCodeWithName + 1498
28      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
29      0x55b857dc9806p _PyEval_EvalFrameDefault + 1046
30      0x55b857d6ab31p
31      0x55b857dc9e36p _PyEval_EvalFrameDefault + 2630
32      0x55b857d6ab31p
33      0x55b857dc9e36p _PyEval_EvalFrameDefault + 2630
34      0x55b857d6ab31p
35      0x55b857dc9e36p _PyEval_EvalFrameDefault + 2630
36      0x55b857d6ab31p
37      0x55b857dc9e36p _PyEval_EvalFrameDefault + 2630
38      0x55b857d12d09p _PyEval_EvalCodeWithName + 2761
39      0x55b857d13635p _PyFunction_FastCallDict + 469
40      0x55b857dcb232p _PyEval_EvalFrameDefault + 7746
41      0x55b857d61ccbp _PyFunction_FastCallKeywords + 251
42      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
43      0x55b857d61ccbp _PyFunction_FastCallKeywords + 251
44      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
45      0x55b857d1356bp _PyFunction_FastCallDict + 267
46      0x55b857d31e53p _PyObject_Call_Prepend + 99
47      0x55b857d24dbep PyObject_Call + 110
48      0x55b857e21817p
49      0x55b857ddc788p
50      0x7fdd253e76bap
51      0x7fdd2511d41dp clone + 109

---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-8-33eafd68b5ee> in <module>
----> 1 run_states = cls_task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    761 
    762     def finetune_and_eval(self):
--> 763         return self.finetune(do_eval=True)
    764 
    765     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    773                 while self.current_epoch <= self.config.num_epoch:
    774                     self.config.strategy.step()
--> 775                     run_states = self._run(do_eval=do_eval)
    776                     self.env.current_epoch += 1
    777 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
    826         with fluid.program_guard(self.main_program, self.startup_program):
    827             if self.config.use_pyreader:
--> 828                 return self._run_with_py_reader(do_eval=do_eval)
    829             return self._run_with_data_feeder(do_eval=do_eval)
    830 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run_with_py_reader(self, do_eval)
    928 
    929                         if do_eval and self.current_step % self.config.eval_interval == 0:
--> 930                             self._eval_interval_event()
    931 
    932                     self._run_step_event(step_run_state)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    578             for name, func in self._hooks[hook_type].items():
    579                 if inspect.ismethod(func):
--> 580                     func(*args)
    581                 else:
    582                     partial(func, self)(*args)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _default_eval_interval_event(self)
    686 
    687     def _default_eval_interval_event(self):
--> 688         self.eval(phase="dev")
    689 
    690     def _default_run_step_event(self, run_state):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in eval(self, phase, load_best_model)
    797                 self.init_if_necessary()
    798             self._eval_start_event()
--> 799             run_states = self._run()
    800             self._eval_end_event(run_states)
    801             return run_states
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
    824 
    825     def _run(self, do_eval=False):
--> 826         with fluid.program_guard(self.main_program, self.startup_program):
    827             if self.config.use_pyreader:
    828                 return self._run_with_py_reader(do_eval=do_eval)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in main_program(self)
    472     def main_program(self):
    473         if not self.env.is_inititalized:
--> 474             self._build_env()
    475         return self.env.main_program
    476 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _build_env(self)
    327                                  self._base_startup_program):
    328             with fluid.unique_name.guard(self.env.UNG):
--> 329                 self.env.outputs = self._build_net()
    330                 if self.is_train_phase or self.is_test_phase:
    331                     self.env.labels = self._add_label()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/classifier_task.py in _build_net(self)
    198             bias_attr=fluid.ParamAttr(
    199                 name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
--> 200             act="softmax")
    201 
    202         self.ret_infers = fluid.layers.reshape(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py in fc(input, size, num_flatten_dims, param_attr, bias_attr, act, is_test, name)
    321             outputs={"Out": tmp},
    322             attrs={"x_num_col_dims": num_flatten_dims,
--> 323                    "y_num_col_dims": 1})
    324         mul_results.append(tmp)
    325 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py in append_op(self, *args, **kwargs)
     41 
     42     def append_op(self, *args, **kwargs):
---> 43         return self.main_program.current_block().append_op(*args, **kwargs)
     44 
     45     def multiple_input(self, input_param_name='input'):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in append_op(self, *args, **kwargs)
   1652                 inputs=kwargs.get("inputs", None),
   1653                 outputs=kwargs.get("outputs", None),
-> 1654                 attrs=kwargs.get("attrs", None))
   1655 
   1656             self.ops.append(op)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __init__(***failed resolving arguments***)
   1056             if self._has_kernel(type):
   1057                 self.desc.infer_var_type(self.block.desc)
-> 1058                 self.desc.infer_shape(self.block.desc)
   1059 
   1060     def _has_kernel(self, op_type):
EnforceNotMet: Enforce failed. Expected x_dims.size() > x_num_col_dims, but received x_dims.size():1 <= x_num_col_dims:1.
The input tensor X's rank of MulOp should be larger than x_num_col_dims. at [/paddle/paddle/fluid/operators/mul_op.cc:48]
PaddlePaddle Call Stacks: 
0       0x7fdca7ea3288p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fdca7ea35d7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fdca857e417p paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 3319
3       0x7fdca7ffac6ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7fdca7f5225cp
5       0x7fdca7ed576ep
6       0x55b857d62744p _PyMethodDef_RawFastCallKeywords + 596
7       0x55b857d62861p _PyCFunction_FastCallKeywords + 33
8       0x55b857dce6e8p _PyEval_EvalFrameDefault + 21240
9       0x55b857d12539p _PyEval_EvalCodeWithName + 761
10      0x55b857d13860p _PyFunction_FastCallDict + 1024
11      0x55b857d31e53p _PyObject_Call_Prepend + 99
12      0x55b857d6997ap
13      0x55b857d6a588p _PyObject_FastCallKeywords + 296
14      0x55b857dcea8fp _PyEval_EvalFrameDefault + 22175
15      0x55b857d12539p _PyEval_EvalCodeWithName + 761
16      0x55b857d13860p _PyFunction_FastCallDict + 1024
17      0x55b857d31e53p _PyObject_Call_Prepend + 99
18      0x55b857d24dbep PyObject_Call + 110
19      0x55b857dcb232p _PyEval_EvalFrameDefault + 7746
20      0x55b857d12539p _PyEval_EvalCodeWithName + 761
21      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
22      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
23      0x55b857d12539p _PyEval_EvalCodeWithName + 761
24      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
25      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
26      0x55b857d61ccbp _PyFunction_FastCallKeywords + 251
27      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
28      0x55b857d12d09p _PyEval_EvalCodeWithName + 2761
29      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
30      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
31      0x55b857d1356bp _PyFunction_FastCallDict + 267
32      0x55b857d76ed2p
33      0x55b857d26fe1p _PyObject_GenericGetAttrWithDict + 257
34      0x55b857dc9cdap _PyEval_EvalFrameDefault + 2282
35      0x55b857d12539p _PyEval_EvalCodeWithName + 761
36      0x55b857d61ef5p _PyFunction_FastCallKeywords + 805
37      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
38      0x55b857d12539p _PyEval_EvalCodeWithName + 761
39      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
40      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
41      0x55b857d1356bp _PyFunction_FastCallDict + 267
42      0x55b857d31e53p _PyObject_Call_Prepend + 99
43      0x55b857d24dbep PyObject_Call + 110
44      0x55b857dcb232p _PyEval_EvalFrameDefault + 7746
45      0x55b857d1281ap _PyEval_EvalCodeWithName + 1498
46      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
47      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
48      0x55b857d12539p _PyEval_EvalCodeWithName + 761
49      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
50      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
51      0x55b857d12539p _PyEval_EvalCodeWithName + 761
52      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
53      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
54      0x55b857d12539p _PyEval_EvalCodeWithName + 761
55      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
56      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
57      0x55b857d61ccbp _PyFunction_FastCallKeywords + 251
58      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
59      0x55b857d12539p _PyEval_EvalCodeWithName + 761
60      0x55b857d13424p PyEval_EvalCodeEx + 68
61      0x55b857d1344cp PyEval_EvalCode + 28
62      0x55b857dd8f8dp
63      0x55b857d625d9p _PyMethodDef_RawFastCallKeywords + 233
64      0x55b857d62861p _PyCFunction_FastCallKeywords + 33
65      0x55b857dcdb94p _PyEval_EvalFrameDefault + 18340
66      0x55b857d6b592p _PyGen_Send + 674
67      0x55b857dcae69p _PyEval_EvalFrameDefault + 6777
68      0x55b857d6b592p _PyGen_Send + 674
69      0x55b857dcae69p _PyEval_EvalFrameDefault + 6777
70      0x55b857d6b592p _PyGen_Send + 674
71      0x55b857d6257dp _PyMethodDef_RawFastCallKeywords + 141
72      0x55b857d6a3cfp _PyMethodDescr_FastCallKeywords + 79
73      0x55b857dce07cp _PyEval_EvalFrameDefault + 19596
74      0x55b857d61ccbp _PyFunction_FastCallKeywords + 251
75      0x55b857dc9806p _PyEval_EvalFrameDefault + 1046
76      0x55b857d61ccbp _PyFunction_FastCallKeywords + 251
77      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
78      0x55b857d12539p _PyEval_EvalCodeWithName + 761
79      0x55b857d13860p _PyFunction_FastCallDict + 1024
80      0x55b857d31e53p _PyObject_Call_Prepend + 99
81      0x55b857d24dbep PyObject_Call + 110
82      0x55b857dcb232p _PyEval_EvalFrameDefault + 7746
83      0x55b857d1281ap _PyEval_EvalCodeWithName + 1498
84      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
85      0x55b857dca8ccp _PyEval_EvalFrameDefault + 5340
86      0x55b857d6b059p
87      0x55b857d625d9p _PyMethodDef_RawFastCallKeywords + 233
88      0x55b857d62861p _PyCFunction_FastCallKeywords + 33
89      0x55b857dcdb94p _PyEval_EvalFrameDefault + 18340
90      0x55b857d12d09p _PyEval_EvalCodeWithName + 2761
91      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
92      0x55b857dc9a93p _PyEval_EvalFrameDefault + 1699
93      0x55b857d6b059p
94      0x55b857d625d9p _PyMethodDef_RawFastCallKeywords + 233
95      0x55b857d62861p _PyCFunction_FastCallKeywords + 33
96      0x55b857dcdb94p _PyEval_EvalFrameDefault + 18340
97      0x55b857d12d09p _PyEval_EvalCodeWithName + 2761
98      0x55b857d61f57p _PyFunction_FastCallKeywords + 903
99      0x55b857dc9806p _PyEval_EvalFrameDefault + 1046

**Comment by kinghuin** [comment]
@githubusr2 
您好，感谢反馈，请尝试以下方法：
1. 您使用的是paddle1.2版本吗？可以升级paddle至1.6版本(如1.6.3报错CUDNN_STATUS_BAD_PARAM则升级至1.6.1)  升级paddlehub至1.5.2
2. 尝试关闭pyreader，在hub.RunConfig中加入这个参数use_pyreader=False
