### ISSUE TITLE
face_detection/train.py  training model bugs

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/models#4369]
### read some image failed
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/root/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 549, in _read_into_queue
    for sample in reader():
  File "/root/phamkhactu/face_detection/reader.py", line 270, in reader
    image_path)
  File "/root/phamkhactu/face_detection/reader.py", line 119, in preprocess
    settings.min_face_size)
  File "/root/phamkhactu/face_detection/image_util.py", line 437, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
2020-03-02 15:47:38,957-WARNING: Your decorated reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 491, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "/root/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 472, in __provider_thread__
    for tensors in func():
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 523, in __tensor_provider__
    for slots in paddle_reader():
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 572, in queue_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception

Pass 0, batch 680, face loss 4.203463, head loss 4.551610, time 0.90225
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    train(args, config, train_parameters, train_file_list)
  File "train.py", line 212, in train
    [v.name for v in fetches])
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/root/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 889, in read_file
    type='read', inputs={'Reader': [reader]}, outputs={'Out': out})
  File "train.py", line 101, in build_program
    image, face_box, head_box, gt_label = fluid.layers.read_file(py_reader)
  File "train.py", line 153, in train
    args=args)
  File "train.py", line 284, in <module>
    train(args, config, train_parameters, train_file_list)

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
```

**Comment by mapingshuo** [comment]
I think this is a `numpy` memory error.

**Comment by qingqing01** [comment]
>   File "/root/phamkhactu/face_detection/image_util.py", line 437, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
> MemoryError

@phamkhactu  The error seems the height or width  is zero, or too large.  You can print them to debug. And which dataset you used?

**Comment by phamkhactu** [comment]
@qingqing01  I use [wider_face_dataset](http://shuoyang1213.me/WIDERFACE/). I think it preprocess,  and i download from driver. Any error in datasets?

**Comment by qingqing01** [comment]
@phamkhactu If WIDERFace dataset, it should be ok.   Whether the annotation is downloaded from:

```
wget http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/bbx_annotation/wider_face_split.zip
unzip wider_face_split.zip && rm -f wider_face_split.zip
```

**Comment by phamkhactu** [comment]
@mapingshuo  @qingqing01. I have question that: Can train model with keras or tensorflow?? Thank in advance if you sharing link github implement it

**Comment by phamkhactu** [comment]
@qingqing01  thank you very much. I will try out it.

**Comment by qingqing01** [comment]
@phamkhactu  Model here only supports PaddlePaddle.  Could you show some debug info about the memory error?

**Comment by phamkhactu** [comment]
@qingqing01  

> wget http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/bbx_annotation/wider_face_split.zip
> unzip wider_face_split.zip && rm -f wider_face_split.zip

here is the split dataset to train,  Have to download dataset from wider_face to train??

**Comment by phamkhactu** [comment]
```
data
|-- download.sh
|-- wider_face_split
|   |-- readme.txt
|   |-- wider_face_train_bbx_gt.txt
|   |-- wider_face_val_bbx_gt.txt
|   `-- ...
|-- WIDER_train
|   `-- images
|       |-- 0--Parade
|       ...
|       `-- 9--Press_Conference
`-- WIDER_val
    `-- images
        |-- 0--Parade
        ...
        `-- 9--Press_Conference
```
from instruction Maybe download wider_face datasets ??. I have been run without dowloading, it show error. @qingqing01

**Comment by phamkhactu** [comment]
> @phamkhactu Model here only supports PaddlePaddle. Could you show some debug info about the memory error?

@qingqing01 
it only shows error i have been posted in above, I can not find exactly where and why.

**Comment by phamkhactu** [comment]
@qingqing01  i debug it it shows error when the width == height 
```
height 301
width 301
----------------
height 396
width 396
----------------
height 306
width 306
----------------
height 8288
width 8288
----------------
height 2377
width 2377
----------------
height 707
width 707
----------------
height 614
width 614
----------------
height 735
width 735
----------------
height 3680
width 3680
----------------
height 1396
width 1396
----------------
height 342
width 342
----------------
height 1577
width 1578
----------------
height 927
width 927
----------------
height 317
width 317
----------------
height 2813
width 2813
----------------
height 330
width 330
----------------
height 783
width 783
----------------
height 1389
width 1389
Pass 1, batch 830, face loss 3.944678, head loss 4.636235, time 0.85032
----------------
height 1814
width 1814
----------------
height 512
width 511
----------------
height 653
width 653
----------------
height 323
width 323
----------------
height 570
width 570
----------------
height 1142
width 1142
----------------
height 767
width 767
----------------
height 2464
width 2464
----------------
height 474
width 474
----------------
height 1158
width 1158
----------------
height 746
width 746
----------------
height 306
width 306
----------------
height 258
width 258
----------------
height 375
width 375
----------------
height 449
width 449
----------------
height 417
width 417
----------------
height 668
width 667
----------------
height 373
width 373
----------------
height 2753
width 2753
----------------
height 656
width 656
----------------
height 495
width 495
----------------
height 2025
width 2025
Pass 1, batch 840, face loss 1.552297, head loss 2.432936, time 0.84701
----------------
height 2730
width 2730
----------------
height 1344
width 1344
----------------
height 382
width 382
----------------
height 1917
width 1917
----------------
height 438
width 438
----------------
height 363
width 363
----------------
height 582
width 582
----------------
height 3901
width 3901
----------------
height 3518
width 3519
----------------
height 1820
width 1820
----------------
height 1282
width 1282
----------------
height 608
width 608
----------------
height 1210
width 1210
Pass 1, batch 850, face loss 2.713190, head loss 2.767012, time 0.84955
----------------
height 874
width 874
----------------
height 476
width 476
----------------
height 396
width 396
----------------
height 334
width 334
----------------
height 537
width 537
----------------
height 636
width 636
----------------
height 646
width 646
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/root/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 549, in _read_into_queue
    for sample in reader():
  File "/root/phamkhactu/face_detection/reader.py", line 270, in reader
    image_path)
  File "/root/phamkhactu/face_detection/reader.py", line 119, in preprocess
    settings.min_face_size)
  File "/root/phamkhactu/face_detection/image_util.py", line 439, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError
----------------
height 1211
width 1211
----------------
height 1738
width 1738
2020-03-03 04:18:10,464-WARNING: Your decorated reader has raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 491, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "/root/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 472, in __provider_thread__
    for tensors in func():
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 523, in __tensor_provider__
    for slots in paddle_reader():
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/usr/local/lib/python3.6/dist-packages/paddle/reader/decorator.py", line 572, in queue_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception

----------------
height 295
width 295
----------------
height 835
width 835
----------------
height 962
width 962
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    train(args, config, train_parameters, train_file_list)
  File "train.py", line 212, in train
    [v.name for v in fetches])
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/root/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/io.py", line 889, in read_file
    type='read', inputs={'Reader': [reader]}, outputs={'Out': out})
  File "train.py", line 101, in build_program
    image, face_box, head_box, gt_label = fluid.layers.read_file(py_reader)
  File "train.py", line 153, in train
    args=args)
  File "train.py", line 284, in <module>
    train(args, config, train_parameters, train_file_list)

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ !=
```

**Comment by qingqing01** [comment]
@phamkhactu 

A small testing, When there is not enough memory:
```
>>> import numpy as np
>>> a=np.zeros((1200000000, 12000000, 3))
Python(25490,0x7fffb689a3c0) malloc: *** mach_vm_map(size=345600000000000000) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```


In the face-detection training, the default uses multiprocess and the worker num is 8. You can reduce the worker number in train.py or set --use_multiprocess=False for a try.

**Comment by phamkhactu** [comment]
> @phamkhactu
> 
> A small testing, When there is not enough memory:
> 
> ```
> >>> import numpy as np
> >>> a=np.zeros((1200000000, 12000000, 3))
> Python(25490,0x7fffb689a3c0) malloc: *** mach_vm_map(size=345600000000000000) failed (error code=3)
> *** error: can't allocate region
> *** set a breakpoint in malloc_error_break to debug
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> MemoryError
> ```
> 
> In the face-detection training, the default uses multiprocess and the worker num is 8. You can reduce the worker number in train.py or set --use_multiprocess=False for a try.

@qingqing01  I have been try it before. It still shows error.

**Comment by qingqing01** [comment]
It still shows error when set --use_multiprocess=False? What's is your environment?

**Comment by phamkhactu** [comment]
@qingqing01  i use docker to training

**Comment by qingqing01** [comment]
@phamkhactu  We tested on P40 (22G memory per GPU), there is no problem when running more than one 1000 iter with bs = 12/per GPU. 

The error seems CPU memory is not enough. How CPU memory does the container use?  Have you tried setting `--use_multiprocess=False`?
