### ISSUE TITLE
DeepVoice3 训练时AssertionError

### ISSUE THREAD

**Issue by weak-fox** [PaddlePaddle/models#4409]
执行python train.py --data-root=ljspeech --use-gpu --preset=../../dv3.single_frame/config.json  --train-seq2seq-only --checkpoint=model后报错

Traceback (most recent call last):
  File "train.py", line 225, in <module>
    model = make_deepvoice3_from_hparams(hparams)
  File "train.py", line 110, in make_deepvoice3_from_hparams
    hparams.key_projection, hparams.value_projection)
  File "/home/aistudio/work/DeepVoice3/deepvoice3_paddle/builder.py", line 75, in deepvoice3
    use_decoder_state_for_postnet_input, "float32")
  File "/home/aistudio/work/DeepVoice3/deepvoice3_paddle/deepvoice3.py", line 1189, in __init__
    window_range, key_projection, value_projection, dropout, dtype)
  File "/home/aistudio/work/DeepVoice3/deepvoice3_paddle/deepvoice3.py", line 1385, in __init__
    dtype=dtype)
  File "/home/aistudio/work/DeepVoice3/deepvoice3_paddle/deepvoice3.py", line 132, in __init__
    dtype=dtype)
  File "/home/aistudio/work/DeepVoice3/deepvoice3_paddle/modules.py", line 119, in Embedding
    dtype=dtype)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 1309, in __init__
    assert self._is_sparse is True and self._is_distributed is False
AssertionError

**Comment by Aurelius84** [comment]
您好，models下DeepVoice3已经移动到了 [PaddlePaddle/Parakeet](https://github.com/PaddlePaddle/Parakeet/tree/develop/examples/deepvoice3)，此仓库下DeepVoice3将被移除，请参考新目录下模型训练代码。
