### ISSUE TITLE
No such  txt file

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/models#4501]
hi,dear
that's the [code](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/predict.py#L51)
and do not find the file.
Should be the [yaml file ](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/configs/attention_cluster.yaml)?

thx

**Comment by ucas010** [comment]
```
Traceback (most recent call last):
  File "D:\python36\new\rcdnn\image\predict.py", line 187, in <module>
    infer(args)
  File "D:\python36\new\rcdnn\image\predict.py", line 87, in infer
    config = parse_config(args.config)
  File "D:\python36\new\rcdnn\image\utils\config_utils.py", line 17, in parse_config
    with open(cfg_file, 'r') as fopen:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/attention_cluster.txt'
```

**Comment by shippingwang** [comment]
Thanks for pointing out, we will correct it
