### ISSUE TITLE
The NeXtVLAD final model couldn't be used ???

### ISSUE THREAD

**Issue by ucas010** [PaddlePaddle/models#4502]
hi,dear
the nextvlad_final file can't be load ???
```
[INFO: predict.py:  185]: Namespace(batch_size=1, config='configs/attention_cluster.txt', filelist=None, infer_topk=20, log_interval=1, model_name='AttentionCluster', save_dir='data\\predict_results', use_gpu=False, video_path=None, weights='./NEXTVLAD_final.pdparams')
[INFO: config_utils.py:   56]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   58]: MODEL:
[INFO: config_utils.py:   60]:     name:AttentionCluster
[INFO: config_utils.py:   60]:     dataset:YouTube-8M
[INFO: config_utils.py:   60]:     bone_network:None
[INFO: config_utils.py:   60]:     drop_rate:0.5
[INFO: config_utils.py:   60]:     feature_num:2
[INFO: config_utils.py:   60]:     feature_names:['rgb', 'audio']
[INFO: config_utils.py:   60]:     feature_dims:[1024, 128]
[INFO: config_utils.py:   60]:     seg_num:100
[INFO: config_utils.py:   60]:     cluster_nums:[32, 32]
[INFO: config_utils.py:   60]:     num_classes:3862
[INFO: config_utils.py:   60]:     topk:20
[INFO: config_utils.py:   60]:     UNIQUE:{'good': 20, 'bad': 30}
[INFO: config_utils.py:   58]: TRAIN:
[INFO: config_utils.py:   60]:     epoch:5
[INFO: config_utils.py:   60]:     learning_rate:0.001
[INFO: config_utils.py:   60]:     pretrain_base:None
[INFO: config_utils.py:   60]:     batch_size:2048
[INFO: config_utils.py:   60]:     use_gpu:True
[INFO: config_utils.py:   60]:     num_gpus:8
[INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/train.list
[INFO: config_utils.py:   58]: VALID:
[INFO: config_utils.py:   60]:     batch_size:2048
[INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/val.list
[INFO: config_utils.py:   58]: TEST:
[INFO: config_utils.py:   60]:     batch_size:256
[INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/test.list
[INFO: config_utils.py:   58]: INFER:
[INFO: config_utils.py:   60]:     batch_size:1
[INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/infer.list
[INFO: config_utils.py:   61]: -------------------------------------------------
Traceback (most recent call last):
  File "D:\python36\new\rcdnn\image\predict.py", line 187, in <module>
    infer(args)
  File "D:\python36\new\rcdnn\image\predict.py", line 90, in infer
    infer_model = models.get_model(args.model_name, infer_config, mode='infer')
  File "D:\python36\new\rcdnn\image\models\model.py", line 191, in get_model
    return model_zoo.get(name, cfg, mode)
  File "D:\python36\new\rcdnn\image\models\model.py", line 179, in get
    raise ModelNotFoundError(name, self.model_zoo.keys())
models.model.ModelNotFoundError: Model AttentionCluster Not Found.
Availiable models:
  NEXTVLAD
```
Except specified the final model path, no other modified.
SO how to solve the problem?
thx

**Comment by ucas010** [comment]
I have tried the model(NEXTVLAD.pdparams), have the same problem
I do not know why

**Comment by ucas010** [comment]
when I solved the up ,comes the down
```
Traceback (most recent call last):
  File "D:\python36\new\rcdnn\image\predict.py", line 187, in <module>
    infer(args)
  File "D:\python36\new\rcdnn\image\predict.py", line 92, in infer
    infer_model.build_model()
  File "D:\python36\new\rcdnn\image\models\nextvlad\nextvlad.py", line 123, in build_model
    eigen_value = np.sqrt(np.load(self.eigen_file)[:1024, 0])
  File "D:\python36\lib\site-packages\numpy\lib\npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
emm,that's why ?
should I modify the input to the model ?
Could I give same frames (image/audio) ?

how to deal with it?
thx

**Comment by ucas010** [comment]
上面那个错误是 因为没有eigen_file ?
这个需要指定位置吗？我没修改代码啊。奇怪。

**Comment by ucas010** [comment]
这个东西在win10上面就不行吗？？
在服务器上用原始代码
```
python predict.py --model_name=NEXTVLAD \
                  --config=configs/nextvlad.yaml \
                  --log_interval=1 \
                  --weights=$PATH_TO_WEIGHTS \
                  --filelist=$FILELIST \
                  --use_gpu=True
```
则没有win10上的那个问题，但有新的问题

```
Traceback (most recent call last):
  File "predict.py", line 200, in <module>
    infer(args)
  File "predict.py", line 119, in infer
    assert os.path.exists(filelist), "{} not exist.".format(filelist)
AssertionError:  not exist.

```

**Comment by ucas010** [comment]
update the problem, now is the down:
```
Traceback (most recent call last):
  File "my_predict.py", line 187, in <module>
    infer(args)
  File "my_predict.py", line 118, in infer
    fluid.default_main_program(), place)
  File "/home/xulm1/xulm1/nextvlad/models-develop/PaddleCV/video/models/model.py", line 158, in load_test_weights
    fluid.load(prog, weights, executor=exe, var_list=params_list)
  File "/data/xulm1/yes/lib/python3.6/site-packages/paddle/fluid/io.py", line 1736, in load
    f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '\x00'.
```
but the **'./NEXTVLAD.pdparams'** model could be load,
the final can't .
that's my problem

**Comment by huangjun12** [comment]
> hi,dear
> the nextvlad_final file can't be load ???
> 
> ```
> [INFO: predict.py:  185]: Namespace(batch_size=1, config='configs/attention_cluster.txt', filelist=None, infer_topk=20, log_interval=1, model_name='AttentionCluster', save_dir='data\\predict_results', use_gpu=False, video_path=None, weights='./NEXTVLAD_final.pdparams')
> [INFO: config_utils.py:   56]: ---------------- Infer Arguments ----------------
> [INFO: config_utils.py:   58]: MODEL:
> [INFO: config_utils.py:   60]:     name:AttentionCluster
> [INFO: config_utils.py:   60]:     dataset:YouTube-8M
> [INFO: config_utils.py:   60]:     bone_network:None
> [INFO: config_utils.py:   60]:     drop_rate:0.5
> [INFO: config_utils.py:   60]:     feature_num:2
> [INFO: config_utils.py:   60]:     feature_names:['rgb', 'audio']
> [INFO: config_utils.py:   60]:     feature_dims:[1024, 128]
> [INFO: config_utils.py:   60]:     seg_num:100
> [INFO: config_utils.py:   60]:     cluster_nums:[32, 32]
> [INFO: config_utils.py:   60]:     num_classes:3862
> [INFO: config_utils.py:   60]:     topk:20
> [INFO: config_utils.py:   60]:     UNIQUE:{'good': 20, 'bad': 30}
> [INFO: config_utils.py:   58]: TRAIN:
> [INFO: config_utils.py:   60]:     epoch:5
> [INFO: config_utils.py:   60]:     learning_rate:0.001
> [INFO: config_utils.py:   60]:     pretrain_base:None
> [INFO: config_utils.py:   60]:     batch_size:2048
> [INFO: config_utils.py:   60]:     use_gpu:True
> [INFO: config_utils.py:   60]:     num_gpus:8
> [INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/train.list
> [INFO: config_utils.py:   58]: VALID:
> [INFO: config_utils.py:   60]:     batch_size:2048
> [INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/val.list
> [INFO: config_utils.py:   58]: TEST:
> [INFO: config_utils.py:   60]:     batch_size:256
> [INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/test.list
> [INFO: config_utils.py:   58]: INFER:
> [INFO: config_utils.py:   60]:     batch_size:1
> [INFO: config_utils.py:   60]:     filelist:data/dataset/youtube8m/infer.list
> [INFO: config_utils.py:   61]: -------------------------------------------------
> Traceback (most recent call last):
>   File "D:\python36\new\rcdnn\image\predict.py", line 187, in <module>
>     infer(args)
>   File "D:\python36\new\rcdnn\image\predict.py", line 90, in infer
>     infer_model = models.get_model(args.model_name, infer_config, mode='infer')
>   File "D:\python36\new\rcdnn\image\models\model.py", line 191, in get_model
>     return model_zoo.get(name, cfg, mode)
>   File "D:\python36\new\rcdnn\image\models\model.py", line 179, in get
>     raise ModelNotFoundError(name, self.model_zoo.keys())
> models.model.ModelNotFoundError: Model AttentionCluster Not Found.
> Availiable models:
>   NEXTVLAD
> ```
> 
> Except specified the final model path, no other modified.
> SO how to solve the problem?
> thx

这个方便贴一下运行的命令吗，看着是运行脚本写错了

**Comment by huangjun12** [comment]
> 上面那个错误是 因为没有eigen_file ?
> 这个需要指定位置吗？我没修改代码啊。奇怪。

eigen_file的路径默认写在yaml文件里了，不用重新指定的

**Comment by huangjun12** [comment]
> 这个东西在win10上面就不行吗？？
> 在服务器上用原始代码
> 
> ```
> python predict.py --model_name=NEXTVLAD \
>                   --config=configs/nextvlad.yaml \
>                   --log_interval=1 \
>                   --weights=$PATH_TO_WEIGHTS \
>                   --filelist=$FILELIST \
>                   --use_gpu=True
> ```
> 
> 则没有win10上的那个问题，但有新的问题
> 
> ```
> Traceback (most recent call last):
>   File "predict.py", line 200, in <module>
>     infer(args)
>   File "predict.py", line 119, in infer
>     assert os.path.exists(filelist), "{} not exist.".format(filelist)
> AssertionError:  not exist.
> ```

filelist为待推断文件列表，需要您创建并指定路径的
