### ISSUE TITLE
TypeError: load() got an unexpected keyword argument 'var_list'

### ISSUE THREAD

**Issue by Mintcat10** [PaddlePaddle/models#4512]
## 1.错误
你好,我在使用NeXtVLAD预训练权重预测的时候出现下面错误:

```
Traceback (most recent call last):
  File "predict.py", line 200, in <module>
    infer(args)
  File "predict.py", line 131, in infer
    fluid.default_main_program(), place)
  File "E:\20200328_img_text\NeXtVLAD\models-develop\PaddleCV\video\models\model.py", line 158, in load_test_weights
    fluid.load(prog, weights, executor=exe, var_list=params_list)
TypeError: load() got an unexpected keyword argument 'var_list'
```
## 2.运行及版本情况
1. 目前使用paddle的版本: 
```
paddlepaddle-gpu 1.6.3.post97
```

2. 运行代码来自:[链接](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/video)

3. 运行命令如下:
```
python predict.py --model_name=NEXTVLAD --config=configs/nextvlad.yaml --log_interval=1 --weights=./data/model/NEXTVLAD.pdparams --filelist=./data/dataset/youtube8m/infer.list --use_gpu=True
```
## 3问题
想问一下是什么原因导致的?

## PS
查看了源代码
[model文件](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/models/model.py)
```
    def load_test_weights(self, exe, weights, prog, place):
        params_list = list(filter(is_parameter, prog.list_vars()))
        fluid.load(prog, weights, executor=exe, var_list=params_list)
```
源代码: Anaconda4.2\envs\Python36\Lib\site-packages\paddle\fluid\io.py
```
def load(program, model_path, executor=None):
```
需要哪个版本的paddle才能兼容?

**Comment by heavengate** [comment]
Paddle 1.7.0和1.7.1已经发布了，使用1.7.0及以上的Paddle版本可以兼容，load接口在1.7版本中新增了这个参数

**Comment by heavengate** [comment]
如果没有问题，当前issue关闭，如果后续有问题可以reopen此issue或提新issue
