### ISSUE TITLE
训练stnet读取kinetics数据集时出线错误 求解决

### ISSUE THREAD

**Issue by jia6214876** [PaddlePaddle/models#4529]
![QQ图片20200414093238](https://user-images.githubusercontent.com/55325034/79176483-eabde700-7e32-11ea-8763-da456262bb26.png)
![QQ图片20200414093322](https://user-images.githubusercontent.com/55325034/79176515-03c69800-7e33-11ea-9748-9a7a30d28323.png)
应该不是路径问题，添加pythonpath也是一样的error

**Comment by ysh329** [comment]
图挂了，看不到，能贴下log嘛

**Comment by ysh329** [comment]
图挂了，看不到，能贴下log嘛

**Comment by jia6214876** [comment]
最后面都是同样的error
(base) krishlo@krishlo-Lenovo-Legion-Y7000P-1060:/media/krishlo/KING/models/PaddleCV/video$ python train.py --model_name=STNET                 --config=./configs/stnet.yaml                 --log_interval=10                 --valid_interval=1                 --use_gpu=True                 --save_dir=./data/checkpoints                 --fix_random_seed=False                 --pretrain=./ResNet50_pretrained |more
[INFO: train.py:  254]: Namespace(batch_size=None, config='./configs/stnet.yaml'
, epoch=None, fix_random_seed=False, is_profiler=0, learning_rate=None, log_inte
rval=10, model_name='STNET', no_memory_optimize=False, pretrain='./ResNet50_pret
rained', profiler_path='./', resume=None, save_dir='./data/checkpoints', use_gpu
=True, valid_interval=1)
[INFO: config_utils.py:   70]: ---------------- Train Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:STNET
[INFO: config_utils.py:   74]:     format:pkl
[INFO: config_utils.py:   74]:     num_classes:400
[INFO: config_utils.py:   74]:     seg_num:7
[INFO: config_utils.py:   74]:     seglen:5
[INFO: config_utils.py:   74]:     image_mean:[0.485, 0.456, 0.406]
[INFO: config_utils.py:   74]:     image_std:[0.229, 0.224, 0.225]
[INFO: config_utils.py:   74]:     num_layers:50
[INFO: config_utils.py:   74]:     topk:5
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     epoch:60
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:224
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     num_gpus:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/train.list
[INFO: config_utils.py:   74]:     learning_rate:0.01
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   74]:     momentum:0.9
[INFO: config_utils.py:   74]:     total_videos:224684
[INFO: config_utils.py:   74]:     pretrain_base:./data/dataset/pretrained/ResNe
t50_pretrained
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:224
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/val.list
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     seg_num:25
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:256
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:4
--More--W0415 13:48:12.649508  6546 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/test.list
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     seg_num:25
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:256
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/infer.list
[INFO: config_utils.py:   74]:     video_path:
[INFO: config_utils.py:   74]:     kinetics_labels:./data/dataset/kinetics_label
--More--W0415 13:48:13.408550  6546 device_context.cc:245] device: 0, cuDNN Version: 7.3.
W0415 13:48:13.408612  6546 device_context.cc:271] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
s.json
[INFO: config_utils.py:   75]: -------------------------------------------------
[INFO: stnet.py:  163]: Load pretrain weights from ./ResNet50_pretrained, exclude fc, batch_norm, xception, conv3d layers.
2020-04-15 13:48:19,295-WARNING: ./ResNet50_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
[WARNING: io.py: 1810]: ./ResNet50_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
[INFO: stnet.py:  173]: Delete fc_0.b_0 from pretrained parameters. Do not load it
[INFO: stnet.py:  173]: Delete fc_0.w_0 from pretrained parameters. Do not load it
[INFO: stnet.py:  179]: conv1_weights is transformed from [Cout, 3, Kh, Kw] into [Cout, 3*seglen, Kh, Kw]
[INFO: accuracy_metrics.py:   34]: Resetting train metrics...
[INFO: accuracy_metrics.py:   34]: Resetting valid metrics...
[INFO: train_utils.py:   46]: ------- learning rate [0.], learning rate counter [-1] -----
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/LQpq2UDLmww_000223_000233.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/-_srAE4uEpo_000003_000013.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/c2TEGerkNKo_000227_000237.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/JsU_kSYA-yE_000113_000123.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/9WEs6jxCV68_000056_000066.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/-3TTZ9RtlwM_000009_000019.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/6EjDCWecjzQ_000514_000524.pkl
[INFO: kinetics_reader.py:  192]: Error when loading ./data_k400/train_pkl/5n1fhuUoOTs_000026_000036.pkl

**Comment by jia6214876** [comment]
补充：用发布的模型进行单视频推断会有下面的提示
python predict.py --model_name=STNET \
>                   --config=./configs/stnet.yaml \
>                   --log_interval=1 \
>                   --weights=STNET.pdparams \
>                   --use_gpu=True \
>                   --video_path=/media/krishlo/KING/models/PaddleCV/video/data/dataset/kinetics/data_k400/val_mp4/abseiling/3caPS4FHFF8.mp4
[INFO: predict.py:  198]: Namespace(batch_size=1, config='./configs/stnet.yaml', filelist=None, infer_topk=20, log_interval=1, model_name='STNET', save_dir='data/predict_results', use_gpu=True, video_path='/media/krishlo/KING/models/PaddleCV/video/data/dataset/kinetics/data_k400/val_mp4/abseiling/3caPS4FHFF8.mp4', weights='STNET.pdparams')
[INFO: config_utils.py:   70]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:STNET
[INFO: config_utils.py:   74]:     format:pkl
[INFO: config_utils.py:   74]:     num_classes:400
[INFO: config_utils.py:   74]:     seg_num:7
[INFO: config_utils.py:   74]:     seglen:5
[INFO: config_utils.py:   74]:     image_mean:[0.485, 0.456, 0.406]
[INFO: config_utils.py:   74]:     image_std:[0.229, 0.224, 0.225]
[INFO: config_utils.py:   74]:     num_layers:50
[INFO: config_utils.py:   74]:     topk:5
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     epoch:60
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:224
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     num_gpus:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/train.list
[INFO: config_utils.py:   74]:     learning_rate:0.01
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   74]:     momentum:0.9
[INFO: config_utils.py:   74]:     total_videos:224684
[INFO: config_utils.py:   74]:     pretrain_base:./data/dataset/pretrained/ResNet50_pretrained
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:224
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/val.list
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     seg_num:25
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:256
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:4
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/test.list
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     seg_num:25
[INFO: config_utils.py:   74]:     short_size:256
[INFO: config_utils.py:   74]:     target_size:256
[INFO: config_utils.py:   74]:     num_reader_threads:12
[INFO: config_utils.py:   74]:     buf_size:1024
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     filelist:./data/dataset/kinetics/infer.list
[INFO: config_utils.py:   74]:     video_path:/media/krishlo/KING/models/PaddleCV/video/data/dataset/kinetics/data_k400/val_mp4/abseiling/3caPS4FHFF8.mp4
[INFO: config_utils.py:   74]:     kinetics_labels:./data/dataset/kinetics_labels.json
[INFO: config_utils.py:   75]: -------------------------------------------------
W0415 15:44:00.417938  3388 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0415 15:44:00.420061  3388 device_context.cc:245] device: 0, cuDNN Version: 7.3.
W0415 15:44:00.420076  3388 device_context.cc:271] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.3, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[INFO: accuracy_metrics.py:   34]: Resetting infer metrics...
[INFO: accuracy_metrics.py:   34]: Resetting infer metrics...
/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "predict.py", line 200, in <module>
    infer(args)
  File "predict.py", line 170, in infer
    feed=infer_feeder.feed(data_feed_in))
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/krishlo/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2663, in batch_norm
    type="batch_norm", inputs=inputs, outputs=outputs, attrs=attrs)
  File "/media/krishlo/KING/models/PaddleCV/video/models/stnet/stnet_res_model.py", line 187, in conv_bn_layer
    moving_variance_name=bn_name + '_variance')
  File "/media/krishlo/KING/models/PaddleCV/video/models/stnet/stnet_res_model.py", line 259, in net
    name='conv1')
  File "/media/krishlo/KING/models/PaddleCV/video/models/stnet/stnet.py", line 88, in build_model
    class_dim=cfg['class_dim'])
  File "predict.py", line 105, in infer
    infer_model.build_model()
  File "predict.py", line 200, in <module>
    infer(args)

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUDNN_STATUS_BAD_PARAM] at (/paddle/paddle/fluid/operators/batch_norm_op.cu:166)

**Comment by xiegegege** [comment]
@jia6214876 请问下你的数据是按readme 生成的吗？麻烦按照https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/data/dataset/README.md#Kinetics数据集 这个链接来下载和处理数据，处理后的每条pkl文件大概几M-20几M不等。还有就是需要确定数据路径是对的。
下面预测时候的报错可能是因为cudnn版本太低了，可以参考 #22510。

**Comment by jia6214876** [comment]
> @jia6214876 请问下你的数据是按readme 生成的吗？麻烦按照[https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/data/dataset/README.md#Kinetics数据集](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/data/dataset/README.md#Kinetics%E6%95%B0%E6%8D%AE%E9%9B%86) 这个链接来下载和处理数据，处理后的每条pkl文件大概几M-几十M不等。还有就是需要确定数据路径是对的。
> 下面预测时候的报错可能是因为cudnn版本太低了，可以参考 [PaddlePaddle/Paddle#22510](https://github.com/PaddlePaddle/Paddle/issues/22510)

原数据集从youtube上下实在太慢所以用的是别人下好的
我的情况和那个问题下面的人说的一样 机器上面的cudann版本是7.6.5 但是提示为7.3

**Comment by xiegegege** [comment]
如果你用别人的数据的话，可能是train.list里的数据路径不是你自己的数据路径，需要修改下。
提示7.3说明你环境的cudnn就是7.3的，可以把高版本的cudnn加到环境变量里，例如：export LD_LIBRARY_PATH=/home/cudnn_v7.5/cuda/lib64:$LD_LIBRARY_PATH

**Comment by jia6214876** [comment]
> 如果你用别人的数据的话，可能是train.list里的数据路径不是你自己的数据路径，需要修改下。
> 提示7.3说明你环境的cudnn就是7.3的，可以把高版本的cudnn加到环境变量里，例如：export LD_LIBRARY_PATH=/home/cudnn_v7.6/cuda/lib64:$LD_LIBRARY_PATH

在.bashrc中添加了export PATH="/usr/local/cuda-10.1/bin:$PATH"
export LD_LIBRARY_PATH="/usr/lcoal/cuda-10.1/lib64:$LD_LIBRARY_PATH"
终端显示：
(base) krishlo@krishlo-Lenovo-Legion-Y7000P-1060:~$ cat /usr/local/cuda-10.1/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

开始predict依然显示版本为7.3 很奇怪

**Comment by xiegegege** [comment]
请问下/usr/lcoal/cuda-10.1/lib64 里面有没有libcudnn.so.7.6.5这个文件呢？或者可以nvidia官网下载一个高版本的cudnn加到环境里

**Comment by jia6214876** [comment]
有的  7.6.5是现在cuda10.1支持的最高版本

**Comment by jia6214876** [comment]
尝试了下7.6.4版本 错误相同

**Comment by xiegegege** [comment]
嗯嗯，我感觉是哪里没设对导致paddle最终运行的环境是cudnn7.3的，建议https://developer.nvidia.com/rdp/cudnn-download 这里重下载一个cudnn7.6，然后export LD_LIBRARY_PATH=/home/cudnn_v7.6/cuda/lib64:$LD_LIBRARY_PATH加入到环境变量里

**Comment by jia6214876** [comment]
按照这个方法下载7.6.0 已成功解决 感谢解答 可能是paddle哪里没有设置好

**Comment by tosonw** [comment]
你好，可以给个数据集链接吗？谢谢！

**Comment by xiegegege** [comment]
> 你好，可以给个数据集链接吗？谢谢！

你好，可以按照https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/data/dataset/README.md#Kinetics数据集  这个链接里的说明准备数据集的

**Comment by tosonw** [comment]
> > 你好，可以给个数据集链接吗？谢谢！
> 
> 你好，可以按照[https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/data/dataset/README.md#Kinetics数据集](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/data/dataset/README.md#Kinetics%E6%95%B0%E6%8D%AE%E9%9B%86) 这个链接里的说明准备数据集的

谢谢，我只要一部分数据集就行，我还是从朋友那里问一下吧
