### ISSUE TITLE
OCR 用attention 训练后，用模型预测报错AssertionError: Can not find [conv2d_0.b_0] in model file 

### ISSUE THREAD

**Issue by MrTsien** [PaddlePaddle/models#4567]
Traceback (most recent call last):
  File "infer.py", line 170, in <module>
    main()
  File "infer.py", line 166, in main
    inference(args)
  File "infer.py", line 91, in inference
    var_list=fluid.io.get_program_parameter(fluid.default_main_program()))
  File "/opt/anaconda3/bin/anaconda/lib/python3.7/site-packages/paddle/fluid/io.py", line 1740, in load
    v.name, parameter_file_name)
AssertionError: Can not find [conv2d_0.b_0] in model file [models/ocr_ctc_attention/model_15000.pdparams]

**Comment by zhupengyang** [comment]
- 用netron打开模型文件，看下保存的模型是不是正常，确认下是不是有conv2d_0.b_0这个节点
- 请确认是否使用```save_inference_model```保存预测模型，是否使用```load_inference_model```加载预测模型

**Comment by MrTsien** [comment]
谢谢
