### ISSUE TITLE
sh run_infer_golden.sh  运行最后出现的错误

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/models#457]
```
Current error rate [wer] = 0.000000
[INFO 2017-11-13 10:31:24,045 infer.py:115] finish inference
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/paddle/code/models/deep_speech_2/data_utils/utility.py", line 121, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/paddle/code/models/deep_speech_2/data_utils/utility.py", line 134, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer

    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
root@8095f1eb2e9a:/paddle/code/models/deep_speech_2/examples/tiny# sh run_infer_golden.sh 

```

**Comment by pkuyym** [comment]
这个是运行完了，不过退出时没有正确杀死进程，新版本已经修复该问题，参考这个PR：https://github.com/PaddlePaddle/models/pull/446
