### ISSUE TITLE
has no attribute 'scale_sub_region'

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/models#459]
```
Traceback (most recent call last):
  File "infer.py", line 126, in <module>
    main()
  File "infer.py", line 122, in main
    infer()
  File "infer.py", line 89, in infer
    share_rnn_weights=args.share_rnn_weights)
  File "/paddle/code/models/deep_speech_2/model_utils/model.py", line 46, in __init__
    rnn_layer_size, use_gru, share_rnn_weights)
  File "/paddle/code/models/deep_speech_2/model_utils/model.py", line 307, in _create_network
    share_rnn_weights=share_rnn_weights)
  File "/paddle/code/models/deep_speech_2/model_utils/network.py", line 263, in deep_speech_v2_network
    index_range_datas=index_range_datas)
  File "/paddle/code/models/deep_speech_2/model_utils/network.py", line 165, in conv_group
    index_range_data=index_range_datas[0])
  File "/paddle/code/models/deep_speech_2/model_utils/network.py", line 43, in conv_bn_layer
    scale_sub_region = paddle.layer.scale_sub_region(
AttributeError: 'module' object has no attribute 'scale_sub_region'

```

**Comment by lezasantaizi** [comment]
![image](https://user-images.githubusercontent.com/7878465/32761049-ebfff2fe-c8b6-11e7-8b99-e5d2561b34bc.png)

@pkuyym

**Comment by kuke** [comment]
@lezasantaizi You need to upgrade PaddlePaddle to the latest version.

**Comment by lezasantaizi** [comment]
已经更新到paddlepaddle (0.10.5)，但是错误仍在
AttributeError: 'module' object has no attribute 'scale_sub_region'

**Comment by lezasantaizi** [comment]
@kuke

**Comment by kuke** [comment]
@lezasantaizi `scale_sub_region`刚加入PaddlePaddle的develop分支，在0.10.5中并没有包含。

**Comment by lezasantaizi** [comment]
okay ，那这个develop分支什么时候上线呢？现在拉下来的代码一运行就挂掉了～
@kuke

**Comment by yangliu2** [comment]
You are probably using the wrong git repo. Use this:
https://github.com/PaddlePaddle/DeepSpeech
instead of the model/deep_speech_2 repo
