### ISSUE TITLE
生成模型的时候出现cannot import name init_on_cpu的错

### ISSUE THREAD

**Issue by BaronChiao** [PaddlePaddle/models#4678]
root@fae-Z370-HD3P:/paddle/models-1.6/PaddleCV/image_classification# ./scripts/train/ResNet50.sh
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    import reader
  File "/paddle/models-1.6/PaddleCV/image_classification/reader.py", line 24, in <module>
    from utils.autoaugment import ImageNetPolicy
  File "/paddle/models-1.6/PaddleCV/image_classification/utils/__init__.py", line 14, in <module>
    from .optimizer import cosine_decay, lr_warmup, cosine_decay_with_warmup, exponential_decay_with_warmup, Optimizer, create_optimizer
  File "/paddle/models-1.6/PaddleCV/image_classification/utils/optimizer.py", line 23, in <module>
    from paddle.fluid.initializer import init_on_cpu
ImportError: cannot import name init_on_cpu

**Comment by BaronChiao** [comment]
另外，请问大佬，我想拿到paddlepaddl的模型，请问怎么拿方便一些呢

**Comment by phlrain** [comment]
看起来是 detection的版本和 paddle版本不一致导致的

**Comment by BaronChiao** [comment]
@phlrain  好像确实是版本不对的原因，现在用的最新版本的models仓库，但是数据集下载不了呀，到网站上也下不了！大佬，你们这边有  生成paddle模型 + 量化  的自动化流程吗
