### ISSUE TITLE
请问度量学习怎么用啊，使用infer.py得到的输出是啥意思呢

### ISSUE THREAD

**Issue by xiaozhaxie777** [PaddlePaddle/models#4714]
看了看infer.py的源码，是把测试集txt里面的图片预测了一下，得到的result是一个一维向量，有些不明白，是需要自己拿两张图的result向量做个比较，计算他的余弦相似度吗？我理解的是输入两张图片，然后输出图片的相似度，希望百度的人能帮忙解答一下，谢谢了。

**Comment by hong19860320** [comment]
不是的哈，对于分类模型，这个一维向量就是这张图片经过推断后在所有类别下的概率，概率值最大类别的就是这个图片推断的分类结果了。

**Comment by xiaozhaxie777** [comment]
> 不是的哈，对于分类模型，这个一维向量就是这张图片经过推断后在所有类别下的概率，概率值最大类别的就是这个图片推断的分类结果了。

嗯，谢谢。那这个其实是一个小样本的多分类网络？我理解的度量学习、还有看paddle网站上的介绍，应该有类似于两张图片相似度这种参数的结果输出吧，还是说就根据概率值最大类别，再做分析？

**Comment by hong19860320** [comment]
> > 不是的哈，对于分类模型，这个一维向量就是这张图片经过推断后在所有类别下的概率，概率值最大类别的就是这个图片推断的分类结果了。
> 
> 嗯，谢谢。那这个其实是一个小样本的多分类网络？我理解的度量学习、还有看paddle网站上的介绍，应该有类似于两张图片相似度这种参数的结果输出吧，还是说就根据概率值最大类别，再做分析？

你说的应该是训练过程中损失函数的确定和loss的计算哈

**Comment by xiaozhaxie777** [comment]
> > > 不是的哈，对于分类模型，这个一维向量就是这张图片经过推断后在所有类别下的概率，概率值最大类别的就是这个图片推断的分类结果了。
> > 
> > 
> > 嗯，谢谢。那这个其实是一个小样本的多分类网络？我理解的度量学习、还有看paddle网站上的介绍，应该有类似于两张图片相似度这种参数的结果输出吧，还是说就根据概率值最大类别，再做分析？
> 
> 你说的应该是训练过程中损失函数的确定和loss的计算哈

又看了看，大概明白了，先用train_elem.py训练，再用train_pair.py微调，但是我微调的时候，出错了。AssertionError: Can not find [_generated_var_0] in model file [output/ResNet50/3000.pdopt]
部分log如下：
python train_pair.py --pretrained_model output/ResNet50/3000
-----------  Configuration Arguments -----------
checkpoint: None
class_dim: 973
display_iter_step: 10
embedding_size: 0
image_shape: 3,224,224
loss_name: eml
lr: 0.0001
lr_steps: 1000
lr_strategy: piecewise_decay
margin: 0.1
model: ResNet50
model_save_dir: output
npairs_reg_lambda: 0.01
pretrained_model: output/ResNet50/3000
samples_each_class: 2
save_iter_step: 1000
test_batch_size: 50
test_iter_step: 500
total_iter_num: 4000
train_batch_size: 64
use_gpu: True
------------------------------------------------
W0623 13:34:35.349243 20958 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W0623 13:34:35.373200 20958 device_context.cc:245] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "train_pair.py", line 310, in <module>
    main()
  File "train_pair.py", line 306, in main
    train_async(args)
  File "train_pair.py", line 198, in train_async
    fluid.load(program=train_prog, model_path=pretrained_model, executor=exe)
  File "/home/zhang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/io.py", line 1761, in load
    v.name, opt_file_name)
AssertionError: Can not find [_generated_var_0] in model file [output/ResNet50/3000.pdopt]

**Comment by a123b12cd** [comment]
> > > 不是的哈，对于分类模型，这个一维向量就是这张图片经过推断后在所有类别下的概率，概率值最大类别的就是这个图片推断的分类结果了。
> > 
> > 
> > 嗯，谢谢。那这个其实是一个小样本的多分类网络？我理解的度量学习、还有看paddle网站上的介绍，应该有类似于两张图片相似度这种参数的结果输出吧，还是说就根据概率值最大类别，再做分析？
> 
> 你说的应该是训练过程中损失函数的确定和loss的计算哈

并不是吧，最后输出的一维向量的维度不是类别的数目，而是网络最后一层的输出。代码中result = exe.run(test_program, fetch_list=fetch_list, feed=data)返回的也是 out = model.net(input=image, embedding_size=args.embedding_size)

**Comment by 821029883** [comment]
> > > > 不是的哈，对于分类模型，这个一维向量就是这张图片经过推断后在所有类别下的概率，概率值最大类别的就是这个图片推断的分类结果了。
> > > 
> > > 
> > > 嗯，谢谢。那这个其实是一个小样本的多分类网络？我理解的度量学习、还有看paddle网站上的介绍，应该有类似于两张图片相似度这种参数的结果输出吧，还是说就根据概率值最大类别，再做分析？
> > 
> > 
> > 你说的应该是训练过程中损失函数的确定和loss的计算哈
> 
> ## 又看了看，大概明白了，先用train_elem.py训练，再用train_pair.py微调，但是我微调的时候，出错了。AssertionError: Can not find [_generated_var_0] in model file [output/ResNet50/3000.pdopt]
> 部分log如下：
> python train_pair.py --pretrained_model output/ResNet50/3000
> ----------- Configuration Arguments -----------
> checkpoint: None
> class_dim: 973
> display_iter_step: 10
> embedding_size: 0
> image_shape: 3,224,224
> loss_name: eml
> lr: 0.0001
> lr_steps: 1000
> lr_strategy: piecewise_decay
> margin: 0.1
> model: ResNet50
> model_save_dir: output
> npairs_reg_lambda: 0.01
> pretrained_model: output/ResNet50/3000
> samples_each_class: 2
> save_iter_step: 1000
> test_batch_size: 50
> test_iter_step: 500
> total_iter_num: 4000
> train_batch_size: 64
> use_gpu: True
> 
> W0623 13:34:35.349243 20958 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
> W0623 13:34:35.373200 20958 device_context.cc:245] device: 0, cuDNN Version: 7.6.
> Traceback (most recent call last):
> File "train_pair.py", line 310, in
> main()
> File "train_pair.py", line 306, in main
> train_async(args)
> File "train_pair.py", line 198, in train_async
> fluid.load(program=train_prog, model_path=pretrained_model, executor=exe)
> File "/home/zhang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/io.py", line 1761, in load
> v.name, opt_file_name)
> AssertionError: Can not find [_generated_var_0] in model file [output/ResNet50/3000.pdopt]

我这边碰到同样问题：
已解决：
在pretrained_model:最后位置添加 /
