### ISSUE TITLE
GRU model under dygraph can't work now!

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/models#4723]
```
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    epoch_num=args.epoch_num)
  File "train.py", line 58, in train_without_distill
    _, logits_s = model(ids_student)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/go/src/github.com/paddlepaddle/edl/example/distill/nlp/nets.py", line 215, in forward
    emb = emb * mask_emb
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 198, in __impl__
    return math_op(self, other_var, 'axis', axis)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 122, 128] and the shape of Y = [1952, 128]. Received [122] in X is not equal to [1952] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:157)
```

**Comment by willthefrog** [comment]
can you take a look at this? @kuke
