### ISSUE TITLE
使用BMN预训练模型训练的时候报错

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/models#4749]
DALI is not installed, you can improve performance if use DALI
[INFO: train.py:  254]: Namespace(batch_size=None, config='./configs/bmn.yaml', epoch=None, fix_random_seed=False, is_profiler=0, learning_rate=None, log_interval=10, model_name='BMN', no_memory_optimize=False, pretrain='data/dataset/bmn/BMN.pdparams', profiler_path='./', resume=None, save_dir='./data/checkpoints', use_gpu=True, valid_interval=1)
[INFO: config_utils.py:   70]: ---------------- Train Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:100
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:400
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:32
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:data/dataset/bmn/trainlabel.json
[INFO: config_utils.py:   74]:     feat_path:data/dataset/bmn/videofeature
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:10
[INFO: config_utils.py:   74]:     batch_size:8
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:1
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:8
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:1
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:data/dataset/bmn/infer1.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
W0713 13:21:17.239037 25735 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0713 13:21:17.242261 25735 device_context.cc:260] device: 0, cuDNN Version: 7.3.
[INFO: model.py:  152]: Load pretrain weights from data/dataset/bmn/BMN.pdparams
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    train(args)
  File "train.py", line 174, in train
    train_model.load_pretrain_params(exe, pretrain, train_prog, place)
  File "/home/aistudio/models-release-1.8/PaddleCV/video/models/model.py", line 154, in load_pretrain_params
    fluid.set_program_state(prog, state_dict)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1967, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((100, 32, 100, 100)), while the loaded parameter (namely [ sample_mask ]) has a shape of  ((100, 320000)).

**Comment by ForFishes** [comment]
从错误看，是热启参数的维度与参数维度不一致，但看参数个数是一样的，应该需要reshape一下组网中var的维度到(100, 320000)

**Comment by liu824** [comment]
具体在哪改呢？我试过在BMN中对输入参数进行reshape，但是仍然报错。

**Comment by ForFishes** [comment]
> 具体在哪改呢？我试过在BMN中对输入参数进行reshape，但是仍然报错。

我的意思是找到a parameter with the shape of ((100, 32, 100, 100)),renshape到 ((100, 320000))。

**Comment by chajchaj** [comment]
请问您的问题解决了吗？
我们基于paddle2.0发布了更加易用的repo：https://github.com/PaddlePaddle/PaddleVideo， 里面包含BMN，欢迎使用、Star、Issue、PR~
