### ISSUE TITLE
#face detection# Error: Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by ftraining** [PaddlePaddle/models#4754]
```bash
2020-07-16 11:17:11,664-WARNING: paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
-----------  Configuration Arguments -----------
batch_num: None
batch_size: 16
data_dir: data
enable_ce: False
epoc_num: 160
learning_rate: 0.001
mean_BGR: 104., 117., 123.
model_save_dir: output
num_devices: 1
parallel: True
pretrained_model: ./vgg_ilsvrc_16_fc_reduced/
resize_h: 640
resize_w: 640
use_gpu: True
use_multiprocess: False
use_pyramidbox: True
------------------------------------------------
2020-07-16 11:17:12,392-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-07-16 11:17:17,149-WARNING: Your decorated reader has raised an exception!
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\layers\io.py", line 496, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\layers\io.py", line 477, in __provider_thread__
    for tensors in func():
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\layers\io.py", line 528, in __tensor_provider__
    for slots in paddle_reader():
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "E:\Sourcecode\models-release-1.8\PaddleCV\face_detection\reader.py", line 270, in reader
    image_path)
  File "E:\Sourcecode\models-release-1.8\PaddleCV\face_detection\reader.py", line 154, in preprocess
    Image.BILINEAR, Image.HAMMING, Image.NEAREST, Image.BICUBIC,
AttributeError: module 'PIL.Image' has no attribute 'HAMMING'

D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "E:/Sourcecode/models-release-1.8/PaddleCV/face_detection/train.py", line 297, in <module>
    train(args, config, train_parameters, train_file_list)
  File "E:/Sourcecode/models-release-1.8/PaddleCV/face_detection/train.py", line 225, in train
    [v.name for v in fetches])
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\parallel_executor.py", line 303, in run
    return_numpy=return_numpy)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\lib\site-packages\six.py", line 686, in reraise
    raise value
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\layers\io.py", line 894, in read_file
    type='read', inputs={'Reader': [reader]}, outputs={'Out': out})
  File "E:/Sourcecode/models-release-1.8/PaddleCV/face_detection/train.py", line 114, in build_program
    image, face_box, head_box, gt_label = fluid.layers.read_file(py_reader)
  File "E:/Sourcecode/models-release-1.8/PaddleCV/face_detection/train.py", line 166, in train
    args=args)
  File "E:/Sourcecode/models-release-1.8/PaddleCV/face_detection/train.py", line 297, in <module>
    train(args, config, train_parameters, train_file_list)

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
```

**Comment by baiyfbupt** [comment]
您好，是否改动了face_detection代码呢？

**Comment by baiyfbupt** [comment]
>AttributeError: module 'PIL.Image' has no attribute 'HAMMING'

看log是PIL版本问题，建议把PIL更新到最新版本再试试

**Comment by ftraining** [comment]
你好，没改动代码。




在 2020-07-16 18:46:28，"Bai Yifan" <notifications@github.com> 写道：

您好，是否改动了face_detection代码呢？
