### ISSUE TITLE
Can not find library pointnet_lib.so pycharm 

### ISSUE THREAD

**Issue by jakeju92** [PaddlePaddle/models#4767]
OS: Ubuntu 16.04
g++: 4.8
paddle: 1.8.1.post107
CUDA: 10.1

你好，

我在PointNet++成功编译pointnet_util.so动态库之后，termial中运行test也都通过的情况下，但是在pycharm中运行test会报错:
```
W0724 15:14:30.073087 1176505 dynamic_loader.cc:120] Can not find library: /home/jake/Documents/paddle/models/PaddleCV/3d_vision/PointNet++/ext_op/src/pointnet_lib.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
Traceback (most recent call last):
  File "/home/jake/Documents/paddle/models/PaddleCV/3d_vision/VoteNet/ext_op/tests/test_farthest_point_sampling_op.py", line 23, in <module>
    import pointnet_lib
  File "../pointnet_lib.py", line 19, in <module>
    fluid.load_op_library(os.path.join(file_dir, 'src/pointnet_lib.so'))
  File "/home/jake/anaconda3/envs/paddle-dev/lib/python3.7/site-packages/paddle/fluid/framework.py", line 5162, in load_op_library
    core.load_op_library(lib_filename)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::dynload::GetOpDsoHandle(std::string const&)
3   paddle::framework::LoadOpLib(std::string const&)

----------------------
Error Message Summary:
----------------------
Error: Failed to find dynamic library: /home/jake/Documents/paddle/models/PaddleCV/3d_vision/PointNet++/ext_op/src/pointnet_lib.so ( libpaddle_framework.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)
```
能帮忙看看是怎么回事吗？谢谢！

**Comment by qingqing01** [comment]
@jb892   将pointnet_lib.so以及`paddle.sysconfig.get_lib()`路径配置下环境变量LD_LIBRARY_PATH中试下，在pycharm可以参考：  https://www.jianshu.com/p/385a408024d1
