### ISSUE TITLE
model/text_classification 使用内置语料集训练模型后，预测时出错，具体如下

### ISSUE THREAD

**Issue by yatouxingren** [PaddlePaddle/models#489]
```text
I1123 09:23:54.320137    84 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
Traceback (most recent call last):
  File "infer.py", line 91, in <module>
    batch_size=10)
  File "infer.py", line 58, in infer
    for idx, item in enumerate(test_reader):
TypeError: 'function' object is not iterable
```
paddle镜像用的是https://hub.docker.com/r/paddlepaddle/paddle/tags/ latest的，model下载的最新的

**Comment by QiJune** [comment]
我来尝试复现一下该问题

**Comment by QiJune** [comment]
@yatouxingren 这里是一个bug，我来修复一下 #492
