### ISSUE TITLE
emotion_detection 运行ernie evaluate报错

### ISSUE THREAD

**Issue by zhangxuanaj** [PaddlePaddle/models#4958]
models/PaddleNLP/emotion_detection/run_ernie.sh   train完成后，运行eval报错，看报错信息，应该是在fluid.load(main_program, init_checkpoint_path, exe) 的时候出错了，error信息：

Error: When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::dims, or Tensor::Resize has been called first. The Tensor's shape is [-1, 768] now
  [Hint: Expected numel() >= 0, but received numel():-768 < 0:0.] at (/paddle/paddle/fluid/framework/tensor.cc:45)

**Comment by Joejiong** [comment]
好的正在查看

**Comment by Joejiong** [comment]
好的谢谢，请，按模版填写一下，你的用户环境，和可以复现的代码。

**Comment by zhangxuanaj** [comment]
> 好的谢谢，请，按模版填写一下，你的用户环境，和可以复现的代码。

就是这个原始代码，没改动，1.8版本。

**Comment by Joejiong** [comment]
@kuke 麻烦帮忙看下谢谢

**Comment by zhangxuanaj** [comment]
W1201 19:50:31.103739 19889 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 10.1, Runtime API Version: 10.0
W1201 19:50:31.109172 19889 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "run_ernie_classifier.py", line 402, in <module>
    main(args)
  File "run_ernie_classifier.py", line 303, in main
    main_program=test_prog)
  File "/home/ssd5/zhangxuan28/paddle/models-release-1.8/PaddleNLP/emotion_detection/utils.py", line 37, in init_checkpoint
    fluid.load(main_program, init_checkpoint_path, exe)
  File "/home/ssd4/weixiaochi/python_env/python_env/python3.paddle.1.8.1/lib/python3.7/site-packages/paddle/fluid/io.py", line 1778, in load
    optimizer_var_list, global_scope(), executor._default_executor)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)




----------------------
Error Message Summary:
----------------------
Error: When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::dims, or Tensor::Resize has been called first. The Tensor's shape is [-1, 768] now
  [Hint: Expected numel() >= 0, but received numel():-768 < 0:0.] at (/paddle/paddle/fluid/framework/tensor.cc:45)

**Comment by zhangxuanaj** [comment]
全部报错信息：

W1201 19:50:31.103739 19889 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 10.1, Runtime API Version: 10.0
W1201 19:50:31.109172 19889 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "run_ernie_classifier.py", line 402, in <module>
    main(args)
  File "run_ernie_classifier.py", line 303, in main
    main_program=test_prog)
  File "/home/ssd5/zhangxuan28/paddle/models-release-1.8/PaddleNLP/emotion_detection/utils.py", line 37, in init_checkpoint
    fluid.load(main_program, init_checkpoint_path, exe)
  File "/home/ssd4/weixiaochi/python_env/python_env/python3.paddle.1.8.1/lib/python3.7/site-packages/paddle/fluid/io.py", line 1778, in load
    optimizer_var_list, global_scope(), executor._default_executor)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)

----------------------
Error Message Summary:
----------------------
Error: When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::dims, or Tensor::Resize has been called first. The Tensor's shape is [-1, 768] now
  [Hint: Expected numel() >= 0, but received numel():-768 < 0:0.] at (/paddle/paddle/fluid/framework/tensor.cc:45)

**Comment by xiaosheng123XIAO** [comment]
请问一下，这个问题解决了吗，我也遇到同样的问题啦
