### ISSUE TITLE
How can I load a pretrained model in AttentionCluster to train my own data?

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/models#4972]
Hi,

I am using the AttentionCluster to train my model, linked here.

I download the released model for finetuning. The model only has an AttentionCluster.pdparams file, but no AttentionCluster.pdopt. 

And it shows 
`AssertionError: Optimizer file [./AttentionCluster.pdopt] not exits`

When I set pretrain="AttentionCluster.pdparams", it shows the shape does not match, because my class num is 12.
```
Traceback (most recent call last):
  File "train_shenfen.py", line 259, in <module>
    train(args)
  File "train_shenfen.py", line 174, in train
    train_model.load_pretrain_params(exe, pretrain, train_prog, place)
  File ".../models/model.py", line 154, in load_pretrain_params
    fluid.set_program_state(prog, state_dict)
  File ".../python3.6/site-packages/paddle/fluid/io.py", line 1968, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((4096, 12)), while the loaded parameter (namely [ logistic.weights ]) has a shape of  ((4096, 3862)).
```

So.. When I want to resume a model for finetuning, I do not have a pdopt file, and when I want to load a pretrained model, the shape does not match..

**Comment by p1n0cch10** [comment]
I find a pretrain model here, https://paddlepaddle.org.cn/support/news?action=detail&id=889
The files look like this
![image](https://user-images.githubusercontent.com/22934323/100183999-5d3f8b00-2f1b-11eb-80b4-7d77f0726b70.png)

It still show the parameter's shape does not match. As my data has 12 classes, instead of 3862, can I ignore the paremeters in the output layer?

Here is the config
MODEL:
    name: "AttentionCluster"
    dataset: "YouTube-8M"
    bone_network: None
    drop_rate: 0.5 
    feature_num: 2
    feature_names: ['rgb', 'audio']
    feature_dims: [1024, 128]
    seg_num: 100 
    cluster_nums: [32, 32] 
    num_classes: 12
    topk: 20
    UNIQUE:
        good: 20
        bad: 30

TRAIN:
    epoch: 100 
    learning_rate: 0.001
    pretrain_base: None
    #batch_size: 2048
    batch_size: 128 
    use_gpu: True
    #num_gpus: 8
    num_gpus: 1
    filelist: "data/dataset/youtube8m/train.list"

VALID:
    #batch_size: 2048
    batch_size: 128 
    filelist: "data/dataset/youtube8m/train.list"

TEST:
    #batch_size: 256
    batch_size: 128 
    filelist: "data/dataset/youtube8m/train.list"

INFER:
    batch_size: 1
    filelist: "data/dataset/youtube8m/train.list"


Here is the log.
DALI is not installed, you can improve performance if use DALI
[INFO: train_shenfen.py:  254]: Namespace(batch_size=None, config='./configs/attention_cluster.yaml', epoch=None, fix_random_seed=False, is_profiler=0, learning_rate=None, log_interval=1, model_name='AttentionCluster', no_memory_optimize=False, pretrain='./resumes/attention_cluster_youtube8m', profiler_path='./', resume=None, save_dir='./data/checkpoints', use_gpu=True, valid_interval=1)
[INFO: config_utils.py:   70]: ---------------- Train Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:AttentionCluster
[INFO: config_utils.py:   74]:     dataset:YouTube-8M
[INFO: config_utils.py:   74]:     bone_network:None
[INFO: config_utils.py:   74]:     drop_rate:0.5
[INFO: config_utils.py:   74]:     feature_num:2
[INFO: config_utils.py:   74]:     feature_names:['rgb', 'audio']
[INFO: config_utils.py:   74]:     feature_dims:[1024, 128]
[INFO: config_utils.py:   74]:     seg_num:100
[INFO: config_utils.py:   74]:     cluster_nums:[32, 32]
[INFO: config_utils.py:   74]:     num_classes:12
[INFO: config_utils.py:   74]:     topk:20
[INFO: config_utils.py:   74]:     UNIQUE:{'good': 20, 'bad': 30}
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     epoch:100
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     pretrain_base:None
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:1
[INFO: config_utils.py:   74]:     filelist:data/dataset/youtube8m/train.list
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     filelist:data/dataset/youtube8m/train.list
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     batch_size:128
[INFO: config_utils.py:   74]:     filelist:data/dataset/youtube8m/train.list
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     filelist:data/dataset/youtube8m/train.list
[INFO: config_utils.py:   75]: -------------------------------------------------
W1125 12:37:15.681217 54923 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 9.0
W1125 12:37:15.684935 54923 device_context.cc:260] device: 0, cuDNN Version: 7.0.
W1125 12:37:17.341135 54923 device_context.h:155] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[INFO: model.py:  152]: Load pretrain weights from ./resumes/attention_cluster_youtube8m
2020-11-25 12:37:18,821-WARNING: ./resumes/attention_cluster_youtube8m.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
  File "train.py", line 259, in <module>
    train(args)
  File "train.py", line 174, in train
    train_model.load_pretrain_params(exe, pretrain, train_prog, place)
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/models/PaddleCV/video/models/model.py", line 154, in load_pretrain_params
    fluid.set_program_state(prog, state_dict)
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/io.py", line 1968, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Parameter's shape does not match, the Program requires a parameter with the shape of ((4096, 12)), while the loaded parameter (namely [ logistic.weights ]) has a shape of  ((4096, 3862)).

**Comment by huangjun12** [comment]
We recommand to load a pretrained model to resume. The problem of "shape not match"  can be fixed this by removing fc layer weight when loading a pretrain model. Please refer to  https://github.com/PaddlePaddle/models/blob/0687ceb6e186ef86e24f32f94d39c3d2fce42a2f/PaddleCV/video/application/video_tag/models/attention_lstm/attention_lstm.py#L170
