### ISSUE TITLE
We only support '%s()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode." % func.__name__

### ISSUE THREAD

**Issue by wwdok** [PaddlePaddle/models#5103]
我按照BMN的[README](https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/video/models/bmn/README.md)教程做,到运行`bash run.sh predict BMN ./configs/bmn.yaml`时遇到如下报错,请问如何debug,谢谢!

```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/PaddlePaddle/models/PaddleCV/video$ bash run.sh predict BMN ./configs/bmn.yaml
predict BMN ./configs/bmn.yaml
DALI is not installed, you can improve performance if use DALI
[INFO: predict.py:  198]: Namespace(batch_size=1, config='./configs/bmn.yaml', filelist=None, infer_topk=20, log_interval=1, model_name='BMN', save_dir='data/predict_results', use_gpu=True, video_path='', weights=None)
[INFO: config_utils.py:   70]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:100
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:400
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:32
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:data/dataset/bmn/activitynet_1.3_annotations.json
[INFO: config_utils.py:   74]:     feat_path:/media/weidawang/DATA/dataset/ActionLocalization/bmn_feat
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:9
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:data/dataset/bmn/infer.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
Traceback (most recent call last):
  File "predict.py", line 200, in <module>
    infer(args)
  File "predict.py", line 104, in infer
    infer_model.build_input(use_dataloader=False)
  File "/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/models/bmn/bmn.py", line 69, in build_input
    feat = fluid.data(name='feat', shape=feat_shape, dtype='float32')
  File "<decorator-gen-25>", line 2, in data
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 232, in __impl__
    ), "We only support '%s()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode." % func.__name__
```

**Comment by wwdok** [comment]
我运行TALL也遇到了同样的问题,请问两者是不是相同的原因呢?
```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/PaddlePaddle/models/PaddleCV/video$ bash run.sh predict TALL ./configs/tall.yaml
predict TALL ./configs/tall.yaml
DALI is not installed, you can improve performance if use DALI
[INFO: predict.py:  198]: Namespace(batch_size=1, config='./configs/tall.yaml', filelist=None, infer_topk=20, log_interval=1, model_name='TALL', save_dir='data/predict_results', use_gpu=True, video_path='', weights=None)
[INFO: config_utils.py:   70]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:TALL
[INFO: config_utils.py:   74]:     visual_feature_dim:12288
[INFO: config_utils.py:   74]:     sentence_embedding_size:4800
[INFO: config_utils.py:   74]:     semantic_size:1024
[INFO: config_utils.py:   74]:     hidden_size:1000
[INFO: config_utils.py:   74]:     output_size:3
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     epoch:25
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:1
[INFO: config_utils.py:   74]:     batch_size:56
[INFO: config_utils.py:   74]:     off_size:2
[INFO: config_utils.py:   74]:     clip_norm:5.0
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     semantic_size:1024
[INFO: config_utils.py:   74]:     feats_dimen:4096
[INFO: config_utils.py:   74]:     context_num:1
[INFO: config_utils.py:   74]:     context_size:128
[INFO: config_utils.py:   74]:     sent_vec_dim:4800
[INFO: config_utils.py:   74]:     sliding_clip_path:./data/dataset/tall/Interval64_128_256_512_overlap0.8_c3d_fc6/
[INFO: config_utils.py:   74]:     clip_sentvec:./data/dataset/tall/train_clip-sentvec.pkl
[INFO: config_utils.py:   74]:     movie_length_info:./data/dataset/tall/video_allframes_info.pkl
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:1
[INFO: config_utils.py:   74]:     batch_size:56
[INFO: config_utils.py:   74]:     off_size:2
[INFO: config_utils.py:   74]:     clip_norm:5.0
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     semantic_size:1024
[INFO: config_utils.py:   74]:     feats_dimen:4096
[INFO: config_utils.py:   74]:     context_num:1
[INFO: config_utils.py:   74]:     context_size:128
[INFO: config_utils.py:   74]:     sent_vec_dim:4800
[INFO: config_utils.py:   74]:     sliding_clip_path:./data/dataset/tall/Interval64_128_256_512_overlap0.8_c3d_fc6/
[INFO: config_utils.py:   74]:     clip_sentvec:./data/dataset/tall/train_clip-sentvec.pkl
[INFO: config_utils.py:   74]:     movie_length_info:./data/dataset/tall/video_allframes_info.pkl
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     feats_dimen:4096
[INFO: config_utils.py:   74]:     context_num:1
[INFO: config_utils.py:   74]:     context_size:128
[INFO: config_utils.py:   74]:     sent_vec_dim:4800
[INFO: config_utils.py:   74]:     semantic_size:4800
[INFO: config_utils.py:   74]:     sliding_clip_path:./data/dataset/tall/Interval128_256_overlap0.8_c3d_fc6/
[INFO: config_utils.py:   74]:     clip_sentvec:./data/dataset/tall/test_clip-sentvec.pkl
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     feats_dimen:4096
[INFO: config_utils.py:   74]:     context_num:1
[INFO: config_utils.py:   74]:     context_size:128
[INFO: config_utils.py:   74]:     sent_vec_dim:4800
[INFO: config_utils.py:   74]:     semantic_size:4800
[INFO: config_utils.py:   74]:     filelist:./data/dataset/tall/infer
[INFO: config_utils.py:   74]:     sliding_clip_path:./data/dataset/tall/infer/infer_feat
[INFO: config_utils.py:   74]:     clip_sentvec:./data/dataset/tall/infer/infer_clip-sen.pkl
[INFO: config_utils.py:   75]: -------------------------------------------------
Traceback (most recent call last):
  File "predict.py", line 200, in <module>
    infer(args)
  File "predict.py", line 104, in infer
    infer_model.build_input(use_dataloader=False)
  File "/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/models/tall/tall.py", line 64, in build_input
    name='train_visual', shape=[None, visual_shape], dtype='float32')
  File "<decorator-gen-25>", line 2, in data
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 232, in __impl__
    ), "We only support '%s()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode." % func.__name__
AssertionError: We only support 'data()' in static graph mode, please call 'paddle.enable_static()' to enter static graph mode.
```

**Comment by wwdok** [comment]
```
import paddle
paddle.enable_static()
```
可解决
