### ISSUE TITLE
Optimizer file [/home/weidawang/.paddle/weights/BMN.pdopt] not exits

### ISSUE THREAD

**Issue by wwdok** [PaddlePaddle/models#5115]
I got error when i am getting started with BMN:

```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/PaddlePaddle/models/PaddleCV/video$ bash run.sh predict BMN ./configs/bmn.yaml
predict BMN ./configs/bmn.yaml
DALI is not installed, you can improve performance if use DALI
[INFO: predict.py:  199]: Namespace(batch_size=1, config='./configs/bmn.yaml', filelist=None, infer_topk=20, log_interval=1, model_name='BMN', save_dir='data/predict_results', use_gpu=True, video_path='', weights=None)
[INFO: config_utils.py:   70]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:100
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:400
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:32
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:data/dataset/bmn/activitynet_1.3_annotations.json
[INFO: config_utils.py:   74]:     feat_path:/media/weidawang/DATA/dataset/ActionLocalization/bmn_feat
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:9
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:data/dataset/bmn/infer.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
W1218 16:29:50.778240 31472 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.2
W1218 16:29:50.779249 31472 device_context.cc:346] device: 0, cuDNN Version: 8.0.
test subset video numbers: 5
Traceback (most recent call last):
  File "predict.py", line 201, in <module>
    infer(args)
  File "predict.py", line 132, in infer
    fluid.default_main_program(), place)
  File "/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/models/model.py", line 158, in load_test_weights
    fluid.load(prog, weights, executor=exe, var_list=params_list)
  File "<decorator-gen-76>", line 2, in load
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 215, in __impl__
    return func(*args, **kwargs)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/io.py", line 1882, in load
    "Optimizer file [{}] not exits".format(opt_file_name)
AssertionError: Optimizer file [/home/weidawang/.paddle/weights/BMN.pdopt] not exits
```

**Comment by sandyhouse** [comment]
> AssertionError: Optimizer file [/home/weidawang/.paddle/weights/BMN.pdopt] not exits

确认下这个文件是否存在

**Comment by wwdok** [comment]
不存在的话，应该去哪里下载呢？谢谢！

**Comment by sandyhouse** [comment]
这是什么模型？相关模型的README里面是否有介绍？

**Comment by wwdok** [comment]
是这个模型：https://github.com/PaddlePaddle/models/blob/release/2.0-beta/PaddleCV/video/models/bmn/README.md

**Comment by sandyhouse** [comment]
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/6737864/102792675-cb288680-43e3-11eb-9daf-51dd66fb7fb5.png">
REAME里面有说明呀。可以通过model连接下载参数，然后通过weight参数指定就可以了。

**Comment by wwdok** [comment]
那个model链接下载出来是BMN.pdparams，不是BMN.pdopt，`--weights`应该指定`.pdparams`还是.`pdopt`呢，谢谢

**Comment by sandyhouse** [comment]
按照我的理解weights应该指定.pdparams，你可以先试一下，如果不行的话我找负责同学帮忙看一下。

**Comment by wwdok** [comment]
嗯嗯好的，我明天试试~

**Comment by wwdok** [comment]
你好,我刚刚尝试明确指定weights参数了,但还是报错,似乎BMN.pdopt是必不可缺的:

```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:~/Repo/PaddlePaddle/models/PaddleCV/video$ python predict.py --model_name=BMN --config=./configs/bmn.yaml  --log_interval=1 --filelist=/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/data/dataset/bmn/infer.list --use_gpu=True --weights=weights/BMN.pdparams
DALI is not installed, you can improve performance if use DALI
[INFO: predict.py:  199]: Namespace(batch_size=1, config='./configs/bmn.yaml', filelist='/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/data/dataset/bmn/infer.list', infer_topk=20, log_interval=1, model_name='BMN', save_dir='data/predict_results', use_gpu=True, video_path=None, weights='weights/BMN.pdparams')
[INFO: config_utils.py:   70]: ---------------- Infer Arguments ----------------
[INFO: config_utils.py:   72]: MODEL:
[INFO: config_utils.py:   74]:     name:BMN
[INFO: config_utils.py:   74]:     tscale:100
[INFO: config_utils.py:   74]:     dscale:100
[INFO: config_utils.py:   74]:     feat_dim:400
[INFO: config_utils.py:   74]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   74]:     num_sample:32
[INFO: config_utils.py:   74]:     num_sample_perbin:3
[INFO: config_utils.py:   74]:     anno_file:data/dataset/bmn/activitynet_1.3_annotations.json
[INFO: config_utils.py:   74]:     feat_path:/media/weidawang/DATA/dataset/ActionLocalization/bmn_feat
[INFO: config_utils.py:   72]: TRAIN:
[INFO: config_utils.py:   74]:     subset:train
[INFO: config_utils.py:   74]:     epoch:9
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   74]:     learning_rate:0.001
[INFO: config_utils.py:   74]:     learning_rate_decay:0.1
[INFO: config_utils.py:   74]:     lr_decay_iter:4200
[INFO: config_utils.py:   74]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   72]: VALID:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:16
[INFO: config_utils.py:   74]:     num_threads:8
[INFO: config_utils.py:   74]:     use_gpu:True
[INFO: config_utils.py:   74]:     num_gpus:4
[INFO: config_utils.py:   72]: TEST:
[INFO: config_utils.py:   74]:     subset:validation
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.001
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     output_path:data/output/EVAL/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/evaluate_results
[INFO: config_utils.py:   72]: INFER:
[INFO: config_utils.py:   74]:     subset:test
[INFO: config_utils.py:   74]:     batch_size:1
[INFO: config_utils.py:   74]:     num_threads:1
[INFO: config_utils.py:   74]:     snms_alpha:0.4
[INFO: config_utils.py:   74]:     snms_t1:0.5
[INFO: config_utils.py:   74]:     snms_t2:0.9
[INFO: config_utils.py:   74]:     filelist:/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/data/dataset/bmn/infer.list
[INFO: config_utils.py:   74]:     output_path:data/output/INFER/BMN_results
[INFO: config_utils.py:   74]:     result_path:data/predict_results
[INFO: config_utils.py:   75]: -------------------------------------------------
W1222 09:34:47.967705   786 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.2
W1222 09:34:47.968752   786 device_context.cc:346] device: 0, cuDNN Version: 8.0.
test subset video numbers: 5
Traceback (most recent call last):
  File "predict.py", line 201, in <module>
    infer(args)
  File "predict.py", line 132, in infer
    fluid.default_main_program(), place)
  File "/home/weidawang/Repo/PaddlePaddle/models/PaddleCV/video/models/model.py", line 158, in load_test_weights
    fluid.load(prog, weights, executor=exe, var_list=params_list)
  File "<decorator-gen-76>", line 2, in load
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 215, in __impl__
    return func(*args, **kwargs)
  File "/home/weidawang/miniconda3/lib/python3.7/site-packages/paddle/fluid/io.py", line 1882, in load
    "Optimizer file [{}] not exits".format(opt_file_name)
AssertionError: Optimizer file [weights/BMN.pdopt] not exits
```

**Comment by huangjun12** [comment]
有如下解决方案供您参考:
(1) 推荐您使用我们的动态图实现: https://github.com/PaddlePaddle/models/tree/develop/dygraph/bmn
训练好的参数文件可从[这里](https://paddlemodels.bj.bcebos.com/hapi/bmn.pdparams)下载；
(2) 您可以修改fluid.load接口为fluid.load_program_state，示例代码参考:
https://github.com/PaddlePaddle/models/blob/d111569654555efdc5cf8e11d709d70aedd95c37/PaddleCV/video/application/video_tag/models/tsn/tsn.py#L150；
(3) 您可以参考静态图下的教程训练BMN模型，得到pdopt参数文件进行推断。

**Comment by wwdok** [comment]
谢谢巨佬,您的回答太周到了!用第一个动态图的方法我这边能跑通了,谢谢!
