### ISSUE TITLE
视频分类模型STNET训练问题

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/models#5148]
用自己的数据训练STNET模型，视频数据是两分类问题，报错信息如下：
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train(args)
  File "train.py", line 247, in train
    profiler_path=args.profiler_path)
  File "/home/aistudio/work/models/PaddleCV/video/utils/train_utils.py", line 135, in train_with_dataloader
    str_time, epoch, train_iter, time_info_str))
  File "/home/aistudio/work/models/PaddleCV/video/metrics/metrics_util.py", line 141, in calculate_and_log_out
    acc1, acc5 = self.calculator.calculate_metrics(loss, pred, label)
  File "/home/aistudio/work/models/PaddleCV/video/metrics/kinetics/accuracy_metrics.py", line 54, in calculate_metrics
    accuracy5 = compute_topk_accuracy(softmax, labels, top_k=5) * 100.
  File "/home/aistudio/work/models/PaddleCV/video/metrics/kinetics/accuracy_metrics.py", line 101, in compute_topk_accuracy
    aggr_top_k_correct_hits = compute_topk_correct_hits(top_k, softmax, labels)
  File "/home/aistudio/work/models/PaddleCV/video/metrics/kinetics/accuracy_metrics.py", line 84, in compute_topk_correct_hits
    top_k_preds[i, :] = np.argsort(-preds[i, :])[:top_k]
ValueError: could not broadcast input array from shape (2) into shape (5)

**Comment by pele228** [comment]
MODEL:
    name: "STNET"
    format: "pkl"
    num_classes: 2
    seg_num: 7
    seglen: 5
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    topk: 2

TRAIN:
    epoch: 60
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 32
    num_gpus: 1
    use_gpu: True
    filelist: "data/dataset/mydata/train.list"
    learning_rate: 0.01
    learning_rate_decay: 0.1
    l2_weight_decay: 1e-4
    momentum: 0.9
    total_videos: 4000
    pretrain_base: "./data/dataset/pretrained/ResNet50_pretrained"

VALID:
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 32
    filelist: "data/dataset/mydata/val.list"

TEST:
    seg_num: 25
    short_size: 256
    target_size: 256
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 4
    filelist: "data/dataset/mydata/val.list"

INFER:
    seg_num: 25
    short_size: 256
    target_size: 256
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 1
    filelist: "data/dataset/mydata/val.list"
    video_path: ""
    kinetics_labels: "./data/dataset/kinetics_labels.json"

**Comment by pele228** [comment]
去除top5的统计
