### ISSUE TITLE
tracking 评估报错

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/models#5240]
地址：https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/tracking#%E5%BC%80%E5%A7%8B%E6%B5%8B%E8%AF%95

执行代码：
`!python eval_benchmark.py -d VOT2018 -tr ATOMnet_ep0040_models -te atom.default_vot -e 40`

后报错：
```
=> Evaluating: ATOMnet_ep0040_models.epoch40
loading VOT2018: 100%|██████████████████████████████████| 60/60 [00:00<00:00, 65.12it/s, zebrafish1]
2021-01-28 09:20:00,429-INFO: font search path ['/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf', '/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/afm', '/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
2021-01-28 09:20:00,818-INFO: generated new fontManager
  0%|                                                    | 0/60 [00:00<?, ?it/s]W0128 09:20:00.959059  1191 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 11.0, Runtime API Version: 9.0
W0128 09:20:00.963425  1191 device_context.cc:260] device: 0, cuDNN Version: 7.6.
  0%|                                                    | 0/60 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "eval_benchmark.py", line 315, in <module>
    main()
  File "eval_benchmark.py", line 308, in main
    metrics = run_tracking_and_evaluate(params)
  File "eval_benchmark.py", line 254, in run_tracking_and_evaluate
    run_one_dataset(dataset, params)
  File "eval_benchmark.py", line 204, in run_one_dataset
    run_one_sequence(video, params, tracker=tracker)
  File "eval_benchmark.py", line 167, in run_one_sequence
    pred_bboxes = run_tracker(tracker, video, reset=True)
  File "eval_benchmark.py", line 113, in run_tracker
    tracker.initialize(image, init_bbox)
  File "../pytracking/tracker/atom/atom.py", line 149, in initialize
    self.init_optimization(train_x, init_y)
  File "../pytracking/tracker/atom/atom.py", line 669, in init_optimization
    fig_num=(12, 13, 14))
  File "../pytracking/libs/optimization.py", line 411, in __init__
    self._construct_graph()
  File "../pytracking/libs/optimization.py", line 431, in _construct_graph
    self.f0 = self.problem(self.x_ph, scope)
  File "../pytracking/tracker/atom/optim.py", line 99, in __call__
    training_samples, P).apply(self.projection_activation)
  File "../pytracking/libs/tensorlist.py", line 258, in oplist
    [op(a, b, *args[2:], **kwargs) for a, b in zip(*args[:2])])
  File "../pytracking/libs/tensorlist.py", line 258, in <listcomp>
    [op(a, b, *args[2:], **kwargs) for a, b in zip(*args[:2])])
  File "../pytracking/libs/operation.py", line 59, in conv1x1
    return FConv2D(input, weight)
  File "../pytracking/libs/Fconv2d.py", line 96, in FConv2D
    num_channels = input.shape[channel_dim]
IndexError: tuple index out of range
```

**Comment by iceriver97** [comment]
@zhiqiu

**Comment by zhwesky2010** [comment]
@qingqing01 麻烦模型负责人修复下
