### ISSUE TITLE
模型导出出现Tensor' object has no attribute 'get

### ISSUE THREAD

**Issue by skyriver1** [PaddlePaddle/models#5406]
paddlepaddle-gpu==2.1.3

       state_dict = paddle.load(resume_model_path)
        model.set_state_dict(state_dict)

Traceback (most recent call last):
  File "D:/dnf/PPASR/export_model.py", line 24, in <module>
    trainer.export(save_model_path=args.save_model, resume_model=args.resume_model)
  File "D:\dnf\PPASR\ppasr\trainer.py", line 493, in export
    base_model.set_state_dict(state_dict)
  File "C:\Users\qiegewala\anaconda3\envs\rrr\lib\site-packages\paddle\fluid\framework.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\qiegewala\anaconda3\envs\rrr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1298, in set_state_dict
    match_res = _check_match(key_name, param)
  File "C:\Users\qiegewala\anaconda3\envs\rrr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1282, in _check_match
    state = state_dict.get(key, None)
AttributeError: 'Tensor' object has no attribute 'get'

**Comment by greatsuuny** [comment]
改成这个样子解决了 state = state_dict[key]
