### ISSUE TITLE
AssertionError: Given weight dir /home/b308/hao/models-develop/dygraph/bmn/checkpoint/bmn.pdparams not exist.

### ISSUE THREAD

**Issue by haohaichao** [PaddlePaddle/models#5508]
(czk) b308@b308:~/hao/models-develop/dygraph/bmn$ python eval.py --weights=checkpoint/bmn.pdparams
[INFO: config_utils.py:   80]: ----------------  Test Arguments ----------------
[INFO: config_utils.py:   82]: MODEL:
[INFO: config_utils.py:   84]:     name:BMN
[INFO: config_utils.py:   84]:     tscale:100
[INFO: config_utils.py:   84]:     dscale:100
[INFO: config_utils.py:   84]:     feat_dim:400
[INFO: config_utils.py:   84]:     prop_boundary_ratio:0.5
[INFO: config_utils.py:   84]:     num_sample:32
[INFO: config_utils.py:   84]:     num_sample_perbin:3
[INFO: config_utils.py:   84]:     anno_file:./activitynet_1.3_annotations.json
[INFO: config_utils.py:   84]:     feat_path:./fix_feat_100
[INFO: config_utils.py:   82]: TRAIN:
[INFO: config_utils.py:   84]:     subset:train
[INFO: config_utils.py:   84]:     epoch:9
[INFO: config_utils.py:   84]:     batch_size:16
[INFO: config_utils.py:   84]:     num_threads:8
[INFO: config_utils.py:   84]:     use_gpu:True
[INFO: config_utils.py:   84]:     num_gpus:4
[INFO: config_utils.py:   84]:     learning_rate:0.001
[INFO: config_utils.py:   84]:     learning_rate_decay:0.1
[INFO: config_utils.py:   84]:     lr_decay_iter:4200
[INFO: config_utils.py:   84]:     l2_weight_decay:0.0001
[INFO: config_utils.py:   82]: VALID:
[INFO: config_utils.py:   84]:     subset:validation
[INFO: config_utils.py:   84]:     batch_size:16
[INFO: config_utils.py:   84]:     num_threads:8
[INFO: config_utils.py:   84]:     use_gpu:True
[INFO: config_utils.py:   84]:     num_gpus:4
[INFO: config_utils.py:   82]: TEST:
[INFO: config_utils.py:   84]:     subset:validation
[INFO: config_utils.py:   84]:     batch_size:1
[INFO: config_utils.py:   84]:     num_threads:1
[INFO: config_utils.py:   84]:     snms_alpha:0.001
[INFO: config_utils.py:   84]:     snms_t1:0.5
[INFO: config_utils.py:   84]:     snms_t2:0.9
[INFO: config_utils.py:   84]:     output_path:output/EVAL/BMN_results
[INFO: config_utils.py:   84]:     result_path:evaluate_results
[INFO: config_utils.py:   82]: INFER:
[INFO: config_utils.py:   84]:     subset:test
[INFO: config_utils.py:   84]:     batch_size:1
[INFO: config_utils.py:   84]:     num_threads:1
[INFO: config_utils.py:   84]:     snms_alpha:0.4
[INFO: config_utils.py:   84]:     snms_t1:0.5
[INFO: config_utils.py:   84]:     snms_t2:0.9
[INFO: config_utils.py:   84]:     filelist:./infer.list
[INFO: config_utils.py:   84]:     output_path:output/INFER/BMN_results
[INFO: config_utils.py:   84]:     result_path:predict_results
[INFO: config_utils.py:   85]: -------------------------------------------------
W0427 14:50:08.213558  6388 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0427 14:50:08.214612  6388 device_context.cc:465] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "eval.py", line 220, in <module>
    test_bmn(args)
  File "eval.py", line 143, in test_bmn
    args.weights)
AssertionError: Given weight dir checkpoint/bmn.pdparams not exist.

使用的是动态图进行验证，我可以确定权重文件夹存在，权重文件夹放在/models-develop/dygraph/bmn/checkpoint中，但运行之后系统报给的文件夹不存在。想询问下我这个是哪里除了问题？

**Comment by D-DanielYang** [comment]
BMN模型的一个更好的实现，可以试试PaddleVideo里面的维护的
