### ISSUE TITLE
typo in models/fluid/image_classification/se_resnext.py

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/models#583]
1. 
There must be` reader` instead of `datareader`.
```
train_reader = paddle.batch(datareader.train(), batch_size=batch_size)
```

2. I use the  flowers102 dataset from` paddle.dataset.flowers.train()` and set the batch size to 1, 
but something wrong happened. 
Here is the log:
```
Traceback (most recent call last):
  File "se_resnext.py", line 157, in <module>
    train(learning_rate=0.1, batch_size=1, num_passes=100)
  File "se_resnext.py", line 127, in train
    exe.run(fluid.default_startup_program())
  File "/home/xingzhaolong/.jumbo/lib/python2.7/site-packages/paddle/v2/fluid/executor.py", line 177, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.v2.fluid.core.EnforceNotMet: enforce allocating <= available failed, 10484135494 > 10440015616
 at [/home/xingzhaolong/pr/temp/do_something/paddle/platform/gpu_info.cc:89]
PaddlePaddle Call Stacks: 
0       0x7fab14ccdae6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fab16b8c2eep paddle::platform::GpuMaxChunkSize() + 766
2       0x7fab14d622ebp paddle::memory::GetGPUBuddyAllocator(int) + 139
3       0x7fab14d624fcp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 28
4       0x7fab14cd4f8ap paddle::framework::Tensor::PlaceholderImpl<paddle::platform::CUDAPlace>::PlaceholderImpl(paddle::platform::CUDAPlace, unsigned long, std::type_index) + 58

```
Seems something wrong with the memory allocating.
I use the Graphics with about 10Gb memory.
   2  Tesla K40m          On   | 0000:83:00.0     Off |                    0 |
| N/A   37C    P0    61W / 235W |   1567MiB / 11439MiB |      0%      Default |
I meet the same problem when running `fluid_mnist.py`.
Help welcome .

**Comment by NHZlX** [comment]
https://github.com/PaddlePaddle/Paddle/issues/6265
