### ISSUE TITLE
image_classification mobilenet.py get exception

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/models#785]
Exception is:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
    img = load_image_bytes(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 131, in load_image_bytes
    img = cv2.imdecode(file_bytes, flag)
AttributeError: 'NoneType' object has no attribute 'imdecode'
```

env: docker
paddlepaddle: latest-gpu

**Comment by seiriosPlus** [comment]
I run python standalone, when I exec ```import cv2```, I get exception:
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by seiriosPlus** [comment]
I add 2 apt-get install commands in Dockerfile, now it runs ok.
```
RUN apt-get install -y libglib2.0-0
RUN apt-get install -y libsm6
```
