### ISSUE TITLE
caffe2fluid:failed to do global pool layer convertion

### ISSUE THREAD

**Issue by walloollaw** [PaddlePaddle/models#877]
when try to convert a caffe model with global pooling:
```
Traceback (most recent call last):
  File "../../convert.py", line 80, in <module>
    ret = main()
  File "../../convert.py", line 76, in main
    args.code_output_path, args.phase)
  File "../../convert.py", line 35, in convert
    transformer = Transformer(def_path, caffemodel_path, phase=phase)
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/paddle/transformer.py", line 273, in __init__
    self.load(def_path, data_path, phase)
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/paddle/transformer.py", line 279, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/graph.py", line 285, in build
    graph.compute_output_shapes()
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/graph.py", line 116, in compute_output_shapes
    *NodeKind.compute_output_shape(node))
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/layers.py", line 138, in compute_output_shape
    val = LAYER_DESCRIPTORS[node.kind](node)
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/shapes.py", line 104, in shape_pool
    return get_strided_kernel_output_shape(node, method)
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/shapes.py", line 38, in get_strided_kernel_output_shape
    node.layer.kernel_parameters, round_func)
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/layers.py", line 213, in kernel_parameters
    k_h = self.get_kernel_value(params.kernel_h, params.kernel_size, 0)
  File "/home/vis/wanglong03/paddle_gits/models.git.wallo/fluid/image_classification/caffe2fluid/kaffe/layers.py", line 206, in get_kernel_value
    raise ValueError('Unable to determine kernel parameter!')
ValueError: Unable to determine kernel parameter!
```

**Comment by walloollaw** [comment]
this bug has been fixed now.
